-- ============================================================================
-- UPDATE EFFORTLESS SCHEMA - the derived layer, rebuilt from the rulebook
-- ============================================================================
-- Generated by rulebook-to-postgres. DO NOT EDIT — regenerated every build.
--
-- SAFE IN PRODUCTION. This file never drops a table, never drops a column,
-- and never deletes row data. It brings any database in line with the
-- rulebook that shipped in this same commit.
--
-- Views, calc_*/get_* functions and RLS policies hold NO data: they are a
-- pure function of the rulebook. They are dropped and recreated here rather
-- than migrated. Do NOT hand-write a migration that recreates a view or a
-- calc_* function — re-run this file instead.
--
-- A hand-authored migration is needed ONLY for table/column changes that
-- step 1 below cannot infer, and it should contain nothing else.
-- ============================================================================

BEGIN;
SET timezone = 'UTC';

-- === 1. Additive schema: missing tables and columns ========================
-- CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS only. Never drops.

-- ============================================================================
-- DROP AND CREATE TABLES (drop-all mode) - Clean slate + Normalized schema
-- ============================================================================
-- GENERATED FILE — DO NOT EDIT. Rewritten by every `effortless build`.
--
-- SOURCE OF TRUTH: effortless-rulebook/effortless-rulebook.json
-- Every table below is defined there. To add a table, a column, or a
-- calculated field, edit the rulebook and rebuild — never this file, and
-- never a *b-customize-*.sql file. A table defined outside the rulebook
-- gets no view, no calculated fields, no RuleSpeak and no Explainer DAG.
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- Total Tables: 4
-- Total Raw Fields: 40
-- ============================================================================

SET timezone = 'UTC';

-- ============================================================================
-- DROP ALL OBJECTS - Clean slate for database
-- ============================================================================
-- GENERATED FILE — DO NOT EDIT. Rewritten by every `effortless build`.
-- Generated by rulebook-to-postgres tool
-- ============================================================================

DO $$ 
DECLARE r RECORD; v_count INTEGER := 0;
BEGIN
    RAISE NOTICE 'Dropping views...';
    FOR r IN (SELECT table_name FROM information_schema.views WHERE table_schema = 'public') LOOP
        EXECUTE 'DROP VIEW IF EXISTS ' || quote_ident(r.table_name) || ' CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % views', v_count; v_count := 0;
    
    RAISE NOTICE 'Dropping functions...';
    FOR r IN (SELECT DISTINCT p.proname as function_name, pg_get_function_identity_arguments(p.oid) as function_args
              FROM pg_proc p JOIN pg_namespace n ON p.pronamespace = n.oid
              WHERE n.nspname = 'public' AND p.prokind = 'f') LOOP
        EXECUTE 'DROP FUNCTION IF EXISTS ' || quote_ident(r.function_name) || '(' || r.function_args || ') CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % functions', v_count; v_count := 0;
    
    RAISE NOTICE 'Dropping tables...';
    FOR r IN (SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE') LOOP
        EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.table_name) || ' CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % tables', v_count;
END $$;

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- LanguageCandidates: Table: LanguageCandidates
-- ----------------------------------------------------------------------------
CREATE TABLE language_candidates (
  language_candidate_id               TEXT                 PRIMARY KEY,
  name                                TEXT                ,                     -- Name of the language candidate being classified.
  is_language                         BOOLEAN             ,                     -- The test answer that is intended to match the Family Feud answer to be "correct".
  has_syntax                          BOOLEAN             ,                     -- Does this language candidate have syntax and/or grammar?
  can_be_held                         BOOLEAN             ,                     -- Is this candidate physical/material.  I.e. could it at least theoretically "be held"?
  category                            TEXT                ,                     -- The general high level category of the candidate.
  has_identity                        BOOLEAN             ,                     -- Could this thing be assigned a guid, unique in the universe that would identify it globally?  Like a drivers license or social security number for a person.
  is_parsed                           BOOLEAN             ,                     -- Is the knowledge/information encoded in a form that requires parsing before meaning can be extracted?
  resolves_to_an_ast                  BOOLEAN             ,                     -- Is the knowledge/information encoded in a form that requires parsing before meaning can be extracted?
  has_linear_decoding_pressure        BOOLEAN             ,
  is_stable_ontology_reference        BOOLEAN             ,
  is_live_ontology_editor             BOOLEAN             ,
  is_open_world                       BOOLEAN             ,
  is_closed_world                     BOOLEAN             ,
  distance_from_concept               INTEGER             ,
  dimensionality_while_editing        TEXT                ,
  model_object_facility_layer         TEXT                ,
  sort_order                          INTEGER             
);
COMMENT ON TABLE language_candidates IS 'Table: LanguageCandidates';
COMMENT ON COLUMN language_candidates.name IS 'Name of the language candidate being classified.';
COMMENT ON COLUMN language_candidates.is_language IS 'The test answer that is intended to match the Family Feud answer to be "correct".';
COMMENT ON COLUMN language_candidates.has_syntax IS 'Does this language candidate have syntax and/or grammar?';
COMMENT ON COLUMN language_candidates.can_be_held IS 'Is this candidate physical/material.  I.e. could it at least theoretically "be held"?';
COMMENT ON COLUMN language_candidates.category IS 'The general high level category of the candidate.';
COMMENT ON COLUMN language_candidates.has_identity IS 'Could this thing be assigned a guid, unique in the universe that would identify it globally?  Like a drivers license or social security number for a person.';
COMMENT ON COLUMN language_candidates.is_parsed IS 'Is the knowledge/information encoded in a form that requires parsing before meaning can be extracted?';
COMMENT ON COLUMN language_candidates.resolves_to_an_ast IS 'Is the knowledge/information encoded in a form that requires parsing before meaning can be extracted?';

-- ----------------------------------------------------------------------------
-- IsEverythingALanguage: Table: IsEverythingALanguage
-- ----------------------------------------------------------------------------
CREATE TABLE is_everything_a_language (
  is_everything_a_language_id         TEXT                 PRIMARY KEY,
  name                                TEXT                ,
  argument_name                       TEXT                ,
  argument_category                   TEXT                ,
  step_type                           TEXT                ,
  statement                           TEXT                ,
  formalization                       TEXT                ,
  related_candidate_name              TEXT                ,
  related_candidate_id                TEXT                ,
  evidence_from_rulebook              TEXT                ,
  notes                               TEXT                
);
COMMENT ON TABLE is_everything_a_language IS 'Table: IsEverythingALanguage';

-- ----------------------------------------------------------------------------
-- HockettFeatures: Table: HockettFeatures
-- ----------------------------------------------------------------------------
CREATE TABLE hockett_features (
  hockett_feature_id                  TEXT                 PRIMARY KEY,
  name                                TEXT                ,                     -- The design feature's name, as Hockett gives it.
  feature_number                      INTEGER             ,                     -- Hockett's own numbering, 1 through 13, then 14 through 16 for the 1968 additions.
  definition                          TEXT                ,                     -- What the feature asserts, in plain English.
  is_original_thirteen                BOOLEAN             ,                     -- TRUE for the thirteen features of the 1960 paper; FALSE for the three added in 1968.
  source                              TEXT                                      -- Citation for the feature list.
);
COMMENT ON TABLE hockett_features IS 'Table: HockettFeatures';
COMMENT ON COLUMN hockett_features.name IS 'The design feature''s name, as Hockett gives it.';
COMMENT ON COLUMN hockett_features.feature_number IS 'Hockett''s own numbering, 1 through 13, then 14 through 16 for the 1968 additions.';
COMMENT ON COLUMN hockett_features.definition IS 'What the feature asserts, in plain English.';
COMMENT ON COLUMN hockett_features.is_original_thirteen IS 'TRUE for the thirteen features of the 1960 paper; FALSE for the three added in 1968.';
COMMENT ON COLUMN hockett_features.source IS 'Citation for the feature list.';

-- ----------------------------------------------------------------------------
-- HockettAssessments: Table: HockettAssessments
-- ----------------------------------------------------------------------------
CREATE TABLE hockett_assessments (
  hockett_assessment_id               TEXT                 PRIMARY KEY,
  language_candidate                  TEXT                ,                     -- FK to the candidate being assessed.
  hockett_feature                     TEXT                ,                     -- FK to the design feature being applied.
  verdict                             TEXT                ,                     -- Yes, No, Partial or Unknown. Partial and Unknown exist because the published assessments hedge, and flattening a hedge into a boolean would bury a judgement call in the data.
  verbatim_assessment                 TEXT                ,                     -- The source's exact wording for this cell, so every resolution to Verdict stays auditable.
  source_citation                     TEXT                ,                     -- Where this cell came from, including which column.
  mapping_note                        TEXT                                      -- Empty when this candidate corresponds exactly to the source's column. Otherwise, how the two differ and how far the row should be trusted.
);
COMMENT ON TABLE hockett_assessments IS 'Table: HockettAssessments';
COMMENT ON COLUMN hockett_assessments.language_candidate IS 'FK to the candidate being assessed.';
COMMENT ON COLUMN hockett_assessments.hockett_feature IS 'FK to the design feature being applied.';
COMMENT ON COLUMN hockett_assessments.verdict IS 'Yes, No, Partial or Unknown. Partial and Unknown exist because the published assessments hedge, and flattening a hedge into a boolean would bury a judgement call in the data.';
COMMENT ON COLUMN hockett_assessments.verbatim_assessment IS 'The source''s exact wording for this cell, so every resolution to Verdict stays auditable.';
COMMENT ON COLUMN hockett_assessments.source_citation IS 'Where this cell came from, including which column.';
COMMENT ON COLUMN hockett_assessments.mapping_note IS 'Empty when this candidate corresponds exactly to the source''s column. Otherwise, how the two differ and how far the row should be trusted.';

-- ============================================================================
-- FK INDEXES - Performance only, always applied
-- ============================================================================

-- HockettAssessments
CREATE INDEX IF NOT EXISTS idx_hockett_assessments_language_candidate ON hockett_assessments (language_candidate);
CREATE INDEX IF NOT EXISTS idx_hockett_assessments_hockett_feature ON hockett_assessments (hockett_feature);

-- 2 FK index(es) declared.


-- === 2/3. Drop the derived layer ==========================================
-- Views first (they depend on functions), then functions leaf-up through the
-- DAG. CASCADE handles the dependency order Postgres knows about; the
-- explicit ordering handles calc_* functions that call other calc_*.
DO $drop_derived$
DECLARE r RECORD; v_views INT := 0; v_fns INT := 0;
BEGIN
    -- 2. Views (depend on functions, so they go first).
    FOR r IN (
        SELECT table_name FROM information_schema.views
         WHERE table_schema = 'public' AND table_name LIKE 'vw\_%'
           AND obj_description(
                 (quote_ident(table_schema) || '.' || quote_ident(table_name))::regclass, 'pg_class')
               IS DISTINCT FROM 'effortless:hand-maintained'
    ) LOOP
        EXECUTE 'DROP VIEW IF EXISTS public.' || quote_ident(r.table_name) || ' CASCADE';
        v_views := v_views + 1;
    END LOOP;

    -- 3. Functions, leaf-up through the DAG. A calc_* may call another
    --    calc_*, so depth-ordering avoids dependency errors.
    FOR r IN (
        WITH fn AS (
            SELECT p.oid, p.proname,
                   pg_get_function_identity_arguments(p.oid) AS args,
                   p.prosrc
              FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
             WHERE n.nspname = 'public'
               AND (p.proname LIKE 'calc\_%' OR p.proname LIKE 'get\_%')
               AND COALESCE(obj_description(p.oid, 'pg_proc'), '')
                   IS DISTINCT FROM 'effortless:hand-maintained'
        )
        -- callers before callees: a function whose body names another
        -- generated function is an interior node and must go first.
        SELECT f.proname, f.args,
               (SELECT count(*) FROM fn c
                 WHERE c.oid <> f.oid AND f.prosrc LIKE '%' || c.proname || '%') AS depth
          FROM fn f
         ORDER BY depth DESC, f.proname
    ) LOOP
        EXECUTE 'DROP FUNCTION IF EXISTS public.' || quote_ident(r.proname)
                || '(' || r.args || ') CASCADE';
        v_fns := v_fns + 1;
    END LOOP;

    RAISE NOTICE 'derived layer dropped: % views, % functions', v_views, v_fns;
END
$drop_derived$;


-- === 4. Static reference data =============================================
-- (no tables marked IsStatic — nothing to upsert)

-- === 5. Recreate calc_*/get_* functions ===================================
-- ============================================================================
-- CREATE FUNCTIONS - Calculation functions for lookup/calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- ============================================================================


-- Disable body validation so LANGUAGE sql functions can forward-reference
-- each other within this file. (pg_dump does the same thing for the same
-- reason.) Without this, SQL functions parse-check at CREATE time and fail
-- on the first forward call site; plpgsql didn't, which is how this file
-- ever worked. Dependency order is still enforced at EXECUTION time.
SET check_function_bodies = off;

-- ============================================================================
-- LOOKUP FUNCTIONS
-- These functions perform lookups via foreign key relationships
-- ============================================================================

-- calc_language_candidates_has_grammar
-- Field: LanguageCandidates.HasGrammar
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_language_candidates_has_grammar(p_language_candidate_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((SELECT has_syntax FROM language_candidates WHERE language_candidate_id = p_language_candidate_id) = TRUE)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_language_candidates_question
-- Field: LanguageCandidates.Question
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_language_candidates_question(p_language_candidate_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT('Is ', (SELECT NULLIF(name, '') FROM language_candidates WHERE language_candidate_id = p_language_candidate_id), ' a language?'))::text;
$$ LANGUAGE sql STABLE;

-- calc_language_candidates_predicted_answer
-- Field: LanguageCandidates.PredictedAnswer
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_language_candidates_predicted_answer(p_language_candidate_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((COALESCE((SELECT has_syntax FROM language_candidates WHERE language_candidate_id = p_language_candidate_id), FALSE) AND COALESCE((SELECT is_parsed FROM language_candidates WHERE language_candidate_id = p_language_candidate_id), FALSE) AND calc_language_candidates_is_description_of(p_language_candidate_id) AND COALESCE((SELECT has_linear_decoding_pressure FROM language_candidates WHERE language_candidate_id = p_language_candidate_id), FALSE) AND COALESCE((SELECT resolves_to_an_ast FROM language_candidates WHERE language_candidate_id = p_language_candidate_id), FALSE) AND COALESCE((SELECT is_stable_ontology_reference FROM language_candidates WHERE language_candidate_id = p_language_candidate_id), FALSE) AND NOT (COALESCE((SELECT can_be_held FROM language_candidates WHERE language_candidate_id = p_language_candidate_id), FALSE)) AND NOT (COALESCE((SELECT has_identity FROM language_candidates WHERE language_candidate_id = p_language_candidate_id), FALSE))))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_language_candidates_prediction_predicates
-- Field: LanguageCandidates.PredictionPredicates
-- Type: calculated | DataType: string | Returns: TEXT

CREATE OR REPLACE FUNCTION calc_language_candidates_prediction_predicates(p_language_candidate_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT(CASE WHEN COALESCE((SELECT has_syntax FROM language_candidates WHERE language_candidate_id = p_language_candidate_id), FALSE) THEN ('Has Syntax')::text ELSE ('No Syntax')::text END, ' & ', CASE WHEN COALESCE((SELECT is_parsed FROM language_candidates WHERE language_candidate_id = p_language_candidate_id), FALSE) THEN ('Requires Parsing')::text ELSE ('No Parsing Neede')::text END, ' & ', CASE WHEN calc_language_candidates_is_description_of(p_language_candidate_id) THEN ('Describes the thing')::text ELSE ('Is the Thing')::text END, ' & ', CASE WHEN COALESCE((SELECT has_linear_decoding_pressure FROM language_candidates WHERE language_candidate_id = p_language_candidate_id), FALSE) THEN ('Has Linear Decoding Pressure')::text ELSE ('No Decoding Pressure')::text END, ' & ', CASE WHEN COALESCE((SELECT resolves_to_an_ast FROM language_candidates WHERE language_candidate_id = p_language_candidate_id), FALSE) THEN ('Resolves to AST')::text ELSE ('No AST')::text END, ', ', CASE WHEN COALESCE((SELECT is_stable_ontology_reference FROM language_candidates WHERE language_candidate_id = p_language_candidate_id), FALSE) THEN ('Is Stable Ontology')::text ELSE ('Not ''Ontology''')::text END, ' AND ', CASE WHEN COALESCE((SELECT can_be_held FROM language_candidates WHERE language_candidate_id = p_language_candidate_id), FALSE) THEN ('Can Be Held')::text ELSE ('Can''t Be Held')::text END, ', ', CASE WHEN COALESCE((SELECT has_identity FROM language_candidates WHERE language_candidate_id = p_language_candidate_id), FALSE) THEN ('Has Identity')::text ELSE ('Has no Identity')::text END))::text;
$$ LANGUAGE sql STABLE;

-- calc_language_candidates_prediction_fail
-- Field: LanguageCandidates.PredictionFail
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_language_candidates_prediction_fail(p_language_candidate_id TEXT)
RETURNS TEXT AS $$
  WITH __erb_dedup_v1 AS (SELECT calc_language_candidates_predicted_answer(p_language_candidate_id) AS val) SELECT (CONCAT(CASE WHEN NOT ((SELECT val FROM __erb_dedup_v1) = (SELECT is_language FROM language_candidates WHERE language_candidate_id = p_language_candidate_id)) THEN (CONCAT((SELECT NULLIF(name, '') FROM language_candidates WHERE language_candidate_id = p_language_candidate_id), ' ', CASE WHEN (SELECT val FROM __erb_dedup_v1) THEN ('Is')::text ELSE ('Isn''t')::text END, ' a Family Feud Language, but ', CASE WHEN COALESCE((SELECT is_language FROM language_candidates WHERE language_candidate_id = p_language_candidate_id), FALSE) THEN ('Is')::text ELSE ('Is Not')::text END, ' marked as a ''Language Candidate.'''))::text ELSE ('')::text END, CASE WHEN calc_language_candidates_is_open_closed_world_conflicted(p_language_candidate_id) THEN (' - Open World vs. Closed World Conflict.')::text ELSE ('')::text END))::text;
$$ LANGUAGE sql STABLE;

-- calc_language_candidates_is_description_of
-- Field: LanguageCandidates.IsDescriptionOf
-- Type: calculated | DataType: boolean | Returns: BOOLEAN

CREATE OR REPLACE FUNCTION calc_language_candidates_is_description_of(p_language_candidate_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (((SELECT distance_from_concept FROM language_candidates WHERE language_candidate_id = p_language_candidate_id))::NUMERIC > 1)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_language_candidates_is_open_closed_world_conflicted
-- Field: LanguageCandidates.IsOpenClosedWorldConflicted
-- Type: calculated | DataType: boolean | Returns: BOOLEAN

CREATE OR REPLACE FUNCTION calc_language_candidates_is_open_closed_world_conflicted(p_language_candidate_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((COALESCE((SELECT is_open_world FROM language_candidates WHERE language_candidate_id = p_language_candidate_id), FALSE) AND COALESCE((SELECT is_closed_world FROM language_candidates WHERE language_candidate_id = p_language_candidate_id), FALSE)))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_language_candidates_relationship_to_concept
-- Field: LanguageCandidates.RelationshipToConcept
-- Type: calculated | DataType: string | Returns: TEXT

CREATE OR REPLACE FUNCTION calc_language_candidates_relationship_to_concept(p_language_candidate_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN ((SELECT distance_from_concept FROM language_candidates WHERE language_candidate_id = p_language_candidate_id))::NUMERIC = 1 THEN ('IsMirrorOf')::text ELSE ('IsDescriptionOf')::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_language_candidates_hockett_assessed_count
-- Field: LanguageCandidates.HockettAssessedCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_language_candidates_hockett_assessed_count(p_language_candidate_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM hockett_assessments WHERE language_candidate = (SELECT NULLIF(name, '') FROM language_candidates WHERE language_candidate_id = p_language_candidate_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_language_candidates_hockett_yes_count
-- Field: LanguageCandidates.HockettYesCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_language_candidates_hockett_yes_count(p_language_candidate_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COALESCE(SUM((calc_hockett_assessments_is_yes_flag(hockett_assessment_id))::numeric), 0) FROM hockett_assessments WHERE language_candidate = (SELECT NULLIF(name, '') FROM language_candidates WHERE language_candidate_id = p_language_candidate_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_language_candidates_is_hockett_assessed
-- Field: LanguageCandidates.IsHockettAssessed
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_language_candidates_is_hockett_assessed(p_language_candidate_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((calc_language_candidates_hockett_assessed_count(p_language_candidate_id))::NUMERIC > 0)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_language_candidates_hockett_score
-- Field: LanguageCandidates.HockettScore
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_language_candidates_hockett_score(p_language_candidate_id TEXT)
RETURNS TEXT AS $$
  WITH __erb_dedup_v1 AS (SELECT calc_language_candidates_hockett_assessed_count(p_language_candidate_id) AS val) SELECT (CASE WHEN ((SELECT val FROM __erb_dedup_v1))::NUMERIC = 0 THEN ('not assessed')::text ELSE (CONCAT(calc_language_candidates_hockett_yes_count(p_language_candidate_id), ' of ', (SELECT val FROM __erb_dedup_v1)))::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_language_candidates_hockett_vs_gate
-- Field: LanguageCandidates.HockettVsGate
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_language_candidates_hockett_vs_gate(p_language_candidate_id TEXT)
RETURNS TEXT AS $$
  WITH __erb_dedup_v1 AS (SELECT calc_language_candidates_hockett_assessed_count(p_language_candidate_id) AS val), __erb_dedup_v2 AS (SELECT calc_language_candidates_predicted_answer(p_language_candidate_id) AS val), __erb_dedup_v3 AS (SELECT calc_language_candidates_hockett_yes_count(p_language_candidate_id) AS val) SELECT (CASE WHEN ((SELECT val FROM __erb_dedup_v1))::NUMERIC = 0 THEN ('')::text ELSE (CASE WHEN ((SELECT val FROM __erb_dedup_v2) AND (SELECT val FROM __erb_dedup_v3) < (SELECT val FROM __erb_dedup_v1)) THEN (CONCAT('The eight-clause gate says language; Hockett''s features hold for only ', (SELECT val FROM __erb_dedup_v3), ' of ', (SELECT val FROM __erb_dedup_v1), '.'))::text ELSE (CASE WHEN (NOT ((SELECT val FROM __erb_dedup_v2)) AND (SELECT val FROM __erb_dedup_v3) = (SELECT val FROM __erb_dedup_v1)) THEN ('Hockett''s features all hold, and the eight-clause gate says not a language.')::text ELSE ('')::text END)::text END)::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_hockett_features_assessment_count
-- Field: HockettFeatures.AssessmentCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_hockett_features_assessment_count(p_hockett_feature_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM hockett_assessments WHERE hockett_feature = (SELECT NULLIF(name, '') FROM hockett_features WHERE hockett_feature_id = p_hockett_feature_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_hockett_features_yes_count
-- Field: HockettFeatures.YesCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_hockett_features_yes_count(p_hockett_feature_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COALESCE(SUM((calc_hockett_assessments_is_yes_flag(hockett_assessment_id))::numeric), 0) FROM hockett_assessments WHERE hockett_feature = (SELECT NULLIF(name, '') FROM hockett_features WHERE hockett_feature_id = p_hockett_feature_id)))::integer;
$$ LANGUAGE sql STABLE;

-- get_language_candidates_name
-- Helper function: Get Name from LanguageCandidates by LanguageCandidateId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_language_candidates_name(p_language_candidate_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name FROM language_candidates WHERE language_candidate_id = p_language_candidate_id);
$$ LANGUAGE sql STABLE;

-- get_language_candidates_is_language
-- Helper function: Get IsLanguage from LanguageCandidates by LanguageCandidateId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_language_candidates_is_language(p_language_candidate_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT is_language FROM language_candidates WHERE language_candidate_id = p_language_candidate_id);
$$ LANGUAGE sql STABLE;

-- get_language_candidates_has_syntax
-- Helper function: Get HasSyntax from LanguageCandidates by LanguageCandidateId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_language_candidates_has_syntax(p_language_candidate_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT has_syntax FROM language_candidates WHERE language_candidate_id = p_language_candidate_id);
$$ LANGUAGE sql STABLE;

-- get_language_candidates_can_be_held
-- Helper function: Get CanBeHeld from LanguageCandidates by LanguageCandidateId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_language_candidates_can_be_held(p_language_candidate_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT can_be_held FROM language_candidates WHERE language_candidate_id = p_language_candidate_id);
$$ LANGUAGE sql STABLE;

-- get_language_candidates_category
-- Helper function: Get Category from LanguageCandidates by LanguageCandidateId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_language_candidates_category(p_language_candidate_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT category FROM language_candidates WHERE language_candidate_id = p_language_candidate_id);
$$ LANGUAGE sql STABLE;

-- get_language_candidates_has_identity
-- Helper function: Get HasIdentity from LanguageCandidates by LanguageCandidateId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_language_candidates_has_identity(p_language_candidate_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT has_identity FROM language_candidates WHERE language_candidate_id = p_language_candidate_id);
$$ LANGUAGE sql STABLE;

-- get_language_candidates_is_parsed
-- Helper function: Get IsParsed from LanguageCandidates by LanguageCandidateId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_language_candidates_is_parsed(p_language_candidate_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT is_parsed FROM language_candidates WHERE language_candidate_id = p_language_candidate_id);
$$ LANGUAGE sql STABLE;

-- get_language_candidates_resolves_to_an_ast
-- Helper function: Get ResolvesToAnAST from LanguageCandidates by LanguageCandidateId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_language_candidates_resolves_to_an_ast(p_language_candidate_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT resolves_to_an_ast FROM language_candidates WHERE language_candidate_id = p_language_candidate_id);
$$ LANGUAGE sql STABLE;

-- get_language_candidates_has_linear_decoding_pressure
-- Helper function: Get HasLinearDecodingPressure from LanguageCandidates by LanguageCandidateId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_language_candidates_has_linear_decoding_pressure(p_language_candidate_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT has_linear_decoding_pressure FROM language_candidates WHERE language_candidate_id = p_language_candidate_id);
$$ LANGUAGE sql STABLE;

-- get_language_candidates_is_stable_ontology_reference
-- Helper function: Get IsStableOntologyReference from LanguageCandidates by LanguageCandidateId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_language_candidates_is_stable_ontology_reference(p_language_candidate_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT is_stable_ontology_reference FROM language_candidates WHERE language_candidate_id = p_language_candidate_id);
$$ LANGUAGE sql STABLE;

-- get_language_candidates_is_live_ontology_editor
-- Helper function: Get IsLiveOntologyEditor from LanguageCandidates by LanguageCandidateId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_language_candidates_is_live_ontology_editor(p_language_candidate_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT is_live_ontology_editor FROM language_candidates WHERE language_candidate_id = p_language_candidate_id);
$$ LANGUAGE sql STABLE;

-- get_language_candidates_is_open_world
-- Helper function: Get IsOpenWorld from LanguageCandidates by LanguageCandidateId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_language_candidates_is_open_world(p_language_candidate_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT is_open_world FROM language_candidates WHERE language_candidate_id = p_language_candidate_id);
$$ LANGUAGE sql STABLE;

-- get_language_candidates_is_closed_world
-- Helper function: Get IsClosedWorld from LanguageCandidates by LanguageCandidateId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_language_candidates_is_closed_world(p_language_candidate_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT is_closed_world FROM language_candidates WHERE language_candidate_id = p_language_candidate_id);
$$ LANGUAGE sql STABLE;

-- get_language_candidates_distance_from_concept
-- Helper function: Get DistanceFromConcept from LanguageCandidates by LanguageCandidateId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_language_candidates_distance_from_concept(p_language_candidate_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT distance_from_concept FROM language_candidates WHERE language_candidate_id = p_language_candidate_id);
$$ LANGUAGE sql STABLE;

-- get_language_candidates_dimensionality_while_editing
-- Helper function: Get DimensionalityWhileEditing from LanguageCandidates by LanguageCandidateId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_language_candidates_dimensionality_while_editing(p_language_candidate_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT dimensionality_while_editing FROM language_candidates WHERE language_candidate_id = p_language_candidate_id);
$$ LANGUAGE sql STABLE;

-- get_language_candidates_model_object_facility_layer
-- Helper function: Get ModelObjectFacilityLayer from LanguageCandidates by LanguageCandidateId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_language_candidates_model_object_facility_layer(p_language_candidate_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT model_object_facility_layer FROM language_candidates WHERE language_candidate_id = p_language_candidate_id);
$$ LANGUAGE sql STABLE;

-- get_language_candidates_sort_order
-- Helper function: Get SortOrder from LanguageCandidates by LanguageCandidateId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_language_candidates_sort_order(p_language_candidate_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT sort_order FROM language_candidates WHERE language_candidate_id = p_language_candidate_id);
$$ LANGUAGE sql STABLE;

-- get_hockett_features_name
-- Helper function: Get Name from HockettFeatures by HockettFeatureId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_hockett_features_name(p_hockett_feature_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name FROM hockett_features WHERE hockett_feature_id = p_hockett_feature_id);
$$ LANGUAGE sql STABLE;

-- get_hockett_features_feature_number
-- Helper function: Get FeatureNumber from HockettFeatures by HockettFeatureId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_hockett_features_feature_number(p_hockett_feature_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT feature_number FROM hockett_features WHERE hockett_feature_id = p_hockett_feature_id);
$$ LANGUAGE sql STABLE;

-- get_hockett_features_definition
-- Helper function: Get Definition from HockettFeatures by HockettFeatureId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_hockett_features_definition(p_hockett_feature_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT definition FROM hockett_features WHERE hockett_feature_id = p_hockett_feature_id);
$$ LANGUAGE sql STABLE;

-- get_hockett_features_is_original_thirteen
-- Helper function: Get IsOriginalThirteen from HockettFeatures by HockettFeatureId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_hockett_features_is_original_thirteen(p_hockett_feature_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT is_original_thirteen FROM hockett_features WHERE hockett_feature_id = p_hockett_feature_id);
$$ LANGUAGE sql STABLE;

-- get_hockett_features_source
-- Helper function: Get Source from HockettFeatures by HockettFeatureId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_hockett_features_source(p_hockett_feature_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT source FROM hockett_features WHERE hockett_feature_id = p_hockett_feature_id);
$$ LANGUAGE sql STABLE;

-- calc_hockett_assessments_name
-- Field: HockettAssessments.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_hockett_assessments_name(p_hockett_assessment_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(language_candidate, '') FROM hockett_assessments WHERE hockett_assessment_id = p_hockett_assessment_id), ' / ', (SELECT NULLIF(hockett_feature, '') FROM hockett_assessments WHERE hockett_assessment_id = p_hockett_assessment_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_hockett_assessments_is_yes_flag
-- Field: HockettAssessments.IsYesFlag
-- Type: calculated | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_hockett_assessments_is_yes_flag(p_hockett_assessment_id TEXT)
RETURNS INTEGER AS $$
  SELECT (CASE WHEN (SELECT NULLIF(verdict, '') FROM hockett_assessments WHERE hockett_assessment_id = p_hockett_assessment_id) = 'Yes' THEN (1)::text ELSE (0)::text END)::integer;
$$ LANGUAGE sql STABLE;

-- ============================================================================
-- MANY-SIDE RELATIONSHIP FUNCTIONS
-- These functions aggregate child records for many-side relationships
-- ============================================================================

-- ============================================================================
-- INVERSE RELATIONSHIP FUNCTIONS
-- These functions perform reverse FK lookups for inverse-side relationships
-- ============================================================================



-- === 6. Custom functions (ERBCustomizations) ===
-- ============================================================================
-- SEEDED FROM: rulebook table ERBCustomizations, row "02b-customize-functions.sql" (SQLCode).
-- This file is written ONCE and never overwritten (overwrite: Never), so
-- hand edits here persist. To keep the SQL travelling with the rulebook,
-- edit the ERBCustomizations row instead and delete this file to reseed.
-- ============================================================================

-- Prediction Fail: Returns TRUE when predicted_answer doesn't match is_language
DROP FUNCTION calc_language_candidates_question;

CREATE OR REPLACE FUNCTION public.calc_language_candidates_question(p_language_candidate_id text)
 RETURNS text
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
AS $function$
BEGIN
  RETURN ('Is ' || (SELECT NULLIF(name, '''') FROM language_candidates WHERE language_candidate_id = p_language_candidate_id) || ' a language?')::text;
END;
$function$;

-- calc_language_candidates_bio_hockett_score was removed here. It summed eleven
-- bio_has_* columns that were never declared in the rulebook, so it could only
-- error when called or report every candidate as scoring zero. Hockett's design
-- features are now first-class rulebook data (HockettFeatures,
-- HockettAssessments) and LanguageCandidates.HockettScore is computed from them.
-- The DROP is explicit because a check-add rebuild does not remove a function
-- that has merely stopped being created.
DROP FUNCTION IF EXISTS calc_language_candidates_bio_hockett_score(text);

-- === 7. Recreate vw_* views ===============================================
-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- Total Views: 4
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Drop pass: every rulebook-owned view, reverse iteration order, CASCADE.
-- The rulebook is HEAD — the surviving view set must mirror it exactly.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_hockett_assessments CASCADE;
DROP VIEW IF EXISTS vw_hockett_features CASCADE;
DROP VIEW IF EXISTS vw_is_everything_a_language CASCADE;
DROP VIEW IF EXISTS vw_language_candidates CASCADE;

-- ----------------------------------------------------------------------------
-- vw_language_candidates: Table: LanguageCandidates
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_language_candidates CASCADE;
CREATE VIEW vw_language_candidates WITH (security_invoker = ON) AS
SELECT
  t.language_candidate_id,
  t.name,                                                                       -- Name of the language candidate being classified.
  t.is_language,                                                                -- The test answer that is intended to match the Family Feud answer to be "correct".
  calc_language_candidates_has_grammar(t.language_candidate_id) AS has_grammar, -- Does this candidate have a Grammar?  Generally follows candidates that have syntax also have grammar.
  t.has_syntax,                                                                 -- Does this language candidate have syntax and/or grammar?
  t.can_be_held,                                                                -- Is this candidate physical/material.  I.e. could it at least theoretically "be held"?
  calc_language_candidates_question(t.language_candidate_id) AS question,       -- Question that 100 random people could be asked, family feud style.
  calc_language_candidates_predicted_answer(t.language_candidate_id) AS predicted_answer,-- The predicted answer as the top most popular answer among those in the family feud polling pool.
  calc_language_candidates_prediction_predicates(t.language_candidate_id) AS prediction_predicates,
  calc_language_candidates_prediction_fail(t.language_candidate_id) AS prediction_fail,-- If the family feud answer does not match the chosen language candidates status then this explains what did not match. t also flags (in english) mismatch where a candidate is marked as BOTH open AND closed world which does not make sense.
  t.category,                                                                   -- The general high level category of the candidate.
  t.has_identity,                                                               -- Could this thing be assigned a guid, unique in the universe that would identify it globally?  Like a drivers license or social security number for a person.
  t.is_parsed,                                                                  -- Is the knowledge/information encoded in a form that requires parsing before meaning can be extracted?
  t.resolves_to_an_ast,                                                         -- Is the knowledge/information encoded in a form that requires parsing before meaning can be extracted?
  t.has_linear_decoding_pressure,
  t.is_stable_ontology_reference,
  t.is_live_ontology_editor,
  t.is_open_world,
  t.is_closed_world,
  calc_language_candidates_is_description_of(t.language_candidate_id) AS is_description_of,
  t.distance_from_concept,
  calc_language_candidates_is_open_closed_world_conflicted(t.language_candidate_id) AS is_open_closed_world_conflicted,
  t.dimensionality_while_editing,
  calc_language_candidates_relationship_to_concept(t.language_candidate_id) AS relationship_to_concept,
  t.model_object_facility_layer,
  t.sort_order,
  calc_language_candidates_hockett_assessed_count(t.language_candidate_id) AS hockett_assessed_count,-- How many of Hockett's design features this candidate has a published assessment for. Zero means nobody has assessed it, which is not the same as failing.
  calc_language_candidates_hockett_yes_count(t.language_candidate_id) AS hockett_yes_count,-- How many assessed design features this candidate satisfies outright.
  calc_language_candidates_is_hockett_assessed(t.language_candidate_id) AS is_hockett_assessed,-- TRUE once this candidate has at least one published design-feature assessment.
  calc_language_candidates_hockett_score(t.language_candidate_id) AS hockett_score,-- The design-feature tally as text, reading "not assessed" rather than "0" when there is no published assessment. A hand-written Postgres function used to sum eleven bio_has_* columns that were never in the rulebook, so every candidate silently scored zero; this field replaces it.
  calc_language_candidates_hockett_vs_gate(t.language_candidate_id) AS hockett_vs_gate-- Names the disagreement, in English, when the eight-clause gate and Hockett's design features reach opposite conclusions. Empty when they agree or when the candidate is unassessed.
FROM language_candidates t;

-- ----------------------------------------------------------------------------
-- vw_is_everything_a_language: Table: IsEverythingALanguage
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_is_everything_a_language CASCADE;
CREATE VIEW vw_is_everything_a_language WITH (security_invoker = ON) AS
SELECT
  t.is_everything_a_language_id,
  t.name,
  t.argument_name,
  t.argument_category,
  t.step_type,
  t.statement,
  t.formalization,
  t.related_candidate_name,
  t.related_candidate_id,
  t.evidence_from_rulebook,
  t.notes
FROM is_everything_a_language t;

-- ----------------------------------------------------------------------------
-- vw_hockett_features: Table: HockettFeatures
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_hockett_features CASCADE;
CREATE VIEW vw_hockett_features WITH (security_invoker = ON) AS
SELECT
  t.hockett_feature_id,
  t.name,                                                                       -- The design feature's name, as Hockett gives it.
  t.feature_number,                                                             -- Hockett's own numbering, 1 through 13, then 14 through 16 for the 1968 additions.
  t.definition,                                                                 -- What the feature asserts, in plain English.
  t.is_original_thirteen,                                                       -- TRUE for the thirteen features of the 1960 paper; FALSE for the three added in 1968.
  t.source,                                                                     -- Citation for the feature list.
  calc_hockett_features_assessment_count(t.hockett_feature_id) AS assessment_count,-- How many candidates have been assessed against this feature.
  calc_hockett_features_yes_count(t.hockett_feature_id) AS yes_count            -- How many assessed candidates satisfy this feature outright.
FROM hockett_features t;

-- ----------------------------------------------------------------------------
-- vw_hockett_assessments: Table: HockettAssessments
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_hockett_assessments CASCADE;
CREATE VIEW vw_hockett_assessments WITH (security_invoker = ON) AS
SELECT
  t.hockett_assessment_id,
  calc_hockett_assessments_name(t.hockett_assessment_id) AS name,               -- Logical key: the candidate and the feature being assessed.
  t.language_candidate,                                                         -- FK to the candidate being assessed.
  t.hockett_feature,                                                            -- FK to the design feature being applied.
  t.verdict,                                                                    -- Yes, No, Partial or Unknown. Partial and Unknown exist because the published assessments hedge, and flattening a hedge into a boolean would bury a judgement call in the data.
  t.verbatim_assessment,                                                        -- The source's exact wording for this cell, so every resolution to Verdict stays auditable.
  t.source_citation,                                                            -- Where this cell came from, including which column.
  t.mapping_note,                                                               -- Empty when this candidate corresponds exactly to the source's column. Otherwise, how the two differ and how far the row should be trusted.
  calc_hockett_assessments_is_yes_flag(t.hockett_assessment_id) AS is_yes_flag  -- 1 when the verdict is an outright Yes, else 0. Summed by the rollups on LanguageCandidates and HockettFeatures.
FROM hockett_assessments t;



-- === 8. Custom views (ERBCustomizations) ===
-- ============================================================================
-- SEEDED FROM: rulebook table ERBCustomizations, row "03b-customize-views.sql" (SQLCode).
-- This file is written ONCE and never overwritten (overwrite: Never), so
-- hand edits here persist. To keep the SQL travelling with the rulebook,
-- edit the ERBCustomizations row instead and delete this file to reseed.
-- ============================================================================

-- ============================================================================
-- CUSTOMIZE VIEWS - User-defined views and view extensions
-- ============================================================================
-- This file is for YOUR custom views that should persist across
-- regeneration of the base ERB files.
--
-- IMPORTANT:
--   - This file runs AFTER 03-create-views.sql
--   - All base vw_* views already exist when this runs
--   - This file will NOT be overwritten by ERB regeneration
--
-- ============================================================================

-- Your custom views go here:

-- === 9. Custom RLS (ERBCustomizations) ===
-- (no ERBCustomizations row for this section)

-- NOTE: the RBAC policy layer is generated by
-- effortless-rbac-to-postgres-policies as
-- drop-update-effortless-postgres-policies.sql. It follows this same
-- drop-and-recreate model and must run AFTER this file, because policies
-- reference the columns and views rebuilt above.

-- === 10. Custom data (ERBCustomizations) ===
-- ============================================================================
-- SEEDED FROM: rulebook table ERBCustomizations, row "05b-customize-data.sql" (SQLCode).
-- This file is written ONCE and never overwritten (overwrite: Never), so
-- hand edits here persist. To keep the SQL travelling with the rulebook,
-- edit the ERBCustomizations row instead and delete this file to reseed.
-- ============================================================================

-- ============================================================================
-- CUSTOMIZE DATA - User-defined seed data and data migrations
-- ============================================================================
-- This file is for YOUR custom seed data that should persist across
-- regeneration of the base ERB files.
--
-- IMPORTANT:
--   - This file runs AFTER 05-insert-data.sql
--   - Base seed data already exists when this runs
--   - This file will NOT be overwritten by ERB regeneration
--
-- ============================================================================

-- Your custom data inserts go here:

COMMIT;
