#!/bin/bash
# container-entrypoint.sh -- GENERATED by effortless-rulebook-editor.
#
# Boot sequence inside the container:
#   0. start boot-server.js on the EXTERNAL UI port (5174) IMMEDIATELY -- this
#      is the very first thing that happens, before Postgres or any build, so
#      a browser tab opened at container-start shows a live progress page
#      instead of a connection-refused error. It streams the build log over
#      SSE and exposes a Rebuild button; see boot-server.js for the full
#      contract (state file + log file it watches).
#   1. start local Postgres cluster (bundled in-image, single-container app)
#   2. point the consumed transpilers at the host's dotnet-run processes via
#      host.docker.internal (LOCAL DEV, the default -- see NETWORKING MODE
#      below) or leave normal effortless tool resolution in place (PRODUCTION)
#   3. run `effortless build` once (generates SQL + runs init-db.sh against
#      the local Postgres + generates the Node API + Vite UI + RuleSpeak +
#      RuleSpeak-DE + XLSX export)
#   4. start the generated Node API and Vite UI (Vite binds the INTERNAL port
#      5175 -- boot-server.js proxies 5174 -> 5175 once the build succeeds)
#   5. watch the mounted effortless-rulebook.json AND the boot server's
#      rebuild-trigger file for changes; on either, kill+rebuild+restart
#      everything. Loop forever.
#
# ---------------------------------------------------------------------
# NETWORKING MODE -- read this before touching LOCAL_TOOL_URLS
# ---------------------------------------------------------------------
# Mode A (PRODUCTION, the DEFAULT): normal effortless tool resolution --
# rulebook-to-node-postgres-api / rulebook-to-vite-admin-portal resolve from
# the published registry, same as any other effortless transpiler. This is
# what every user other than the tool's own developer wants.
#
# Mode B (LOCAL DEV): set LOCAL_TOOL_URLS=1 to opt into pointing the
# consumed transpilers at http://host.docker.internal:$LOCAL_API_PORT and
# :$LOCAL_WEB_PORT (defaults 30039/30040 -- the ports the two tools' own
# start.sh scripts bind to on the host), so a `dotnet run` on the host is
# picked up immediately on the next rebuild -- no publish step needed for
# the fast local iteration loop while actively developing those two tools.
# Do NOT hard-code host.docker.internal anywhere outside this one
# conditional block.
# ---------------------------------------------------------------------

set -uo pipefail

RULEBOOK_PATH="/app/effortless-rulebook/effortless-rulebook.json"
BOOT_STATE_FILE="/tmp/boot-state"
BUILD_LOG_FILE="/tmp/current-build.log"
REBUILD_TRIGGER_FILE="/tmp/rebuild-trigger"
API_PID=""
UI_PID=""
BOOT_SERVER_PID=""

echo "booting" > "$BOOT_STATE_FILE"
touch "$BUILD_LOG_FILE" "$REBUILD_TRIGGER_FILE"

echo "[entrypoint] starting boot-server.js on :5174 (immediate progress page + log stream + rebuild button)..."
BOOT_LOG_FILE="$BUILD_LOG_FILE" BOOT_STATE_FILE="$BOOT_STATE_FILE" BOOT_REBUILD_TRIGGER="$REBUILD_TRIGGER_FILE" \
  node /app/boot-server.js > /tmp/boot-server.log 2>&1 &
BOOT_SERVER_PID=$!

# The host's ~/.ssotme is bind-mounted READ-ONLY at /root/.ssotme-ro (auth
# credentials live there and must never be mutated from inside the
# container). `-setToolUrl` (used only in LOCAL_TOOL_URLS mode) needs to
# WRITE a tool_urls.json alongside those credentials, so we copy the
# read-only mount into a writable working copy at /root/.ssotme once at
# startup and point HOME/CLI state there instead. The host's real
# ~/.ssotme is never touched.
if [ -d /root/.ssotme-ro ]; then
  echo "[entrypoint] copying read-only ~/.ssotme mount into a writable working copy..."
  rm -rf /root/.ssotme
  cp -r /root/.ssotme-ro /root/.ssotme
  chmod -R u+w /root/.ssotme
fi

echo "[entrypoint] starting local Postgres cluster..."
mkdir -p /var/lib/postgresql/data
chown -R postgres:postgres /var/lib/postgresql
if [ ! -s /var/lib/postgresql/data/PG_VERSION ]; then
  su postgres -c "/usr/lib/postgresql/*/bin/initdb -D /var/lib/postgresql/data" >/tmp/initdb.log 2>&1
fi
# initdb's default pg_hba.conf only trusts 127.0.0.1/::1 -- a host client
# connecting through the published -p 5432 port arrives via Docker Desktop's
# host-forwarding proxy, which does NOT present a Docker-internal bridge
# address (varies by platform), so a scoped rule can't reliably match. This
# is a disposable, reseeded-every-rebuild dev DB behind the user's own
# firewall -- open trust to any host is fine here.
if ! grep -q "0.0.0.0/0" /var/lib/postgresql/data/pg_hba.conf 2>/dev/null; then
  echo "host    all             all             0.0.0.0/0               trust" >> /var/lib/postgresql/data/pg_hba.conf
  echo "host    all             all             ::/0                    trust" >> /var/lib/postgresql/data/pg_hba.conf
fi
su postgres -c "/usr/lib/postgresql/*/bin/pg_ctl -D /var/lib/postgresql/data -l /tmp/postgres.log -o '-h 0.0.0.0' start"

echo "[entrypoint] waiting for Postgres to accept connections..."
for i in $(seq 1 60); do
  su postgres -c "psql -c 'select 1' >/dev/null 2>&1" && break
  sleep 1
done

# Ensure the app role + database exist (idempotent -- safe on restart loops).
su postgres -c "psql -c \"ALTER USER postgres PASSWORD 'postgres';\" " >/dev/null 2>&1
su postgres -c "createdb rulebookeditor" >/dev/null 2>&1 || true

export PGHOST=localhost
export PGPORT=5432
export PGUSER=postgres
export PGPASSWORD=postgres
export PGDATABASE=rulebookeditor
export DATABASE_URL="postgresql://postgres:postgres@localhost:5432/rulebookeditor"

# Tiny no-args wrapper the "chmodinitdb" pipeline step execs (see comment on
# that step in effortless.editor.json: -exec passes NO arguments through to
# the invoked command, so `chmod +x ./init-db.sh` as one CommandLine token
# stream does not work -- this wrapper takes no CLI args of its own).
# Written into /postgres before every build since rulebook-to-postgres
# creates that directory fresh on the very first build.
mkdir -p /app/postgres
cat > /app/postgres/chmod-initdb.sh <<'EOF'
#!/bin/bash
chmod +x /app/postgres/init-db.sh 2>/dev/null || true
EOF
chmod +x /app/postgres/chmod-initdb.sh

# Default OFF: normal published-tool registry resolution is what every user
# other than the tool's own developer wants. Set LOCAL_TOOL_URLS=1 to opt
# into the fast-iteration path (host.docker.internal -> a `dotnet run` on
# the host) while actively developing the two consumed transpilers.
if [ "${LOCAL_TOOL_URLS:-0}" != "0" ] && [ -n "${LOCAL_TOOL_URLS:-0}" ]; then
  LOCAL_API_PORT="${LOCAL_API_PORT:-30039}"
  LOCAL_WEB_PORT="${LOCAL_WEB_PORT:-30040}"
  echo "[entrypoint] LOCAL_TOOL_URLS active (default) -- pointing consumed transpilers at host.docker.internal"
  effortless -setToolUrl rulebook-to-node-postgres-api=http://host.docker.internal:${LOCAL_API_PORT}
  effortless -setToolUrl rulebook-to-vite-admin-portal=http://host.docker.internal:${LOCAL_WEB_PORT}
else
  echo "[entrypoint] LOCAL_TOOL_URLS=0 -- using normal effortless tool resolution (production mode)"
fi

run_build() {
  echo "building" > "$BOOT_STATE_FILE"
  echo "[entrypoint] $(date -Iseconds) running effortless build..." > "$BUILD_LOG_FILE"
  # The registered initdb step's CommandLine chmods init-db.sh executable
  # before running it -- rulebook-to-postgres emits init-db.sh as a
  # `Never`-overwrite file WITHOUT the execute bit set, and on the very
  # first build it doesn't exist until the preceding rulebooktopostgres
  # step creates it within this same `effortless build` run.
  #
  # `effortless build` runs each ProjectTranspilers step in sequence and
  # keeps going even after one step fails outright (its own exit code
  # reflects only the LAST step, and a failed step's error can be buried
  # under hundreds of lines of unrelated SQL/npm output from steps before
  # and after it). That silence is exactly what made this script
  # undiagnosable in practice: `effortless build` would print one ERROR
  # line deep in the log, then the entrypoint would blithely call
  # start_services() anyway and report success. So: capture full build
  # output to the fixed build-log file (boot-server.js tails this file, so
  # its name must stay stable across rebuilds -- NOT timestamped), ALWAYS
  # scan it for the CLI's own "ERROR:" / "TRANSPILER ERROR" markers
  # regardless of exit code, and if any step failed, print a short,
  # unambiguous summary (which step, what error) before deciding whether to
  # continue.
  #
  # `effortless build` alone does NOT re-resolve `[latest]` for already-
  # pinned transpilers -- effortless.json caches each step's LastUrl /
  # LastVersionUsed from the last time it ran, so a newly published tool
  # version sits unused until something re-pins it. `-upgradeAll` is the
  # documented, project-scoped command for exactly this: it walks every
  # registered ProjectTranspiler and updates its pinned version/URL to the
  # current head, so this rebuild (and every rebuild after it) always
  # consumes whatever is actually live, not a stale build-time snapshot.
  # Runs every time, not just the first build, since a tool can be
  # (re)published at any point while this container is up.
  echo "[entrypoint] $(date -Iseconds) running effortless -upgradeAll to pick up any newly published tool versions..." >> "$BUILD_LOG_FILE"
  (cd /app && effortless -upgradeAll) >> >(tee -a "$BUILD_LOG_FILE") 2>&1
  (cd /app && effortless build) >> >(tee -a "$BUILD_LOG_FILE") 2>&1
  build_status=$?
  echo "[entrypoint] $(date -Iseconds) effortless build finished (exit $build_status)" >> "$BUILD_LOG_FILE"

  failed_steps=$(grep -B2 "^ERROR:" "$BUILD_LOG_FILE" | grep -oE "\*\*\*\* /[a-zA-Z0-9_/-]+: [a-zA-Z0-9_-]+ \*\*\*\*" | sort -u)
  error_lines=$(grep -E "^ERROR:|TRANSPILER ERROR|Failed to connect to transpiler" "$BUILD_LOG_FILE")

  if [ -n "$error_lines" ]; then
    {
      echo ""
      echo "############################################################"
      echo "[entrypoint] BUILD HAD FAILURES -- full log: $BUILD_LOG_FILE"
      if [ -n "$failed_steps" ]; then
        echo "[entrypoint] failed step(s):"
        echo "$failed_steps" | sed 's/^/[entrypoint]   /'
      fi
      echo "[entrypoint] error line(s):"
      echo "$error_lines" | sed 's/^/[entrypoint]   /'
      echo "############################################################"
      echo ""
    } >> "$BUILD_LOG_FILE"
    BUILD_HAD_FAILURES=1
    echo "error" > "$BOOT_STATE_FILE"
  else
    BUILD_HAD_FAILURES=""
  fi
}

start_services() {
  if [ -n "${BUILD_HAD_FAILURES:-}" ]; then
    echo "[entrypoint] SKIPPING service start -- last build failed (see summary above). Fix the failing transpiler/rulebook and save, or click Rebuild."  >> "$BUILD_LOG_FILE"
    return 0
  fi

  if [ ! -f /app/api/index.js ]; then
    echo "[entrypoint] SKIPPING API start -- /app/api/index.js was not generated (rulebook-to-node-postgres-api did not produce expected output)." >> "$BUILD_LOG_FILE"
  else
    echo "[entrypoint] starting generated Node API (port 5177)..." >> "$BUILD_LOG_FILE"
    (cd /app/api && npm install --omit=dev --silent && PORT=5177 node index.js) \
      > /tmp/api.log 2>&1 &
    API_PID=$!
  fi

  if [ ! -d /app/admin-portal ]; then
    echo "[entrypoint] SKIPPING UI start -- /app/admin-portal was not generated (rulebook-to-vite-admin-portal did not produce expected output)." >> "$BUILD_LOG_FILE"
    echo "error" > "$BOOT_STATE_FILE"
    return 0
  fi

  echo "[entrypoint] starting generated Vite UI (internal port 5175, dev server)..." >> "$BUILD_LOG_FILE"
  # `vite dev --host` (not `vite build` + a static server) for v1: this repo
  # already runs its own file-watch/rebuild loop at the rulebook level, so a
  # live dev server that also hot-reloads the generated frontend files
  # themselves (in case a future version regenerates UI source shape, not
  # just data) is simpler to keep correct than wiring a second static-file
  # server + manual rebuild step. Bound to the INTERNAL port 5175 --
  # boot-server.js owns the EXTERNAL port 5174 and proxies to this once ready.
  (cd /app/admin-portal && npm install --silent && API_PROXY_TARGET=http://127.0.0.1:5177 npx vite --host 0.0.0.0 --port 5175) \
    > /tmp/ui.log 2>&1 &
  UI_PID=$!

  echo "[entrypoint] waiting for internal Vite UI to accept connections..."  >> "$BUILD_LOG_FILE"
  for i in $(seq 1 60); do
    curl -sf "http://127.0.0.1:5175/" >/dev/null 2>&1 && break
    sleep 1
  done

  echo "ready" > "$BOOT_STATE_FILE"
}

stop_services() {
  echo "[entrypoint] stopping API (pid $API_PID) and UI (pid $UI_PID)..."
  [ -n "$API_PID" ] && kill "$API_PID" 2>/dev/null
  [ -n "$UI_PID" ] && kill "$UI_PID" 2>/dev/null
  # also reap anything still bound to the two ports (npm/vite spawn children)
  fuser -k 5177/tcp 2>/dev/null || true
  fuser -k 5175/tcp 2>/dev/null || true
  sleep 1
}

run_build
start_services

if [ -n "${BUILD_HAD_FAILURES:-}" ]; then
  echo "[entrypoint] READY STATE: NOT READY -- build failed, see summary above. API/UI are not running."
elif [ -z "${API_PID:-}" ] || [ -z "${UI_PID:-}" ]; then
  echo "[entrypoint] READY STATE: PARTIAL -- one or both generated services did not start (see SKIPPING lines above). Check /tmp/api.log and /tmp/ui.log inside the container."
else
  echo "[entrypoint] READY STATE: services launched -- API on :5177, UI on :5174 (boot-server proxying to internal :5175). (npm install still running in the background may delay first response by 10-30s; check /tmp/api.log / /tmp/ui.log if a port doesn't respond.)"
fi

echo "[entrypoint] watching $RULEBOOK_PATH and $REBUILD_TRIGGER_FILE for changes (Ctrl-C / docker stop to exit)..."
while true; do
  inotifywait -e modify -e close_write -e move -e create "$RULEBOOK_PATH" "$REBUILD_TRIGGER_FILE" >/tmp/watch.log 2>&1
  echo "[entrypoint] $(date -Iseconds) change detected (rulebook edit or Rebuild button) -- rebuilding..."
  stop_services
  run_build
  start_services
done
