#!/bin/bash
# edit-rulebook.sh -- GENERATED by effortless-rulebook-editor.
#
# Thin launcher: builds the rulebook-editor image from the Dockerfile
# emitted alongside this script, then runs ONE container with the correct
# bind mounts. Refresh your browser after editing effortless-rulebook.json --
# the container's filesystem watcher detects the change, re-runs
# `effortless build`, and restarts the API + UI automatically.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

# The image is shared (same Dockerfile everywhere), but the CONTAINER name is
# derived from this install's own directory name so that a project with
# multiple rulebooks -- each with its own installed instance of this tool,
# living alongside its own rulebook -- can run all of them side by side
# without one instance's `docker rm -f`/`docker run --name` colliding with
# another's.
IMAGE_NAME="effortless-rulebook-editor"
CONTAINER_NAME="effortless-rulebook-editor-$(basename "$(pwd)")"

# Host ports are UNPINNED by default -- Docker assigns free ephemeral ports
# (docker run -P) so this never collides with anything else on the host.
# Set RULEBOOK_EDITOR_API_PORT / RULEBOOK_EDITOR_UI_PORT to pin specific
# host ports instead (e.g. for a stable bookmark or a scripted workflow).
API_PORT="${RULEBOOK_EDITOR_API_PORT:-}"
UI_PORT="${RULEBOOK_EDITOR_UI_PORT:-}"

# The rulebook file to mount, relative to this script's own directory.
# Auto-detected since this script can land at different depths depending on
# the RelativePath it was installed under (directly inside effortless-rulebook/,
# a subfolder below it, the project root, ...). Checked in order:
#   1. ./effortless-rulebook.json          (installed alongside the rulebook)
#   2. ../effortless-rulebook.json         (installed one level below it)
#   3. ./effortless-rulebook/effortless-rulebook.json   (installed at project root)
#   4. the first *rulebook*.json found in any of the above locations
#      (covers a differently-named rulebook, e.g. effortless-banking-rulebook.json)
# Override RULEBOOK_FILE (any path relative to this script's directory) if
# none of these match your layout.
if [ -n "${RULEBOOK_FILE:-}" ]; then
  : # explicit override wins, skip auto-detection
elif [ -f "./effortless-rulebook.json" ]; then
  RULEBOOK_FILE="./effortless-rulebook.json"
elif [ -f "../effortless-rulebook.json" ]; then
  RULEBOOK_FILE="../effortless-rulebook.json"
elif [ -f "./effortless-rulebook/effortless-rulebook.json" ]; then
  RULEBOOK_FILE="./effortless-rulebook/effortless-rulebook.json"
else
  RULEBOOK_FILE=$(find . .. -maxdepth 2 -iname "*rulebook*.json" 2>/dev/null | head -n1)
  RULEBOOK_FILE="${RULEBOOK_FILE:-./effortless-rulebook.json}"
fi

# --- LOCAL DEV vs PRODUCTION -------------------------------------------
# Normal registry resolution (published, versioned tools) is the DEFAULT --
# this is what every user other than the tool's own developer wants: the
# container resolves rulebook-to-node-postgres-api / rulebook-to-vite-admin-portal
# from the published registry, same as any other effortless transpiler.
#
# Tool developers actively iterating on those two transpilers' source can opt
# INTO local-dev mode instead, which points the container at their own
# `dotnet run` processes (host.docker.internal:$LOCAL_API_PORT /
# :$LOCAL_WEB_PORT, default 30039/30040) so source edits are picked up on the
# next rebuild with no publish step in the loop:
#   LOCAL_TOOL_URLS=1 ./edit-rulebook.sh
# In that mode, a `dotnet run`'d instance of each tool must be listening on
# the configured port, or the build will fail loudly (see
# container-entrypoint.sh's build-failure summary).
LOCAL_TOOL_URLS="${LOCAL_TOOL_URLS:-0}"
LOCAL_API_PORT="${LOCAL_API_PORT:-30039}"
LOCAL_WEB_PORT="${LOCAL_WEB_PORT:-30040}"

if [ ! -f "$RULEBOOK_FILE" ]; then
  echo "ERROR: rulebook file not found: $(pwd)/$RULEBOOK_FILE" >&2
  echo "  Auto-detection checked ./effortless-rulebook.json, ../effortless-rulebook.json," >&2
  echo "  and ./effortless-rulebook/effortless-rulebook.json relative to this script's own" >&2
  echo "  directory ($(pwd)) but found nothing. Set RULEBOOK_FILE explicitly, e.g.:" >&2
  echo "    RULEBOOK_FILE=../effortless-banking-rulebook.json ./edit-rulebook.sh" >&2
  exit 1
fi

echo "Building $IMAGE_NAME image..."
docker build -t "$IMAGE_NAME" -f Dockerfile .

echo "Stopping any previous $CONTAINER_NAME container..."
docker rm -f "$CONTAINER_NAME" >/dev/null 2>&1 || true

# If the user pinned a port explicitly, free it even if some OTHER container
# (not just a previous run of this one) is holding it -- e.g. a different
# project's dev stack left running on that same pinned port. Without this,
# `docker run` below fails with "port is already allocated" instead of just
# taking over the port. Unpinned (default) ports never need this -- Docker
# always finds a free one.
for PORT_TO_FREE in "$API_PORT" "$UI_PORT"; do
  [ -z "$PORT_TO_FREE" ] && continue
  STALE_CIDS=$(docker ps -q --filter "publish=$PORT_TO_FREE")
  if [ -n "$STALE_CIDS" ]; then
    echo "Port $PORT_TO_FREE is in use by another container -- stopping it..."
    docker rm -f $STALE_CIDS >/dev/null 2>&1 || true
  fi
done

# -p HOST:CONTAINER when pinned, -p CONTAINER (Docker picks a free host port)
# when not.
API_PUBLISH="${API_PORT:+${API_PORT}:}5177"
UI_PUBLISH="${UI_PORT:+${UI_PORT}:}5174"

echo "Starting $CONTAINER_NAME container..."
docker run -d \
  --name "$CONTAINER_NAME" \
  -p "$API_PUBLISH" \
  -p "$UI_PUBLISH" \
  -v "$(pwd)/${RULEBOOK_FILE}:/app/effortless-rulebook/effortless-rulebook.json:ro" \
  -v "$HOME/.ssotme:/root/.ssotme-ro:ro" \
  -e "LOCAL_TOOL_URLS=${LOCAL_TOOL_URLS}" \
  -e "LOCAL_API_PORT=${LOCAL_API_PORT}" \
  -e "LOCAL_WEB_PORT=${LOCAL_WEB_PORT}" \
  "$IMAGE_NAME"

# Resolve the actual host ports Docker assigned (identical to what was
# requested when pinned; freshly picked when left unpinned).
RESOLVED_API_PORT=$(docker port "$CONTAINER_NAME" 5177/tcp | head -n1 | cut -d: -f2)
RESOLVED_UI_PORT=$(docker port "$CONTAINER_NAME" 5174/tcp | head -n1 | cut -d: -f2)

echo ""
echo "effortless-rulebook-editor is starting up."
echo "  API:  http://localhost:${RESOLVED_API_PORT}/api/state"
echo "  UI:   http://localhost:${RESOLVED_UI_PORT}   (shows a live boot/progress page immediately --"
echo "                                       no need to wait before opening it; it hands off"
echo "                                       to the real app automatically once ready, and has"
echo "                                       its own Rebuild button + log view at any time)"
echo ""
echo "Edit effortless-rulebook/effortless-rulebook.json to trigger a rebuild -- the"
echo "container watches the file (and the UI's Rebuild button) and rebuilds automatically."
echo ""
echo "Following container logs now (Ctrl-C stops watching logs -- the container keeps running;"
echo "re-run this script, or 'docker logs -f $CONTAINER_NAME', to watch again)..."
echo ""
exec docker logs -f "$CONTAINER_NAME"
