-- ============================================================================
-- CREATE POLICIES - Row Level Security policies
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- ============================================================================

-- Enable RLS on all tables

ALTER TABLE truth_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE connectives ENABLE ROW LEVEL SECURITY;
ALTER TABLE truth_table_rows ENABLE ROW LEVEL SECURITY;
ALTER TABLE set_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE membership_facts ENABLE ROW LEVEL SECURITY;
ALTER TABLE evaluation_steps ENABLE ROW LEVEL SECURITY;

-- TODO: Add specific RLS policies based on your security requirements
-- Example:
-- CREATE POLICY "Users can view their own data" ON app_user
--   FOR SELECT USING (auth.uid() = user_id);

