export const schema = {
  users: {
    tableName: 'Users',
    snakeName: 'users',
    primaryKey: 'user_id',
    nameField: 'name',
    fields: [
      { name: 'name', label: 'Name', type: 'calculated', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'full_name', label: 'Full Name', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'role', label: 'Role', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'email', label: 'Email', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'is_r_m', label: 'Is R M', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'is_underwriter', label: 'Is Underwriter', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'is_branch_banker', label: 'Is Branch Banker', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'is_admin', label: 'Is Admin', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'count_of_portfolio_businesses', label: 'Count Of Portfolio Businesses', type: 'aggregation', datatype: 'integer', nullable: false, relatedTo: null },
      { name: 'count_of_originated_loans', label: 'Count Of Originated Loans', type: 'aggregation', datatype: 'integer', nullable: false, relatedTo: null },
      { name: 'count_of_underwritten_loans', label: 'Count Of Underwritten Loans', type: 'aggregation', datatype: 'integer', nullable: false, relatedTo: null },
    ],
    rawFields: ['full_name', 'role', 'email'],
    readOnlyFields: ['name', 'is_r_m', 'is_underwriter', 'is_branch_banker', 'is_admin', 'count_of_portfolio_businesses', 'count_of_originated_loans', 'count_of_underwritten_loans'],
  },
  businesses: {
    tableName: 'Businesses',
    snakeName: 'businesses',
    primaryKey: 'business_id',
    nameField: 'name',
    fields: [
      { name: 'name', label: 'Name', type: 'calculated', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'legal_name', label: 'Legal Name', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'business_structure', label: 'Business Structure', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'naics_code', label: 'Naics Code', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'naics_description', label: 'Naics Description', type: 'raw', datatype: 'string', nullable: true, relatedTo: null },
      { name: 'annual_revenue_usd', label: 'Annual Revenue Usd', type: 'raw', datatype: 'number', nullable: true, relatedTo: null },
      { name: 'status', label: 'Status', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'onboarded_at', label: 'Onboarded At', type: 'raw', datatype: 'datetime', nullable: true, relatedTo: null },
      { name: 'relationship_manager', label: 'Relationship Manager', type: 'relationship', datatype: 'string', nullable: false, relatedTo: 'users' },
      { name: 'referral_source', label: 'Referral Source', type: 'relationship', datatype: 'string', nullable: true, relatedTo: 'businesses' },
      { name: 'relationship_manager_label', label: 'Relationship Manager Label', type: 'lookup', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'is_customer', label: 'Is Customer', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'is_prospect', label: 'Is Prospect', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'was_referred', label: 'Was Referred', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'count_of_beneficial_owners', label: 'Count Of Beneficial Owners', type: 'aggregation', datatype: 'integer', nullable: false, relatedTo: null },
      { name: 'count_of_contacts', label: 'Count Of Contacts', type: 'aggregation', datatype: 'integer', nullable: false, relatedTo: null },
      { name: 'count_of_accounts', label: 'Count Of Accounts', type: 'aggregation', datatype: 'integer', nullable: false, relatedTo: null },
      { name: 'count_of_loans', label: 'Count Of Loans', type: 'aggregation', datatype: 'integer', nullable: false, relatedTo: null },
      { name: 'count_of_interactions', label: 'Count Of Interactions', type: 'aggregation', datatype: 'integer', nullable: false, relatedTo: null },
      { name: 'count_of_documents', label: 'Count Of Documents', type: 'aggregation', datatype: 'integer', nullable: false, relatedTo: null },
      { name: 'total_deposit_balance_usd', label: 'Total Deposit Balance Usd', type: 'aggregation', datatype: 'number', nullable: false, relatedTo: null },
      { name: 'total_loan_principal_usd', label: 'Total Loan Principal Usd', type: 'aggregation', datatype: 'number', nullable: false, relatedTo: null },
      { name: 'count_of_classified_loans', label: 'Count Of Classified Loans', type: 'aggregation', datatype: 'integer', nullable: false, relatedTo: null },
      { name: 'has_classified_loan', label: 'Has Classified Loan', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'beneficial_owners_at_cdd_threshold', label: 'Beneficial Owners At Cdd Threshold', type: 'aggregation', datatype: 'integer', nullable: false, relatedTo: null },
      { name: 'meets_cdd_rule', label: 'Meets Cdd Rule', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'portfolio_priority', label: 'Portfolio Priority', type: 'calculated', datatype: 'string', nullable: false, relatedTo: null },
    ],
    rawFields: ['legal_name', 'business_structure', 'naics_code', 'naics_description', 'annual_revenue_usd', 'status', 'onboarded_at'],
    readOnlyFields: ['name', 'relationship_manager_label', 'is_customer', 'is_prospect', 'was_referred', 'count_of_beneficial_owners', 'count_of_contacts', 'count_of_accounts', 'count_of_loans', 'count_of_interactions', 'count_of_documents', 'total_deposit_balance_usd', 'total_loan_principal_usd', 'count_of_classified_loans', 'has_classified_loan', 'beneficial_owners_at_cdd_threshold', 'meets_cdd_rule', 'portfolio_priority'],
  },
  beneficial_owners: {
    tableName: 'BeneficialOwners',
    snakeName: 'beneficial_owners',
    primaryKey: 'beneficial_owner_id',
    nameField: 'name',
    fields: [
      { name: 'name', label: 'Name', type: 'calculated', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'business', label: 'Business', type: 'relationship', datatype: 'string', nullable: false, relatedTo: 'businesses' },
      { name: 'full_name', label: 'Full Name', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'date_of_birth_encrypted', label: 'Date Of Birth Encrypted', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'ssn_encrypted', label: 'Ssn Encrypted', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'address_encrypted', label: 'Address Encrypted', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'ownership_percentage', label: 'Ownership Percentage', type: 'raw', datatype: 'number', nullable: false, relatedTo: null },
      { name: 'is_control_person', label: 'Is Control Person', type: 'raw', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'business_label', label: 'Business Label', type: 'lookup', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'meets25_percent_threshold', label: 'Meets25 Percent Threshold', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'meets_cdd_threshold', label: 'Meets Cdd Threshold', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
    ],
    rawFields: ['full_name', 'date_of_birth_encrypted', 'ssn_encrypted', 'address_encrypted', 'ownership_percentage', 'is_control_person'],
    readOnlyFields: ['name', 'business_label', 'meets25_percent_threshold', 'meets_cdd_threshold'],
  },
  contacts: {
    tableName: 'Contacts',
    snakeName: 'contacts',
    primaryKey: 'contact_id',
    nameField: 'name',
    fields: [
      { name: 'name', label: 'Name', type: 'calculated', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'business', label: 'Business', type: 'relationship', datatype: 'string', nullable: false, relatedTo: 'businesses' },
      { name: 'full_name', label: 'Full Name', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'title', label: 'Title', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'email', label: 'Email', type: 'raw', datatype: 'string', nullable: true, relatedTo: null },
      { name: 'phone', label: 'Phone', type: 'raw', datatype: 'string', nullable: true, relatedTo: null },
      { name: 'contact_type', label: 'Contact Type', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'is_authorized_signer', label: 'Is Authorized Signer', type: 'raw', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'business_label', label: 'Business Label', type: 'lookup', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'is_officer', label: 'Is Officer', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'is_ap_clerk', label: 'Is Ap Clerk', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
    ],
    rawFields: ['full_name', 'title', 'email', 'phone', 'contact_type', 'is_authorized_signer'],
    readOnlyFields: ['name', 'business_label', 'is_officer', 'is_ap_clerk'],
  },
  accounts: {
    tableName: 'Accounts',
    snakeName: 'accounts',
    primaryKey: 'account_id',
    nameField: 'name',
    fields: [
      { name: 'name', label: 'Name', type: 'calculated', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'business', label: 'Business', type: 'relationship', datatype: 'string', nullable: false, relatedTo: 'businesses' },
      { name: 'account_type', label: 'Account Type', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'account_number_last4', label: 'Account Number Last4', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'current_balance_usd', label: 'Current Balance Usd', type: 'raw', datatype: 'number', nullable: false, relatedTo: null },
      { name: 'has_ach', label: 'Has Ach', type: 'raw', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'has_wire', label: 'Has Wire', type: 'raw', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'has_card', label: 'Has Card', type: 'raw', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'opened_at', label: 'Opened At', type: 'raw', datatype: 'datetime', nullable: false, relatedTo: null },
      { name: 'business_label', label: 'Business Label', type: 'lookup', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'treasury_service_count', label: 'Treasury Service Count', type: 'calculated', datatype: 'integer', nullable: false, relatedTo: null },
      { name: 'has_any_treasury_service', label: 'Has Any Treasury Service', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
    ],
    rawFields: ['account_type', 'account_number_last4', 'current_balance_usd', 'has_ach', 'has_wire', 'has_card', 'opened_at'],
    readOnlyFields: ['name', 'business_label', 'treasury_service_count', 'has_any_treasury_service'],
  },
  loans: {
    tableName: 'Loans',
    snakeName: 'loans',
    primaryKey: 'loan_id',
    nameField: 'name',
    fields: [
      { name: 'name', label: 'Name', type: 'calculated', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'loan_number', label: 'Loan Number', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'business', label: 'Business', type: 'relationship', datatype: 'string', nullable: false, relatedTo: 'businesses' },
      { name: 'originating_rm', label: 'Originating Rm', type: 'relationship', datatype: 'string', nullable: false, relatedTo: 'users' },
      { name: 'underwriter', label: 'Underwriter', type: 'relationship', datatype: 'string', nullable: false, relatedTo: 'users' },
      { name: 'loan_purpose', label: 'Loan Purpose', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'principal_usd', label: 'Principal Usd', type: 'raw', datatype: 'number', nullable: false, relatedTo: null },
      { name: 'rate_pct', label: 'Rate Pct', type: 'raw', datatype: 'number', nullable: false, relatedTo: null },
      { name: 'term_months', label: 'Term Months', type: 'raw', datatype: 'integer', nullable: false, relatedTo: null },
      { name: 'underwriting_stage', label: 'Underwriting Stage', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'risk_rating', label: 'Risk Rating', type: 'raw', datatype: 'integer', nullable: false, relatedTo: null },
      { name: 'risk_rating_label', label: 'Risk Rating Label', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'dscr', label: 'Dscr', type: 'raw', datatype: 'number', nullable: true, relatedTo: null },
      { name: 'ltv', label: 'Ltv', type: 'raw', datatype: 'number', nullable: true, relatedTo: null },
      { name: 'global_cash_flow_usd', label: 'Global Cash Flow Usd', type: 'raw', datatype: 'number', nullable: true, relatedTo: null },
      { name: 'originated_at', label: 'Originated At', type: 'raw', datatype: 'datetime', nullable: false, relatedTo: null },
      { name: 'funded_at', label: 'Funded At', type: 'raw', datatype: 'datetime', nullable: true, relatedTo: null },
      { name: 'business_label', label: 'Business Label', type: 'lookup', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'business_naics_code', label: 'Business Naics Code', type: 'lookup', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'originating_rm_label', label: 'Originating Rm Label', type: 'lookup', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'underwriter_is_admin', label: 'Underwriter Is Admin', type: 'lookup', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'is_funded', label: 'Is Funded', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'is_classified_asset', label: 'Is Classified Asset', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'dscr_in_band', label: 'Dscr In Band', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'ltv_in_band', label: 'Ltv In Band', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'segregation_of_duties_ok', label: 'Segregation Of Duties Ok', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'count_of_covenants', label: 'Count Of Covenants', type: 'aggregation', datatype: 'integer', nullable: false, relatedTo: null },
      { name: 'count_of_breached_covenants', label: 'Count Of Breached Covenants', type: 'aggregation', datatype: 'integer', nullable: false, relatedTo: null },
      { name: 'count_of_risk_rating_history', label: 'Count Of Risk Rating History', type: 'aggregation', datatype: 'integer', nullable: false, relatedTo: null },
      { name: 'count_of_documents', label: 'Count Of Documents', type: 'aggregation', datatype: 'integer', nullable: false, relatedTo: null },
      { name: 'has_breached_covenant', label: 'Has Breached Covenant', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'on_watchlist', label: 'On Watchlist', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'health_score', label: 'Health Score', type: 'calculated', datatype: 'integer', nullable: false, relatedTo: null },
    ],
    rawFields: ['loan_number', 'loan_purpose', 'principal_usd', 'rate_pct', 'term_months', 'underwriting_stage', 'risk_rating', 'risk_rating_label', 'dscr', 'ltv', 'global_cash_flow_usd', 'originated_at', 'funded_at'],
    readOnlyFields: ['name', 'business_label', 'business_naics_code', 'originating_rm_label', 'underwriter_is_admin', 'is_funded', 'is_classified_asset', 'dscr_in_band', 'ltv_in_band', 'segregation_of_duties_ok', 'count_of_covenants', 'count_of_breached_covenants', 'count_of_risk_rating_history', 'count_of_documents', 'has_breached_covenant', 'on_watchlist', 'health_score'],
  },
  covenants: {
    tableName: 'Covenants',
    snakeName: 'covenants',
    primaryKey: 'covenant_id',
    nameField: 'name',
    fields: [
      { name: 'name', label: 'Name', type: 'calculated', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'loan', label: 'Loan', type: 'relationship', datatype: 'string', nullable: false, relatedTo: 'loans' },
      { name: 'covenant_type', label: 'Covenant Type', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'threshold_value', label: 'Threshold Value', type: 'raw', datatype: 'number', nullable: true, relatedTo: null },
      { name: 'test_frequency', label: 'Test Frequency', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'next_test_date', label: 'Next Test Date', type: 'raw', datatype: 'datetime', nullable: false, relatedTo: null },
      { name: 'status', label: 'Status', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'current_waiver_through', label: 'Current Waiver Through', type: 'raw', datatype: 'datetime', nullable: true, relatedTo: null },
      { name: 'loan_label', label: 'Loan Label', type: 'lookup', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'loan_business', label: 'Loan Business', type: 'lookup', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'is_breached', label: 'Is Breached', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'has_active_waiver', label: 'Has Active Waiver', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
    ],
    rawFields: ['covenant_type', 'threshold_value', 'test_frequency', 'next_test_date', 'status', 'current_waiver_through'],
    readOnlyFields: ['name', 'loan_label', 'loan_business', 'is_breached', 'has_active_waiver'],
  },
  risk_rating_history: {
    tableName: 'RiskRatingHistory',
    snakeName: 'risk_rating_history',
    primaryKey: 'risk_rating_history_id',
    nameField: 'name',
    fields: [
      { name: 'name', label: 'Name', type: 'calculated', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'loan', label: 'Loan', type: 'relationship', datatype: 'string', nullable: false, relatedTo: 'loans' },
      { name: 'changed_by_user', label: 'Changed By User', type: 'relationship', datatype: 'string', nullable: false, relatedTo: 'users' },
      { name: 'effective_date', label: 'Effective Date', type: 'raw', datatype: 'datetime', nullable: false, relatedTo: null },
      { name: 'prior_grade', label: 'Prior Grade', type: 'raw', datatype: 'integer', nullable: true, relatedTo: null },
      { name: 'new_grade', label: 'New Grade', type: 'raw', datatype: 'integer', nullable: false, relatedTo: null },
      { name: 'reason', label: 'Reason', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'loan_label', label: 'Loan Label', type: 'lookup', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'changed_by_user_label', label: 'Changed By User Label', type: 'lookup', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'grade_delta', label: 'Grade Delta', type: 'calculated', datatype: 'integer', nullable: false, relatedTo: null },
      { name: 'is_downgrade', label: 'Is Downgrade', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'is_initial_rating', label: 'Is Initial Rating', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'crossed_classified_threshold', label: 'Crossed Classified Threshold', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
    ],
    rawFields: ['effective_date', 'prior_grade', 'new_grade', 'reason'],
    readOnlyFields: ['name', 'loan_label', 'changed_by_user_label', 'grade_delta', 'is_downgrade', 'is_initial_rating', 'crossed_classified_threshold'],
  },
  documents: {
    tableName: 'Documents',
    snakeName: 'documents',
    primaryKey: 'document_id',
    nameField: 'name',
    fields: [
      { name: 'name', label: 'Name', type: 'calculated', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'business', label: 'Business', type: 'relationship', datatype: 'string', nullable: true, relatedTo: 'businesses' },
      { name: 'loan', label: 'Loan', type: 'relationship', datatype: 'string', nullable: true, relatedTo: 'loans' },
      { name: 'uploaded_by_user', label: 'Uploaded By User', type: 'relationship', datatype: 'string', nullable: true, relatedTo: 'users' },
      { name: 'filename', label: 'Filename', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'document_type', label: 'Document Type', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'ocr_indexed', label: 'Ocr Indexed', type: 'raw', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'uploaded_via', label: 'Uploaded Via', type: 'raw', datatype: 'string', nullable: true, relatedTo: null },
      { name: 'uploaded_at', label: 'Uploaded At', type: 'raw', datatype: 'datetime', nullable: false, relatedTo: null },
      { name: 'business_label', label: 'Business Label', type: 'lookup', datatype: 'string', nullable: true, relatedTo: null },
      { name: 'loan_label', label: 'Loan Label', type: 'lookup', datatype: 'string', nullable: true, relatedTo: null },
      { name: 'uploaded_by_user_label', label: 'Uploaded By User Label', type: 'lookup', datatype: 'string', nullable: true, relatedTo: null },
      { name: 'attached_to', label: 'Attached To', type: 'calculated', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'from_customer_portal', label: 'From Customer Portal', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
    ],
    rawFields: ['filename', 'document_type', 'ocr_indexed', 'uploaded_via', 'uploaded_at'],
    readOnlyFields: ['name', 'business_label', 'loan_label', 'uploaded_by_user_label', 'attached_to', 'from_customer_portal'],
  },
  interactions: {
    tableName: 'Interactions',
    snakeName: 'interactions',
    primaryKey: 'interaction_id',
    nameField: 'name',
    fields: [
      { name: 'name', label: 'Name', type: 'calculated', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'business', label: 'Business', type: 'relationship', datatype: 'string', nullable: false, relatedTo: 'businesses' },
      { name: 'user', label: 'User', type: 'relationship', datatype: 'string', nullable: true, relatedTo: 'users' },
      { name: 'interaction_type', label: 'Interaction Type', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'subject', label: 'Subject', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'body', label: 'Body', type: 'raw', datatype: 'string', nullable: true, relatedTo: null },
      { name: 'interaction_date', label: 'Interaction Date', type: 'raw', datatype: 'datetime', nullable: false, relatedTo: null },
      { name: 'due_date', label: 'Due Date', type: 'raw', datatype: 'datetime', nullable: true, relatedTo: null },
      { name: 'source', label: 'Source', type: 'raw', datatype: 'string', nullable: true, relatedTo: null },
      { name: 'business_label', label: 'Business Label', type: 'lookup', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'user_label', label: 'User Label', type: 'lookup', datatype: 'string', nullable: true, relatedTo: null },
      { name: 'is_system_event', label: 'Is System Event', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'is_task', label: 'Is Task', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'from_customer', label: 'From Customer', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
      { name: 'is_covenant_event', label: 'Is Covenant Event', type: 'calculated', datatype: 'boolean', nullable: false, relatedTo: null },
    ],
    rawFields: ['interaction_type', 'subject', 'body', 'interaction_date', 'due_date', 'source'],
    readOnlyFields: ['name', 'business_label', 'user_label', 'is_system_event', 'is_task', 'from_customer', 'is_covenant_event'],
  },
  constraints: {
    tableName: 'Constraints',
    snakeName: 'constraints',
    primaryKey: 'constraint_id',
    nameField: 'name',
    fields: [
      { name: 'name', label: 'Name', type: 'calculated', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'constraint_key', label: 'Constraint Key', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'entity', label: 'Entity', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'predicate', label: 'Predicate', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'deontic', label: 'Deontic', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'severity', label: 'Severity', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'message', label: 'Message', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'rule_group', label: 'Rule Group', type: 'raw', datatype: 'string', nullable: true, relatedTo: null },
      { name: 'source_citation', label: 'Source Citation', type: 'raw', datatype: 'string', nullable: true, relatedTo: null },
      { name: 'rule_speak_override', label: 'Rule Speak Override', type: 'raw', datatype: 'string', nullable: true, relatedTo: null },
      { name: 'is_active', label: 'Is Active', type: 'raw', datatype: 'boolean', nullable: false, relatedTo: null },
    ],
    rawFields: ['constraint_key', 'entity', 'predicate', 'deontic', 'severity', 'message', 'rule_group', 'source_citation', 'rule_speak_override', 'is_active'],
    readOnlyFields: ['name'],
  },
  __meta__: {
    tableName: '__meta__',
    snakeName: '__meta__',
    primaryKey: '__meta___id',
    nameField: 'name',
    fields: [
      { name: 'meta_key', label: 'Meta Key', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'name', label: 'Name', type: 'calculated', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'value_type', label: 'Value Type', type: 'raw', datatype: 'string', nullable: false, relatedTo: null },
      { name: 'string_value', label: 'String Value', type: 'raw', datatype: 'string', nullable: true, relatedTo: null },
      { name: 'json_value', label: 'Json Value', type: 'raw', datatype: 'string', nullable: true, relatedTo: null },
    ],
    rawFields: ['meta_key', 'value_type', 'string_value', 'json_value'],
    readOnlyFields: ['name'],
  },
};
