#!/bin/bash
# container-entrypoint.sh -- GENERATED by effortless-rulebook-editor.
#
# Boot sequence inside the container:
#   0. start boot-server.js on the EXTERNAL UI port (5174) IMMEDIATELY -- this
#      is the very first thing that happens, before Postgres or any build, so
#      a browser tab opened at container-start shows a live progress page
#      instead of a connection-refused error. It streams the build log over
#      SSE and exposes a Rebuild button; see boot-server.js for the full
#      contract (state file + log file it watches).
#   1. start local Postgres cluster (bundled in-image, single-container app)
#   2. run `effortless build` once (generates SQL + runs init-db.sh against
#      the local Postgres + generates the Node API + Vite UI + RuleSpeak +
#      RuleSpeak-DE + XLSX export) -- consumed transpilers resolve from the
#      normal published registry, same as any other effortless transpiler
#   3. start the generated Node API and Vite UI (Vite binds the INTERNAL port
#      5175 -- boot-server.js proxies 5174 -> 5175 once the build succeeds)
#   4. watch the mounted effortless-rulebook.json AND the boot server's
#      rebuild-trigger file for changes; on either, first check for pending
#      uncommitted changes (see check_uncommitted_before_build below -- the
#      very first build in step 2 is never gated, since nothing can be
#      pending yet), then kill+rebuild+restart everything. Loop forever.

set -uo pipefail

RULEBOOK_PATH="/app/effortless-rulebook/effortless-rulebook.json"
RULEBOOK_DIR="/app/effortless-rulebook"
BOOT_STATE_FILE="/tmp/boot-state"
BUILD_LOG_FILE="/tmp/current-build.log"
REBUILD_TRIGGER_FILE="/tmp/rebuild-trigger"
# Build-gating on pending uncommitted changes (see check_uncommitted_before_build
# below). CONFLICT_CHOICE_FILE is the signal file boot-server.js's new
# POST /__boot/resolve-conflict route writes to, following the exact same
# poll-a-fixed-path pattern already used for BOOT_STATE_FILE/REBUILD_TRIGGER_FILE
# above -- no new IPC mechanism invented for this.
CONFLICT_CHOICE_FILE="/tmp/conflict-choice"
# Port the generated Node API listens on -- same value start_services() below
# already uses (PORT=5177). Needed here too so the "overwrite" resolution can
# curl the API's own /api/save-changes merge endpoint directly, when that
# instance of the API is still up and reachable (see the caveat in that
# function).
API_PORT=5177
API_PID=""
UI_PID=""
BOOT_SERVER_PID=""

echo "booting" > "$BOOT_STATE_FILE"
touch "$BUILD_LOG_FILE" "$REBUILD_TRIGGER_FILE"
rm -f "$CONFLICT_CHOICE_FILE"

echo "[entrypoint] starting boot-server.js on :5174 (immediate progress page + log stream + rebuild button)..."
BOOT_LOG_FILE="$BUILD_LOG_FILE" BOOT_STATE_FILE="$BOOT_STATE_FILE" BOOT_REBUILD_TRIGGER="$REBUILD_TRIGGER_FILE" \
BOOT_CONFLICT_CHOICE_FILE="$CONFLICT_CHOICE_FILE" \
  node /app/boot-server.js > /tmp/boot-server.log 2>&1 &
BOOT_SERVER_PID=$!

# The host's ~/.ssotme is bind-mounted READ-ONLY at /root/.ssotme-ro (auth
# credentials live there and must never be mutated from inside the
# container). The effortless CLI needs a writable HOME/CLI state directory,
# so we copy the read-only mount into a writable working copy at
# /root/.ssotme once at startup and point HOME/CLI state there instead. The
# host's real ~/.ssotme is never touched.
if [ -d /root/.ssotme-ro ]; then
  echo "[entrypoint] copying read-only ~/.ssotme mount into a writable working copy..."
  rm -rf /root/.ssotme
  cp -r /root/.ssotme-ro /root/.ssotme
  chmod -R u+w /root/.ssotme
fi

echo "[entrypoint] starting local Postgres cluster..."
mkdir -p /var/lib/postgresql/data
chown -R postgres:postgres /var/lib/postgresql
if [ ! -s /var/lib/postgresql/data/PG_VERSION ]; then
  su postgres -c "/usr/lib/postgresql/*/bin/initdb -D /var/lib/postgresql/data" >/tmp/initdb.log 2>&1
fi
# initdb's default pg_hba.conf only trusts 127.0.0.1/::1 -- a host client
# connecting through the published -p 5432 port arrives via Docker Desktop's
# host-forwarding proxy, which does NOT present a Docker-internal bridge
# address (varies by platform), so a scoped rule can't reliably match. This
# is a disposable, reseeded-every-rebuild dev DB behind the user's own
# firewall -- open trust to any host is fine here.
if ! grep -q "0.0.0.0/0" /var/lib/postgresql/data/pg_hba.conf 2>/dev/null; then
  echo "host    all             all             0.0.0.0/0               trust" >> /var/lib/postgresql/data/pg_hba.conf
  echo "host    all             all             ::/0                    trust" >> /var/lib/postgresql/data/pg_hba.conf
fi
su postgres -c "/usr/lib/postgresql/*/bin/pg_ctl -D /var/lib/postgresql/data -l /tmp/postgres.log -o '-h 0.0.0.0' start"

echo "[entrypoint] waiting for Postgres to accept connections..."
for i in $(seq 1 60); do
  su postgres -c "psql -c 'select 1' >/dev/null 2>&1" && break
  sleep 1
done

# Ensure the app role + database exist (idempotent -- safe on restart loops).
su postgres -c "psql -c \"ALTER USER postgres PASSWORD 'postgres';\" " >/dev/null 2>&1
su postgres -c "createdb rulebookeditor" >/dev/null 2>&1 || true

export PGHOST=localhost
export PGPORT=5432
export PGUSER=postgres
export PGPASSWORD=postgres
export PGDATABASE=rulebookeditor
export DATABASE_URL="postgresql://postgres:postgres@localhost:5432/rulebookeditor"

# Tiny no-args wrapper the "chmodinitdb" pipeline step execs (see comment on
# that step in effortless.editor.json: -exec passes NO arguments through to
# the invoked command, so `chmod +x ./init-db.sh` as one CommandLine token
# stream does not work -- this wrapper takes no CLI args of its own).
# Written into /postgres before every build since rulebook-to-postgres
# creates that directory fresh on the very first build.
mkdir -p /app/postgres
cat > /app/postgres/chmod-initdb.sh <<'EOF'
#!/bin/bash
chmod +x /app/postgres/init-db.sh 2>/dev/null || true
EOF
chmod +x /app/postgres/chmod-initdb.sh


check_uncommitted_before_build() {
  # Gate on pending uncommitted-changes log file(s) before any build EXCEPT
  # the very first one at container boot (nothing can be pending yet -- the
  # generated Node API hasn't even started). Called from the watch loop
  # below, never from the first `run_build` at the bottom of this script.
  #
  # Pending files follow the SAME naming convention the generated Node API's
  # uncommitted.js uses (see rulebook-to-node-postgres-api): sibling of the
  # rulebook file, "<rulebookBaseName>.uncommitted-NN.json". We only need to
  # detect them here, not parse/merge them ourselves -- merging is the Node
  # API's job (mergeUncommittedIntoRulebook(), reused as-is by option 3 below).
  local base
  base="$(basename "$RULEBOOK_PATH" .json)"
  local pending
  pending=$(ls "$RULEBOOK_DIR"/${base}.uncommitted-*.json 2>/dev/null || true)
  if [ -z "$pending" ]; then
    return 0
  fi

  echo "[entrypoint] $(date -Iseconds) pending uncommitted changes found -- gating this build:" >> "$BUILD_LOG_FILE"
  echo "$pending" | sed 's/^/[entrypoint]   /' >> "$BUILD_LOG_FILE"

  # Surface the three-way prompt through the existing boot-server UI (the
  # same page that already shows build progress/logs) instead of proceeding
  # silently. Reuses the existing BOOT_STATE_FILE mechanism with a new state
  # value, and the existing poll-a-fixed-path pattern (like
  # REBUILD_TRIGGER_FILE) for waiting on the user's choice.
  echo "awaiting-conflict-resolution" > "$BOOT_STATE_FILE"
  rm -f "$CONFLICT_CHOICE_FILE"

  echo "[entrypoint] waiting for a conflict-resolution choice via the boot page (or POST /__boot/resolve-conflict)..." >> "$BUILD_LOG_FILE"
  while [ ! -f "$CONFLICT_CHOICE_FILE" ]; do
    sleep 1
  done
  local choice
  choice="$(cat "$CONFLICT_CHOICE_FILE")"
  rm -f "$CONFLICT_CHOICE_FILE"
  echo "[entrypoint] $(date -Iseconds) conflict resolution chosen: $choice" >> "$BUILD_LOG_FILE"

  case "$choice" in
    save-as-unresolved)
      # Option 1 (safe default): move the pending file(s) aside into a single
      # merge-conflict snapshot for later manual/LLM reconciliation, then
      # clear the uncommitted log so the build proceeds on the rulebook file
      # exactly as it currently sits on disk.
      local ts
      ts="$(date +%Y%m%dT%H%M%S)"
      local dest="$RULEBOOK_DIR/${base}.merge-conflict-${ts}.json"
      echo "[entrypoint] saving pending uncommitted change(s) to $dest (unresolved, for later reconciliation)" >> "$BUILD_LOG_FILE"
      {
        echo "{"
        echo "  \"savedAt\": \"$(date -Iseconds)\","
        echo "  \"reason\": \"rulebook changed externally while uncommitted changes were pending\","
        echo "  \"sourceFiles\": ["
        local first=1
        for f in $pending; do
          if [ "$first" -eq 1 ]; then first=0; else echo ","; fi
          printf '    %s' "$(cat "$f")"
        done
        echo ""
        echo "  ]"
        echo "}"
      } > "$dest"
      rm -f $pending
      ;;
    discard)
      # Option 2: throw away the pending log entirely -- equivalent to
      # restarting fresh from whatever the rulebook file currently says.
      echo "[entrypoint] discarding pending uncommitted change(s): $pending" >> "$BUILD_LOG_FILE"
      rm -f $pending
      ;;
    overwrite)
      # Option 3 (not recommended): merge the pending uncommitted log into
      # the rulebook file BEFORE the build runs, so the live-edited version
      # wins over whatever changed the file externally. The actual merge
      # logic (mergeUncommittedIntoRulebook()) lives in the Node API's
      # uncommitted.js -- this is bash, so we do NOT reimplement it here. We
      # call the PREVIOUS API instance's own POST /api/save-changes if it's
      # still up and reachable (start_services() hasn't been re-run yet at
      # this point in the loop, so the process from before this rebuild may
      # still be listening on :5177).
      #
      # KNOWN LIMITATION: this only works while the previous API process is
      # still alive and reachable. If it already died/was killed (e.g. this
      # gate is reached from a path where stop_services() already ran, or on
      # first-boot-after-crash), there is no live merge endpoint to call, and
      # this falls back to the safe "save-as-unresolved" behavior instead of
      # silently doing nothing.
      if curl -sf "http://127.0.0.1:${API_PORT}/api/health" >/dev/null 2>&1; then
        echo "[entrypoint] previous API instance still reachable on :${API_PORT} -- calling POST /api/save-changes to merge uncommitted changes into the rulebook file..." >> "$BUILD_LOG_FILE"
        curl -sf -X POST "http://127.0.0.1:${API_PORT}/api/save-changes" >> "$BUILD_LOG_FILE" 2>&1 || \
          echo "[entrypoint] WARNING: POST /api/save-changes failed -- rulebook file was NOT overwritten with uncommitted changes" >> "$BUILD_LOG_FILE"
      else
        echo "[entrypoint] WARNING: previous API instance is not reachable on :${API_PORT} -- cannot merge via /api/save-changes." >> "$BUILD_LOG_FILE"
        echo "[entrypoint]          falling back to 'save-as-unresolved' so no data is silently lost."  >> "$BUILD_LOG_FILE"
        local ts2
        ts2="$(date +%Y%m%dT%H%M%S)"
        local dest2="$RULEBOOK_DIR/${base}.merge-conflict-${ts2}.json"
        {
          echo "{"
          echo "  \"savedAt\": \"$(date -Iseconds)\","
          echo "  \"reason\": \"overwrite was chosen but the previous API instance was not reachable\","
          echo "  \"sourceFiles\": ["
          local first2=1
          for f in $pending; do
            if [ "$first2" -eq 1 ]; then first2=0; else echo ","; fi
            printf '    %s' "$(cat "$f")"
          done
          echo ""
          echo "  ]"
          echo "}"
        } > "$dest2"
      fi
      rm -f $pending
      ;;
    *)
      echo "[entrypoint] WARNING: unrecognized conflict-resolution choice '$choice' -- treating as 'save-as-unresolved'" >> "$BUILD_LOG_FILE"
      local ts3
      ts3="$(date +%Y%m%dT%H%M%S)"
      cat $pending > "$RULEBOOK_DIR/${base}.merge-conflict-${ts3}.json" 2>/dev/null || true
      rm -f $pending
      ;;
  esac
}

run_build() {
  echo "building" > "$BOOT_STATE_FILE"
  echo "[entrypoint] $(date -Iseconds) running effortless build..." > "$BUILD_LOG_FILE"
  # The registered initdb step's CommandLine chmods init-db.sh executable
  # before running it -- rulebook-to-postgres emits init-db.sh as a
  # `Never`-overwrite file WITHOUT the execute bit set, and on the very
  # first build it doesn't exist until the preceding rulebooktopostgres
  # step creates it within this same `effortless build` run.
  #
  # `effortless build` runs each ProjectTranspilers step in sequence and
  # keeps going even after one step fails outright (its own exit code
  # reflects only the LAST step, and a failed step's error can be buried
  # under hundreds of lines of unrelated SQL/npm output from steps before
  # and after it). That silence is exactly what made this script
  # undiagnosable in practice: `effortless build` would print one ERROR
  # line deep in the log, then the entrypoint would blithely call
  # start_services() anyway and report success. So: capture full build
  # output to the fixed build-log file (boot-server.js tails this file, so
  # its name must stay stable across rebuilds -- NOT timestamped), ALWAYS
  # scan it for the CLI's own "ERROR:" / "TRANSPILER ERROR" markers
  # regardless of exit code, and if any step failed, print a short,
  # unambiguous summary (which step, what error) before deciding whether to
  # continue.
  #
  # `effortless build` alone does NOT re-resolve `[latest]` for already-
  # pinned transpilers -- effortless.json caches each step's LastUrl /
  # LastVersionUsed from the last time it ran, so a newly published tool
  # version sits unused until something re-pins it. `-upgradeAll` is the
  # documented, project-scoped command for exactly this: it walks every
  # registered ProjectTranspiler and updates its pinned version/URL to the
  # current head, so this rebuild (and every rebuild after it) always
  # consumes whatever is actually live, not a stale build-time snapshot.
  # Runs every time, not just the first build, since a tool can be
  # (re)published at any point while this container is up.
  echo "[entrypoint] $(date -Iseconds) running effortless -upgradeAll to pick up any newly published tool versions..." >> "$BUILD_LOG_FILE"
  (cd /app && effortless -upgradeAll) >> >(tee -a "$BUILD_LOG_FILE") 2>&1
  (cd /app && effortless build) >> >(tee -a "$BUILD_LOG_FILE") 2>&1
  build_status=$?
  echo "[entrypoint] $(date -Iseconds) effortless build finished (exit $build_status)" >> "$BUILD_LOG_FILE"

  failed_steps=$(grep -B2 "^ERROR:" "$BUILD_LOG_FILE" | grep -oE "\*\*\*\* /[a-zA-Z0-9_/-]+: [a-zA-Z0-9_-]+ \*\*\*\*" | sort -u)
  error_lines=$(grep -E "^ERROR:|TRANSPILER ERROR|Failed to connect to transpiler" "$BUILD_LOG_FILE")

  if [ -n "$error_lines" ]; then
    {
      echo ""
      echo "############################################################"
      echo "[entrypoint] BUILD HAD FAILURES -- full log: $BUILD_LOG_FILE"
      if [ -n "$failed_steps" ]; then
        echo "[entrypoint] failed step(s):"
        echo "$failed_steps" | sed 's/^/[entrypoint]   /'
      fi
      echo "[entrypoint] error line(s):"
      echo "$error_lines" | sed 's/^/[entrypoint]   /'
      echo "############################################################"
      echo ""
    } >> "$BUILD_LOG_FILE"
    BUILD_HAD_FAILURES=1
    echo "error" > "$BOOT_STATE_FILE"
  else
    BUILD_HAD_FAILURES=""
  fi
}

start_services() {
  if [ -n "${BUILD_HAD_FAILURES:-}" ]; then
    echo "[entrypoint] SKIPPING service start -- last build failed (see summary above). Fix the failing transpiler/rulebook and save, or click Rebuild."  >> "$BUILD_LOG_FILE"
    return 0
  fi

  if [ ! -f /app/api/index.js ]; then
    echo "[entrypoint] SKIPPING API start -- /app/api/index.js was not generated (rulebook-to-node-postgres-api did not produce expected output)." >> "$BUILD_LOG_FILE"
  else
    echo "[entrypoint] starting generated Node API (port 5177)..." >> "$BUILD_LOG_FILE"
    (cd /app/api && npm install --omit=dev --silent && PORT=5177 node index.js) \
      > /tmp/api.log 2>&1 &
    API_PID=$!
  fi

  if [ ! -d /app/admin-portal ]; then
    echo "[entrypoint] SKIPPING UI start -- /app/admin-portal was not generated (rulebook-to-vite-admin-portal did not produce expected output)." >> "$BUILD_LOG_FILE"
    echo "error" > "$BOOT_STATE_FILE"
    return 0
  fi

  echo "[entrypoint] starting generated Vite UI (internal port 5175, dev server)..." >> "$BUILD_LOG_FILE"
  # `vite dev --host` (not `vite build` + a static server) for v1: this repo
  # already runs its own file-watch/rebuild loop at the rulebook level, so a
  # live dev server that also hot-reloads the generated frontend files
  # themselves (in case a future version regenerates UI source shape, not
  # just data) is simpler to keep correct than wiring a second static-file
  # server + manual rebuild step. Bound to the INTERNAL port 5175 --
  # boot-server.js owns the EXTERNAL port 5174 and proxies to this once ready.
  (cd /app/admin-portal && npm install --silent && API_PROXY_TARGET=http://127.0.0.1:5177 npx vite --host 0.0.0.0 --port 5175) \
    > /tmp/ui.log 2>&1 &
  UI_PID=$!

  echo "[entrypoint] waiting for internal Vite UI to accept connections..."  >> "$BUILD_LOG_FILE"
  for i in $(seq 1 60); do
    curl -sf "http://127.0.0.1:5175/" >/dev/null 2>&1 && break
    sleep 1
  done

  echo "ready" > "$BOOT_STATE_FILE"
}

stop_services() {
  echo "[entrypoint] stopping API (pid $API_PID) and UI (pid $UI_PID)..."
  [ -n "$API_PID" ] && kill "$API_PID" 2>/dev/null
  [ -n "$UI_PID" ] && kill "$UI_PID" 2>/dev/null
  # also reap anything still bound to the two ports (npm/vite spawn children)
  fuser -k 5177/tcp 2>/dev/null || true
  fuser -k 5175/tcp 2>/dev/null || true
  sleep 1
}

run_build
start_services

if [ -n "${BUILD_HAD_FAILURES:-}" ]; then
  echo "[entrypoint] READY STATE: NOT READY -- build failed, see summary above. API/UI are not running."
elif [ -z "${API_PID:-}" ] || [ -z "${UI_PID:-}" ]; then
  echo "[entrypoint] READY STATE: PARTIAL -- one or both generated services did not start (see SKIPPING lines above). Check /tmp/api.log and /tmp/ui.log inside the container."
else
  echo "[entrypoint] READY STATE: services launched -- API on :5177, UI on :5174 (boot-server proxying to internal :5175). (npm install still running in the background may delay first response by 10-30s; check /tmp/api.log / /tmp/ui.log if a port doesn't respond.)"
fi

echo "[entrypoint] watching $RULEBOOK_PATH and $REBUILD_TRIGGER_FILE for changes (Ctrl-C / docker stop to exit)..."
while true; do
  inotifywait -e modify -e close_write -e move -e create "$RULEBOOK_PATH" "$REBUILD_TRIGGER_FILE" >/tmp/watch.log 2>&1
  echo "[entrypoint] $(date -Iseconds) change detected (rulebook edit or Rebuild button) -- rebuilding..."
  # Every build from here on (file-watcher-triggered OR Rebuild-button/
  # rebuild-trigger-triggered) is gated on pending uncommitted changes -- the
  # FIRST build above (before this loop) is deliberately NOT gated, since
  # nothing can be pending yet at container boot.
  check_uncommitted_before_build
  stop_services
  run_build
  start_services
done
