#!/bin/bash
# edit-rulebook.sh -- GENERATED by effortless-rulebook-editor.
#
# Thin launcher: builds the rulebook-editor image from the Dockerfile
# emitted alongside this script, then runs ONE container with the correct
# bind mounts. Refresh your browser after editing effortless-rulebook.json --
# the container's filesystem watcher detects the change, re-runs
# `effortless build`, and restarts the API + UI automatically.
#
# This script is expected to land at:
#   <project-root>/effortless-rulebook/docker/edit-rulebook.sh
# i.e. ONE level below effortless-rulebook/. The mount path below
# (../effortless-rulebook.json's parent, "..") is relative to THIS script's
# own directory -- adjust ../.. instead if you installed this tool at a
# different RelativePath.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

IMAGE_NAME="effortless-rulebook-editor"
CONTAINER_NAME="effortless-rulebook-editor"
API_PORT="${RULEBOOK_EDITOR_API_PORT:-5177}"
UI_PORT="${RULEBOOK_EDITOR_UI_PORT:-5174}"

# --- LOCAL DEV vs PRODUCTION -------------------------------------------
# Both consumed transpilers (rulebook-to-node-postgres-api,
# rulebook-to-vite-admin-portal) are published to cpln.app, so PRODUCTION
# mode is the default: normal effortless tool resolution, no overrides.
#
# Set LOCAL_TOOL_URLS=1 ONLY if you are actively developing one of those two
# tools and want this container to hit your own `dotnet run` process instead
# of the published version -- e.g.:
#   LOCAL_TOOL_URLS=1 LOCAL_API_PORT=30039 ./edit-rulebook.sh
LOCAL_TOOL_URLS="${LOCAL_TOOL_URLS:-}"
LOCAL_API_PORT="${LOCAL_API_PORT:-30039}"
LOCAL_WEB_PORT="${LOCAL_WEB_PORT:-30040}"

echo "Building $IMAGE_NAME image..."
docker build -t "$IMAGE_NAME" -f Dockerfile .

echo "Stopping any previous $CONTAINER_NAME container..."
docker rm -f "$CONTAINER_NAME" >/dev/null 2>&1 || true

echo "Starting $CONTAINER_NAME..."
docker run -d \
  --name "$CONTAINER_NAME" \
  -p "${API_PORT}:5177" \
  -p "${UI_PORT}:5174" \
  -v "$(pwd)/../effortless-rulebook.json:/app/effortless-rulebook/effortless-rulebook.json:ro" \
  -v "$HOME/.ssotme:/root/.ssotme-ro:ro" \
  -e "LOCAL_TOOL_URLS=${LOCAL_TOOL_URLS}" \
  -e "LOCAL_API_PORT=${LOCAL_API_PORT}" \
  -e "LOCAL_WEB_PORT=${LOCAL_WEB_PORT}" \
  "$IMAGE_NAME"

echo ""
echo "effortless-rulebook-editor is starting up (first build can take a while -- live"
echo "network calls to the transpiler catalog, then a Postgres init). Watch progress with:"
echo "  docker logs -f $CONTAINER_NAME"
echo ""
echo "Once ready:"
echo "  API:  http://localhost:${API_PORT}/api/state"
echo "  UI:   http://localhost:${UI_PORT}"
echo ""
echo "Edit effortless-rulebook/effortless-rulebook.json and refresh the UI -- the"
echo "container watches the file and rebuilds automatically."
