-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- Total Views: 8
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Drop pass: every rulebook-owned view, reverse iteration order, CASCADE.
-- The rulebook is HEAD — the surviving view set must mirror it exactly.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_ratings CASCADE;
DROP VIEW IF EXISTS vw_crew_assignments CASCADE;
DROP VIEW IF EXISTS vw_movies CASCADE;
DROP VIEW IF EXISTS vw_people CASCADE;
DROP VIEW IF EXISTS vw_crew_types CASCADE;
DROP VIEW IF EXISTS vw_episodes CASCADE;
DROP VIEW IF EXISTS vw_seasons CASCADE;
DROP VIEW IF EXISTS vw_series CASCADE;

-- ----------------------------------------------------------------------------
-- vw_series: Table: Series
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_series CASCADE;
CREATE VIEW vw_series WITH (security_invoker = ON) AS
SELECT
  t.serie_id,
  calc_series_name(t.serie_id) AS name,
  t.series_number,
  t.show_code,
  t.title,
  t.description,
  t.network,
  t.premiere_date,
  t.finale_date,
  calc_series_total_seasons(t.serie_id) AS total_seasons,
  calc_series_total_episodes(t.serie_id) AS total_episodes,
  calc_series_is_long_running(t.serie_id) AS is_long_running,
  calc_series_seasons(t.serie_id) AS seasons,
  calc_series_series_ratings(t.serie_id) AS series_ratings,
  calc_series_rating(t.serie_id) AS rating,
  calc_series_is_good(t.serie_id) AS is_good
FROM series t;

-- ----------------------------------------------------------------------------
-- vw_seasons: Table: Seasons
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_seasons CASCADE;
CREATE VIEW vw_seasons WITH (security_invoker = ON) AS
SELECT
  t.season_id,
  calc_seasons_name(t.season_id) AS name,
  t.series,
  calc_seasons_show_title(t.season_id) AS show_title,
  calc_seasons_show_description(t.season_id) AS show_description,
  calc_seasons_show_network(t.season_id) AS show_network,
  t.season_number,
  t.title,
  t.description,
  t.start_airdate,
  t.end_airdate,
  calc_seasons_episode_count(t.season_id) AS episode_count,
  calc_seasons_episodes(t.season_id) AS episodes,
  t.mock_data_notes
FROM seasons t;

-- ----------------------------------------------------------------------------
-- vw_episodes: Table: Episodes
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_episodes CASCADE;
CREATE VIEW vw_episodes WITH (security_invoker = ON) AS
SELECT
  t.episode_id,
  calc_episodes_name(t.episode_id) AS name,
  t.season,
  calc_episodes_season_number(t.episode_id) AS season_number,
  calc_episodes_season_title(t.episode_id) AS season_title,
  calc_episodes_season_description(t.episode_id) AS season_description,
  t.episode_number,
  t.description,
  t.airdate,
  t.writers,
  t.director,
  t.runtime_minutes,
  t.ratings,
  t.one_sentence_summary,
  t.favorite_color
FROM episodes t;

-- ----------------------------------------------------------------------------
-- vw_crew_types: Table: CrewTypes
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_crew_types CASCADE;
CREATE VIEW vw_crew_types WITH (security_invoker = ON) AS
SELECT
  t.crew_type_id,
  t.name,
  t.description
FROM crew_types t;

-- ----------------------------------------------------------------------------
-- vw_people: Table: People
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_people CASCADE;
CREATE VIEW vw_people WITH (security_invoker = ON) AS
SELECT
  t.person_id,
  t.name,
  t.birth_year,
  t.nationality,
  t.bio,
  t.crew_assignments
FROM people t;

-- ----------------------------------------------------------------------------
-- vw_movies: Table: Movies
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_movies CASCADE;
CREATE VIEW vw_movies WITH (security_invoker = ON) AS
SELECT
  t.movie_id,
  calc_movies_name(t.movie_id) AS name,
  t.movie_number,
  t.title,
  t.description,
  t.release_date,
  t.runtime_minutes,
  t.budget,
  t.box_office,
  t.crew_assignments,
  calc_movies_crew_count(t.movie_id) AS crew_count,
  t.director_name
FROM movies t;

-- ----------------------------------------------------------------------------
-- vw_crew_assignments: Table: CrewAssignments
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_crew_assignments CASCADE;
CREATE VIEW vw_crew_assignments WITH (security_invoker = ON) AS
SELECT
  t.crew_assignment_id,
  calc_crew_assignments_name(t.crew_assignment_id) AS name,
  t.person,
  calc_crew_assignments_person_name(t.crew_assignment_id) AS person_name,
  t.movie,
  calc_crew_assignments_movie_title(t.crew_assignment_id) AS movie_title,
  t.crew_type,
  calc_crew_assignments_crew_type_name(t.crew_assignment_id) AS crew_type_name,
  t.notes
FROM crew_assignments t;

-- ----------------------------------------------------------------------------
-- vw_ratings: Table: Ratings
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_ratings CASCADE;
CREATE VIEW vw_ratings WITH (security_invoker = ON) AS
SELECT
  t.rating_id,
  calc_ratings_name(t.rating_id) AS name,
  calc_ratings_display_name(t.rating_id) AS display_name,
  t.rating,
  t.series,
  calc_ratings_series_name(t.rating_id) AS series_name,
  t.episode,
  calc_ratings_episode_name(t.rating_id) AS episode_name,
  calc_ratings_episode_season_title(t.rating_id) AS episode_season_title,
  t.users_name,
  t.email_address,
  t.phone_nmber,
  t.notes,
  t.created_at
FROM ratings t;

