-- ============================================================================
-- CREATE POLICIES - Row Level Security policies
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- ============================================================================

-- Enable RLS on all tables

ALTER TABLE series ENABLE ROW LEVEL SECURITY;
ALTER TABLE seasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE episodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE crew_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE people ENABLE ROW LEVEL SECURITY;
ALTER TABLE movies ENABLE ROW LEVEL SECURITY;
ALTER TABLE crew_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE ratings ENABLE ROW LEVEL SECURITY;

-- TODO: Add specific RLS policies based on your security requirements
-- Example:
-- CREATE POLICY "Users can view their own data" ON app_user
--   FOR SELECT USING (auth.uid() = user_id);

