-- ============================================================================
-- DROP AND CREATE TABLES (drop-all mode) - Clean slate + Normalized schema
-- ============================================================================
-- GENERATED FILE — DO NOT EDIT. Rewritten by every `effortless build`.
--
-- SOURCE OF TRUTH: effortless-rulebook/effortless-rulebook.json
-- Every table below is defined there. To add a table, a column, or a
-- calculated field, edit the rulebook and rebuild — never this file, and
-- never a *b-customize-*.sql file. A table defined outside the rulebook
-- gets no view, no calculated fields, no RuleSpeak and no Explainer DAG.
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- Total Tables: 1
-- Total Raw Fields: 4
-- ============================================================================

SET timezone = 'UTC';

-- ============================================================================
-- DROP ALL OBJECTS - Clean slate for database
-- ============================================================================
-- GENERATED FILE — DO NOT EDIT. Rewritten by every `effortless build`.
-- Generated by rulebook-to-postgres tool
-- ============================================================================

DO $$ 
DECLARE r RECORD; v_count INTEGER := 0;
BEGIN
    RAISE NOTICE 'Dropping views...';
    FOR r IN (SELECT table_name FROM information_schema.views WHERE table_schema = 'public') LOOP
        EXECUTE 'DROP VIEW IF EXISTS ' || quote_ident(r.table_name) || ' CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % views', v_count; v_count := 0;
    
    RAISE NOTICE 'Dropping functions...';
    FOR r IN (SELECT DISTINCT p.proname as function_name, pg_get_function_identity_arguments(p.oid) as function_args
              FROM pg_proc p JOIN pg_namespace n ON p.pronamespace = n.oid
              WHERE n.nspname = 'public' AND p.prokind = 'f') LOOP
        EXECUTE 'DROP FUNCTION IF EXISTS ' || quote_ident(r.function_name) || '(' || r.function_args || ') CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % functions', v_count; v_count := 0;
    
    RAISE NOTICE 'Dropping tables...';
    FOR r IN (SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE') LOOP
        EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.table_name) || ' CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % tables', v_count;
END $$;

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Customers: Table: Customers
-- ----------------------------------------------------------------------------
CREATE TABLE customers (
  customer_id                         TEXT                 PRIMARY KEY,
  email_address                       TEXT                ,                     -- The customer's email address
  first_name                          TEXT                ,                     -- First Name of the customer - used to make the full name
  last_name                           TEXT                                      -- Last Name of the customer - used to make the full name
);
COMMENT ON TABLE customers IS 'Table: Customers';
COMMENT ON COLUMN customers.email_address IS 'The customer''s email address';
COMMENT ON COLUMN customers.first_name IS 'First Name of the customer - used to make the full name';
COMMENT ON COLUMN customers.last_name IS 'Last Name of the customer - used to make the full name';

-- ============================================================================
-- FK INDEXES - Performance only, always applied
-- ============================================================================

-- (no FK fields detected in rulebook)
