-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- Total Views: 1
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Drop pass: every rulebook-owned view, reverse iteration order, CASCADE.
-- The rulebook is HEAD — the surviving view set must mirror it exactly.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_customers CASCADE;

-- ----------------------------------------------------------------------------
-- vw_customers: Table: Customers
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_customers CASCADE;
CREATE VIEW vw_customers WITH (security_invoker = ON) AS
SELECT
  t.customer_id,
  calc_customers_name(t.customer_id) AS name,                                   -- Identifier for the customer.
  t.email_address,                                                              -- The customer's email address
  t.first_name,                                                                 -- First Name of the customer - used to make the full name
  t.last_name,                                                                  -- Last Name of the customer - used to make the full name
  calc_customers_full_name(t.customer_id) AS full_name                          -- Full name is computed from the first and last name of the customer
FROM customers t;

