-- ============================================================================
-- INSERT DATA - Load data from rulebook
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- PK strategy: string (FK values are rewritten to match each PK)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Customers: Table: Customers
-- ----------------------------------------------------------------------------
INSERT INTO customers (customer_id, email_address, first_name, last_name)
VALUES ('bob-gmail-com', 'bob@gmail.com', 'Bobby', 'Smith') ON CONFLICT (customer_id) DO UPDATE SET email_address = EXCLUDED.email_address, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name;

INSERT INTO customers (customer_id, email_address, first_name, last_name)
VALUES ('jimmy-gmail-com', 'jimmy@gmail.com', 'Jimmy', 'Doe') ON CONFLICT (customer_id) DO UPDATE SET email_address = EXCLUDED.email_address, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name;

INSERT INTO customers (customer_id, email_address, first_name, last_name)
VALUES ('mary-gmail-com', 'mary@gmail.com', 'Mary', 'Jones') ON CONFLICT (customer_id) DO UPDATE SET email_address = EXCLUDED.email_address, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name;

