@startuml
skinparam classAttributeIconSize 0

note top of Customers
  Table: Customers
end note

class Customers {
  +CustomerId: String
  +EmailAddress: String -- The customer's email address
  +FirstName: String -- First Name of the customer - used to make the full name
  +LastName: String -- Last Name of the customer - used to make the full name
  --
  /Name: String  {derived} -- Identifier for the customer.
  /FullName: String  {derived} -- Full name is computed from the first and last name of the customer
}

@enduml