@startuml

object "bob-gmail.com" as Customers_0 {
  CustomerId = "bob-gmail-com"
  EmailAddress = "bob@gmail.com"
  FirstName = "Bobby"
  LastName = "Smith"
}

object "jimmy-gmail.com" as Customers_1 {
  CustomerId = "jimmy-gmail-com"
  EmailAddress = "jimmy@gmail.com"
  FirstName = "Jimmy"
  LastName = "Doe"
}

object "mary-gmail.com" as Customers_2 {
  CustomerId = "mary-gmail-com"
  EmailAddress = "mary@gmail.com"
  FirstName = "Mary"
  LastName = "Jones"
}

@enduml