#!/usr/bin/env bash
# ============================================================================
# Procedural Knowledge Ontology (PKO) — one-command run.
#
# This domain has TWO kinds of deliverable, and start.sh boots both:
#
#   * the APP  — the Procedure Register web console, backed by Postgres views
#                generated from the rulebook by rulebook-to-postgres
#   * the DOCS — markdown projections of the same rulebook (SOPs, governance,
#                comms policies, validation report)
#
# Per repo doctrine start.sh IS the restart story: it kills whatever is on its
# ports first, then boots clean. You never need to find a PID.
#
#   ./start.sh            app: API (:8099) + Vite dev server (:5174)
#                              open http://localhost:5174
#   ./start.sh prod       app: build the UI, serve API + static UI on :8099
#   ./start.sh docs       regenerate every markdown projection (no server)
#   ./start.sh validate   validate the rulebook against the ERB-PKO profile
#   ./start.sh test       conformance tests only
#   ./start.sh db         (re)create + load erb_procedural_knowledge_ontology
#   ./start.sh all        validate + docs + tests + db, then boot the app
#
# `effortless build` is the canonical step that regenerates postgres-bootstrap/
# and rulespeak/ from the rulebook. It is NOT run here because it needs the CLI
# and the transpiler bus; see README.md.
# ============================================================================
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

PROJECT_NAME='procedural-knowledge-ontology'
EXPERIENCE_DESCRIPTION='PKO Procedure Register with view-backed API and generated projections'
START_COMMAND='./start.sh'
PYTHON="${PYTHON:-python3}"
RULEBOOK="effortless-rulebook/procedural-knowledge-ontology-rulebook.json"
MODE="${1:-app}"

API_PORT="${PORT:-8099}"
WEB_PORT="${WEB_PORT:-5174}"
PRIMARY_URL="http://localhost:${WEB_PORT}"
HEALTH_URL="http://localhost:${API_PORT}/api/health"

# The DB name is DERIVED from the domain (erb_<domain-with-underscores>), which
# is the deterministically-correct target rather than a guess. DATABASE_URL only
# overrides it.
ERB_DOMAIN="${ERB_DOMAIN:-procedural-knowledge-ontology}"
export ERB_DOMAIN
DATABASE_URL="${DATABASE_URL:-postgresql://postgres@localhost:5432/erb_${ERB_DOMAIN//-/_}}"
export DATABASE_URL

banner() { printf '\n\033[1;34m==> %s\033[0m\n' "$1"; }
die()    { printf '\n\033[1;31mERROR: %s\033[0m\n' "$1" >&2; exit 1; }

[ -f "$RULEBOOK" ] || die "missing $HERE/$RULEBOOK
The rulebook is the source of truth for this domain and is committed;
a clean clone has it. To restore:  git checkout -- $RULEBOOK"

command -v "$PYTHON" >/dev/null 2>&1 || die "'$PYTHON' not found. This domain needs Python 3."
for command in npm psql lsof curl; do
  command -v "$command" >/dev/null 2>&1 || die "'$command' is required"
done
for file in app/backend/package.json app/backend/server.js \
  app/frontend/package.json app/frontend/index.html; do
  [ -f "$file" ] || die "missing required file: $HERE/$file"
done

# --- the document pipeline (unchanged) -------------------------------------
run_validate() {
  banner "Validating $RULEBOOK against the ERB-PKO profile"
  $PYTHON tools/pko_rulebook_tool.py validate -i "$RULEBOOK"
}

run_generate() {
  banner "Regenerating projections into generated/"
  $PYTHON tools/pko_rulebook_tool.py natural-language-docs -i "$RULEBOOK" -o generated/natural-language-docs.md
  $PYTHON tools/pko_rulebook_tool.py financial-sops        -i "$RULEBOOK" -o generated/financial-sops.md
  $PYTHON tools/pko_rulebook_tool.py text-email-policies   -i "$RULEBOOK" -o generated/text-email-policies.md
  $PYTHON tools/pko_rulebook_tool.py governance            -i "$RULEBOOK" -o generated/governance.md
  $PYTHON tools/pko_rulebook_tool.py validation-report     -i "$RULEBOOK" -o generated/validation-report.md

  banner "BPM process-export adapter: foreign format -> canonical PKO -> existing projector"
  $PYTHON tools/bpm_process_export_to_pko.py -i examples/bpm-vendor-payment.json -o generated/bpm-imported-pko-rulebook.json
  $PYTHON tools/pko_rulebook_tool.py financial-sops    -i generated/bpm-imported-pko-rulebook.json -o generated/bpm-financial-sops.md
  $PYTHON tools/pko_rulebook_tool.py validation-report -i generated/bpm-imported-pko-rulebook.json -o generated/bpm-validation-report.md
}

run_test() {
  banner "Conformance tests"
  $PYTHON -m unittest discover -s tests -v
}

# --- the database -----------------------------------------------------------
run_db() {
  banner "Loading $DATABASE_URL"
  [ -f postgres-bootstrap/init-db.sh ] || die "postgres-bootstrap/init-db.sh is missing.
It is generated by rulebook-to-postgres. Regenerate it with:
    effortless build"

  # createdb is idempotent for our purposes: if the DB is already there we just
  # proceed to load it. Any OTHER createdb failure is real and must surface.
  if ! psql "$DATABASE_URL" -c 'SELECT 1' >/dev/null 2>&1; then
    banner "Creating database erb_${ERB_DOMAIN//-/_}"
    createdb "erb_${ERB_DOMAIN//-/_}" 2>/dev/null \
      || psql -U postgres -d postgres -c "CREATE DATABASE erb_${ERB_DOMAIN//-/_}" \
      || die "could not create erb_${ERB_DOMAIN//-/_} — is Postgres running? (pg_isready)"
  fi

  chmod +x postgres-bootstrap/init-db.sh
  ./postgres-bootstrap/init-db.sh

  # Access control is only real if it refuses something. init-db.sh emits the
  # policies and role schemas; these witnesses prove they actually cut, by
  # querying AS each principal for a row that must not come back -- alongside
  # positive controls, because a suite that only tests denials cannot tell a
  # working policy from one that denies everything.
  #
  # Non-fatal on purpose: a failing witness must be loud but must not stop the
  # app from starting, or a security regression becomes indistinguishable from
  # a broken boot.
  if [ -f tools/run_denial_witnesses.py ]; then
    echo "[start] access denial witnesses"
    if ! python3 tools/run_denial_witnesses.py; then
      echo "[start] WARNING: access witnesses FAILED — a policy is not"
      echo "[start] enforcing what the rulebook says. See the table above."
    fi
  fi
}

# --- the app ----------------------------------------------------------------
# Kill anything already on the ports (clean restart). This is start.sh's
# primary job — the user never has to hunt a PID.
free_ports() {
  for p in "$@"; do
    pids="$(lsof -nP -tiTCP:"$p" -sTCP:LISTEN 2>/dev/null || true)"
    if [ -n "$pids" ]; then
      echo "  freeing declared port $p (PIDs: $(echo "$pids" | tr '\n' ' '))"
      # shellcheck disable=SC2086
      kill $pids
      sleep 1
      pids="$(lsof -nP -tiTCP:"$p" -sTCP:LISTEN 2>/dev/null || true)"
      if [ -n "$pids" ]; then
        # shellcheck disable=SC2086
        kill -KILL $pids
        sleep 1
      fi
    fi
    [ -z "$(lsof -nP -tiTCP:"$p" -sTCP:LISTEN 2>/dev/null || true)" ] \
      || die "port $p is still occupied"
  done
}

preflight_db() {
  psql "$DATABASE_URL" -c 'SELECT 1' >/dev/null 2>&1 \
    || die "cannot reach $DATABASE_URL
The app reads vw_<entity> views from this database. Create and load it:
    ./start.sh db"
  local n
  n=$(psql "$DATABASE_URL" -tAc "SELECT count(*) FROM information_schema.views WHERE table_schema='public' AND table_name LIKE 'vw\\_%'")
  [ "$n" -gt 0 ] || die "$DATABASE_URL has no vw_* views — it was never loaded.
    ./start.sh db"
  echo "  $n views available in $DATABASE_URL"
}

ensure_deps() {
  [ -d app/backend/node_modules ]  || (banner "Installing API deps";  cd app/backend  && npm install --silent)
  [ -d app/frontend/node_modules ] || (banner "Installing UI deps";   cd app/frontend && npm install --silent)
}

run_app() {
  banner "Preflight"
  preflight_db
  ensure_deps

  banner "Freeing ports"
  free_ports "$API_PORT" "$WEB_PORT"

  banner "Starting API on :$API_PORT"
  (cd app/backend && PORT="$API_PORT" node server.js) &
  API_PID=$!
  trap 'kill $API_PID 2>/dev/null || true' EXIT

  # Wait for the API to actually answer before starting the UI, so a failed
  # boot surfaces here rather than as a confusing proxy error in the browser.
  for _ in $(seq 1 40); do
    curl -sf "http://localhost:$API_PORT/api/health" >/dev/null 2>&1 && break
    sleep 0.25
  done
  curl -sf "http://localhost:$API_PORT/api/health" >/dev/null 2>&1 \
    || die "the API did not come up on :$API_PORT"
  echo "  API healthy"

  banner "Starting UI on :$WEB_PORT"
  echo "[start] project: $PROJECT_NAME"
  echo "[start] starting: $EXPERIENCE_DESCRIPTION"
  echo "[start] primary:  $PRIMARY_URL"
  echo "[start] API:      http://localhost:$API_PORT"
  echo "[start] health:   $HEALTH_URL"
  (cd app/frontend && npx vite --port "$WEB_PORT" --strictPort)
}

run_prod() {
  banner "Preflight"
  preflight_db
  ensure_deps

  banner "Building the UI"
  (cd app/frontend && npm run build)

  banner "Freeing port $API_PORT"
  free_ports "$API_PORT"

  banner "Serving API + UI on :$API_PORT"
  PRIMARY_URL="http://localhost:${API_PORT}"
  HEALTH_URL="${PRIMARY_URL}/api/health"
  echo "[start] project: $PROJECT_NAME"
  echo "[start] starting: $EXPERIENCE_DESCRIPTION"
  echo "[start] primary:  $PRIMARY_URL"
  echo "[start] health:   $HEALTH_URL"
  (cd app/backend && PORT="$API_PORT" node server.js)
}

case "$MODE" in
  validate) run_validate ;;
  test)     run_test ;;
  db)       run_db ;;
  docs)
    run_validate
    run_generate
    banner "Generated artifacts (projections — edit the rulebook, not these)"
    ls -1 generated/
    printf '\n\033[1;32mOK\033[0m — rulebook valid, projections regenerated.\n'
    ;;
  app)  run_app ;;
  prod) run_prod ;;
  all)
    run_validate
    run_generate
    run_test
    run_db
    run_app
    ;;
  open)
    run_validate
    run_generate
    run_test
    DOC="generated/natural-language-docs.md"
    command -v open >/dev/null 2>&1 && open "$DOC" || echo "Open $HERE/$DOC"
    ;;
  *)
    echo "usage: ./start.sh [app|prod|docs|db|validate|test|all|open]" >&2
    exit 2
    ;;
esac
