-- ============================================================================
-- CREATE FUNCTIONS - Calculation functions for lookup/calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- ============================================================================


-- Disable body validation so LANGUAGE sql functions can forward-reference
-- each other within this file. (pg_dump does the same thing for the same
-- reason.) Without this, SQL functions parse-check at CREATE time and fail
-- on the first forward call site; plpgsql didn't, which is how this file
-- ever worked. Dependency order is still enforced at EXECUTION time.
SET check_function_bodies = off;

-- ============================================================================
-- LOOKUP FUNCTIONS
-- These functions perform lookups via foreign key relationships
-- ============================================================================

-- get_workflow_status_concepts_pref_label
-- Helper function: Get PrefLabel from WorkflowStatusConcepts by ConceptId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_workflow_status_concepts_pref_label(p_concept_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT pref_label FROM workflow_status_concepts WHERE concept_id = p_concept_id);
$$ LANGUAGE sql STABLE;

-- get_workflow_status_concepts_alt_label
-- Helper function: Get AltLabel from WorkflowStatusConcepts by ConceptId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_workflow_status_concepts_alt_label(p_concept_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT alt_label FROM workflow_status_concepts WHERE concept_id = p_concept_id);
$$ LANGUAGE sql STABLE;

-- get_workflow_status_concepts_definition
-- Helper function: Get Definition from WorkflowStatusConcepts by ConceptId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_workflow_status_concepts_definition(p_concept_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT definition FROM workflow_status_concepts WHERE concept_id = p_concept_id);
$$ LANGUAGE sql STABLE;

-- get_workflow_status_concepts_scope_note
-- Helper function: Get ScopeNote from WorkflowStatusConcepts by ConceptId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_workflow_status_concepts_scope_note(p_concept_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT scope_note FROM workflow_status_concepts WHERE concept_id = p_concept_id);
$$ LANGUAGE sql STABLE;

-- get_workflow_steps_display_name
-- Helper function: Get DisplayName from WorkflowSteps by WorkflowStepId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_workflow_steps_display_name(p_workflow_step_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT display_name FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id);
$$ LANGUAGE sql STABLE;

-- get_workflow_steps_sequence_position_override
-- Helper function: Get SequencePositionOverride from WorkflowSteps by WorkflowStepId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_workflow_steps_sequence_position_override(p_workflow_step_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT sequence_position_override FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id);
$$ LANGUAGE sql STABLE;

-- get_workflow_steps_requires_human_approval
-- Helper function: Get RequiresHumanApproval from WorkflowSteps by WorkflowStepId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_workflow_steps_requires_human_approval(p_workflow_step_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT requires_human_approval FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id);
$$ LANGUAGE sql STABLE;

-- get_workflow_steps_step_duration_minutes
-- Helper function: Get StepDurationMinutes from WorkflowSteps by WorkflowStepId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_workflow_steps_step_duration_minutes(p_workflow_step_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT step_duration_minutes FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id);
$$ LANGUAGE sql STABLE;

-- calc_workflows_relative_path
-- Field: Workflows.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_workflows_relative_path(p_workflow_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT('workflows/', (SELECT NULLIF(workflow_id, '') FROM workflows WHERE workflow_id = p_workflow_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_workflows_iri
-- Field: Workflows.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_workflows_iri(p_workflow_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_workflows_relative_path(p_workflow_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_workflows_name
-- Field: Workflows.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_workflows_name(p_workflow_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(display_name, '') FROM workflows WHERE workflow_id = p_workflow_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_workflows_count_of_non_proposed_steps
-- Field: Workflows.CountOfNonProposedSteps
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflows_count_of_non_proposed_steps(p_workflow_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM workflow_steps WHERE workflow = (SELECT NULLIF(workflow_id, '') FROM workflows WHERE workflow_id = p_workflow_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflows_has_more_than1_step
-- Field: Workflows.HasMoreThan1Step
-- Type: calculated | DataType: boolean | Returns: BOOLEAN

CREATE OR REPLACE FUNCTION calc_workflows_has_more_than1_step(p_workflow_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((calc_workflows_count_of_non_proposed_steps(p_workflow_id))::NUMERIC > 1)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_workflows_count_ai_steps
-- Field: Workflows.CountAISteps
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflows_count_ai_steps(p_workflow_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM workflow_steps WHERE workflow = (SELECT NULLIF(workflow_id, '') FROM workflows WHERE workflow_id = p_workflow_id) AND calc_workflow_steps_is_executed_by_ai(workflow_step_id) = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflows_count_human_steps
-- Field: Workflows.CountHumanSteps
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflows_count_human_steps(p_workflow_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM workflow_steps WHERE workflow = (SELECT NULLIF(workflow_id, '') FROM workflows WHERE workflow_id = p_workflow_id) AND calc_workflow_steps_is_executed_by_human(workflow_step_id) = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflows_count_human_required_steps
-- Field: Workflows.CountHumanRequiredSteps
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflows_count_human_required_steps(p_workflow_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM workflow_steps WHERE workflow = (SELECT NULLIF(workflow_id, '') FROM workflows WHERE workflow_id = p_workflow_id) AND requires_human_approval = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflows_count_approval_consistency_violations
-- Field: Workflows.CountApprovalConsistencyViolations
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflows_count_approval_consistency_violations(p_workflow_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM workflow_steps WHERE workflow = (SELECT NULLIF(workflow_id, '') FROM workflows WHERE workflow_id = p_workflow_id) AND calc_workflow_steps_approval_consistency_violation(workflow_step_id) = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflows_has_consistency_violation
-- Field: Workflows.HasConsistencyViolation
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflows_has_consistency_violation(p_workflow_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((calc_workflows_count_approval_consistency_violations(p_workflow_id))::NUMERIC > 0)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_workflows_has_ai_agent_step
-- Field: Workflows.HasAIAgentStep
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflows_has_ai_agent_step(p_workflow_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((calc_workflows_count_ai_steps(p_workflow_id))::NUMERIC > 0)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_workflows_months_since_modified
-- Field: Workflows.MonthsSinceModified
-- Type: calculated | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflows_months_since_modified(p_workflow_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((EXTRACT(YEAR FROM AGE(CURRENT_TIMESTAMP::timestamp, (SELECT modified::timestamptz FROM workflows WHERE workflow_id = p_workflow_id)::timestamp)) * 12 + EXTRACT(MONTH FROM AGE(CURRENT_TIMESTAMP::timestamp, (SELECT modified::timestamptz FROM workflows WHERE workflow_id = p_workflow_id)::timestamp))))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflows_is_stale
-- Field: Workflows.IsStale
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflows_is_stale(p_workflow_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (calc_workflows_months_since_modified(p_workflow_id) > (SELECT staleness_threshold_months FROM workflows WHERE workflow_id = p_workflow_id))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_workflows_is_stale_and_has_ai_agent
-- Field: Workflows.IsStaleAndHasAIAgent
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflows_is_stale_and_has_ai_agent(p_workflow_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((calc_workflows_is_stale(p_workflow_id) AND calc_workflows_has_ai_agent_step(p_workflow_id)))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_workflows_count_derivation_links
-- Field: Workflows.CountDerivationLinks
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflows_count_derivation_links(p_workflow_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM workflow_artifacts WHERE calc_workflow_artifacts_produced_by_workflow(artifact_id) = (SELECT NULLIF(workflow_id, '') FROM workflows WHERE workflow_id = p_workflow_id) AND calc_workflow_artifacts_has_derivation_parent(artifact_id) = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflows_count_legal_owned_steps
-- Field: Workflows.CountLegalOwnedSteps
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflows_count_legal_owned_steps(p_workflow_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM workflow_steps WHERE workflow = (SELECT NULLIF(workflow_id, '') FROM workflows WHERE workflow_id = p_workflow_id) AND calc_workflow_steps_is_legal_owned(workflow_step_id) = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflows_count_engineering_owned_steps
-- Field: Workflows.CountEngineeringOwnedSteps
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflows_count_engineering_owned_steps(p_workflow_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM workflow_steps WHERE workflow = (SELECT NULLIF(workflow_id, '') FROM workflows WHERE workflow_id = p_workflow_id) AND calc_workflow_steps_is_engineering_owned(workflow_step_id) = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflows_involves_engineering_and_legal
-- Field: Workflows.InvolvesEngineeringAndLegal
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflows_involves_engineering_and_legal(p_workflow_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (((calc_workflows_count_engineering_owned_steps(p_workflow_id))::NUMERIC > 0 AND (calc_workflows_count_legal_owned_steps(p_workflow_id))::NUMERIC > 0));
$$ LANGUAGE sql STABLE;

-- calc_workflows_count_inferred_precedence_pairs
-- Field: Workflows.CountInferredPrecedencePairs
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflows_count_inferred_precedence_pairs(p_workflow_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM vw_step_precedence_closure WHERE is_inferred = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflows_count_asserted_precedence_pairs
-- Field: Workflows.CountAssertedPrecedencePairs
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflows_count_asserted_precedence_pairs(p_workflow_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM vw_step_precedence_closure WHERE is_inferred = FALSE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflows_count_of_precedence_closure_pairs
-- Field: Workflows.CountOfPrecedenceClosurePairs
-- Type: calculated | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflows_count_of_precedence_closure_pairs(p_workflow_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_workflows_count_asserted_precedence_pairs(p_workflow_id)) AS v) __safe_numeric), 0) + COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_workflows_count_inferred_precedence_pairs(p_workflow_id)) AS v) __safe_numeric), 0)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflows_count_roles_with_bad_filler_cardinality
-- Field: Workflows.CountRolesWithBadFillerCardinality
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflows_count_roles_with_bad_filler_cardinality(p_workflow_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM roles WHERE calc_roles_has_exactly_one_filler(role_id) = FALSE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflows_count_agent_type_changes
-- Field: Workflows.CountAgentTypeChanges
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflows_count_agent_type_changes(p_workflow_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM role_assignments WHERE calc_role_assignments_is_agent_type_change(role_assignment_id) = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflows_count_compliance_audit_changes
-- Field: Workflows.CountComplianceAuditChanges
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflows_count_compliance_audit_changes(p_workflow_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM role_assignments WHERE calc_role_assignments_requires_compliance_audit(role_assignment_id) = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflows_count_approval_gate_steps
-- Field: Workflows.CountApprovalGateSteps
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflows_count_approval_gate_steps(p_workflow_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM workflow_steps WHERE workflow = (SELECT NULLIF(workflow_id, '') FROM workflows WHERE workflow_id = p_workflow_id) AND calc_workflow_steps_is_approval_gate(workflow_step_id) = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflows_count_gates_without_human_approver
-- Field: Workflows.CountGatesWithoutHumanApprover
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflows_count_gates_without_human_approver(p_workflow_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM approval_gates WHERE calc_approval_gates_has_human_approver(approval_gate_id) = FALSE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflows_count_workflow_artifacts
-- Field: Workflows.CountWorkflowArtifacts
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflows_count_workflow_artifacts(p_workflow_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM workflow_artifacts WHERE calc_workflow_artifacts_produced_by_workflow(artifact_id) = (SELECT NULLIF(workflow_id, '') FROM workflows WHERE workflow_id = p_workflow_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflows_count_roles_with_escalation_violation
-- Field: Workflows.CountRolesWithEscalationViolation
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflows_count_roles_with_escalation_violation(p_workflow_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM roles WHERE calc_roles_escalation_violation(role_id) = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflows_count_unconsumed_datasets
-- Field: Workflows.CountUnconsumedDatasets
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflows_count_unconsumed_datasets(p_workflow_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM datasets WHERE calc_datasets_is_consumed(dataset_id) = FALSE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflows_cq1_satisfied
-- Field: Workflows.Cq1Satisfied
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflows_cq1_satisfied(p_workflow_id TEXT)
RETURNS BOOLEAN AS $$
  WITH __erb_dedup_v1 AS (SELECT calc_workflows_count_of_non_proposed_steps(p_workflow_id) AS val) SELECT (calc_workflows_count_of_precedence_closure_pairs(p_workflow_id) = (COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT val FROM __erb_dedup_v1)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT val FROM __erb_dedup_v1)) AS v) __safe_numeric), 0) - COALESCE(1, 0))) AS v) __safe_numeric), 0) / NULLIF(COALESCE(2, 0), 0))) AS v) __safe_numeric), 0)))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_workflows_cq2_satisfied
-- Field: Workflows.Cq2Satisfied
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflows_cq2_satisfied(p_workflow_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (((calc_workflows_count_approval_gate_steps(p_workflow_id))::NUMERIC > 0 AND (calc_workflows_count_gates_without_human_approver(p_workflow_id))::NUMERIC = 0));
$$ LANGUAGE sql STABLE;

-- calc_workflows_cq3_satisfied
-- Field: Workflows.Cq3Satisfied
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflows_cq3_satisfied(p_workflow_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (NOT (calc_workflows_has_consistency_violation(p_workflow_id)))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_workflows_cq4_satisfied
-- Field: Workflows.Cq4Satisfied
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflows_cq4_satisfied(p_workflow_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (calc_workflows_count_derivation_links(p_workflow_id) = (COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_workflows_count_workflow_artifacts(p_workflow_id)) AS v) __safe_numeric), 0) - COALESCE(1, 0)))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_workflows_cq5_satisfied
-- Field: Workflows.Cq5Satisfied
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflows_cq5_satisfied(p_workflow_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (NOT (calc_workflows_is_stale(p_workflow_id)))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_workflows_cq6_satisfied
-- Field: Workflows.Cq6Satisfied
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflows_cq6_satisfied(p_workflow_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((calc_workflows_count_roles_with_escalation_violation(p_workflow_id))::NUMERIC = 0)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_workflows_cq7_satisfied
-- Field: Workflows.Cq7Satisfied
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflows_cq7_satisfied(p_workflow_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (calc_workflows_involves_engineering_and_legal(p_workflow_id))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_workflows_cq8_satisfied
-- Field: Workflows.Cq8Satisfied
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflows_cq8_satisfied(p_workflow_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((calc_workflows_count_unconsumed_datasets(p_workflow_id))::NUMERIC = 0)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_workflow_steps_parent_path
-- Field: WorkflowSteps.ParentPath
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: RelativePath from related Workflows


CREATE OR REPLACE FUNCTION calc_workflow_steps_parent_path(p_workflow_step_id TEXT)
RETURNS TEXT AS $$
  SELECT calc_workflows_relative_path((SELECT workflow FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id));
$$ LANGUAGE sql STABLE;

-- calc_workflow_steps_executing_human_agent
-- Field: WorkflowSteps.ExecutingHumanAgent
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: FilledByHumanAgent from related Roles


CREATE OR REPLACE FUNCTION calc_workflow_steps_executing_human_agent(p_workflow_step_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT filled_by_human_agent::text FROM roles WHERE role_id = (SELECT assigned_role FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id));
$$ LANGUAGE sql STABLE;

-- calc_workflow_steps_executing_ai_agent
-- Field: WorkflowSteps.ExecutingAIAgent
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: FilledByAIAgent from related Roles


CREATE OR REPLACE FUNCTION calc_workflow_steps_executing_ai_agent(p_workflow_step_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT filled_by_ai_agent::text FROM roles WHERE role_id = (SELECT assigned_role FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id));
$$ LANGUAGE sql STABLE;

-- calc_workflow_steps_executing_automated_pipeline
-- Field: WorkflowSteps.ExecutingAutomatedPipeline
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: FilledByAutomatedPipeline from related Roles


CREATE OR REPLACE FUNCTION calc_workflow_steps_executing_automated_pipeline(p_workflow_step_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT filled_by_automated_pipeline::text FROM roles WHERE role_id = (SELECT assigned_role FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id));
$$ LANGUAGE sql STABLE;

-- calc_workflow_steps_owning_department
-- Field: WorkflowSteps.OwningDepartment
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: OwnedBy from related Roles


CREATE OR REPLACE FUNCTION calc_workflow_steps_owning_department(p_workflow_step_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT owned_by::text FROM roles WHERE role_id = (SELECT assigned_role FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id));
$$ LANGUAGE sql STABLE;

-- get_workflows_display_name
-- Helper function: Get DisplayName from Workflows by WorkflowId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_workflows_display_name(p_workflow_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT display_name FROM workflows WHERE workflow_id = p_workflow_id);
$$ LANGUAGE sql STABLE;

-- get_workflows_title
-- Helper function: Get Title from Workflows by WorkflowId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_workflows_title(p_workflow_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT title FROM workflows WHERE workflow_id = p_workflow_id);
$$ LANGUAGE sql STABLE;

-- get_workflows_description
-- Helper function: Get Description from Workflows by WorkflowId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_workflows_description(p_workflow_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM workflows WHERE workflow_id = p_workflow_id);
$$ LANGUAGE sql STABLE;

-- get_workflows_identifier
-- Helper function: Get Identifier from Workflows by WorkflowId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_workflows_identifier(p_workflow_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT identifier FROM workflows WHERE workflow_id = p_workflow_id);
$$ LANGUAGE sql STABLE;

-- get_workflows_modified
-- Helper function: Get Modified from Workflows by WorkflowId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_workflows_modified(p_workflow_id TEXT)
RETURNS TIMESTAMPTZ AS $$
  SELECT (SELECT modified FROM workflows WHERE workflow_id = p_workflow_id);
$$ LANGUAGE sql STABLE;

-- get_workflows_created
-- Helper function: Get Created from Workflows by WorkflowId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_workflows_created(p_workflow_id TEXT)
RETURNS TIMESTAMPTZ AS $$
  SELECT (SELECT created FROM workflows WHERE workflow_id = p_workflow_id);
$$ LANGUAGE sql STABLE;

-- get_workflows_staleness_threshold_months
-- Helper function: Get StalenessThresholdMonths from Workflows by WorkflowId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_workflows_staleness_threshold_months(p_workflow_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT staleness_threshold_months FROM workflows WHERE workflow_id = p_workflow_id);
$$ LANGUAGE sql STABLE;

-- get_roles_display_name
-- Helper function: Get DisplayName from Roles by RoleId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_roles_display_name(p_role_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT display_name FROM roles WHERE role_id = p_role_id);
$$ LANGUAGE sql STABLE;

-- get_roles_label
-- Helper function: Get Label from Roles by RoleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_roles_label(p_role_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT label FROM roles WHERE role_id = p_role_id);
$$ LANGUAGE sql STABLE;

-- get_roles_comment
-- Helper function: Get Comment from Roles by RoleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_roles_comment(p_role_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT comment FROM roles WHERE role_id = p_role_id);
$$ LANGUAGE sql STABLE;

-- get_datasets_title
-- Helper function: Get Title from Datasets by DatasetId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_datasets_title(p_dataset_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT title FROM datasets WHERE dataset_id = p_dataset_id);
$$ LANGUAGE sql STABLE;

-- get_datasets_identifier
-- Helper function: Get Identifier from Datasets by DatasetId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_datasets_identifier(p_dataset_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT identifier FROM datasets WHERE dataset_id = p_dataset_id);
$$ LANGUAGE sql STABLE;

-- get_datasets_modified
-- Helper function: Get Modified from Datasets by DatasetId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_datasets_modified(p_dataset_id TEXT)
RETURNS TIMESTAMPTZ AS $$
  SELECT (SELECT modified FROM datasets WHERE dataset_id = p_dataset_id);
$$ LANGUAGE sql STABLE;

-- get_datasets_distribution_url
-- Helper function: Get DistributionUrl from Datasets by DatasetId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_datasets_distribution_url(p_dataset_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT distribution_url FROM datasets WHERE dataset_id = p_dataset_id);
$$ LANGUAGE sql STABLE;

-- get_workflow_artifacts_title
-- Helper function: Get Title from WorkflowArtifacts by ArtifactId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_workflow_artifacts_title(p_artifact_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT title FROM workflow_artifacts WHERE artifact_id = p_artifact_id);
$$ LANGUAGE sql STABLE;

-- get_workflow_artifacts_identifier
-- Helper function: Get Identifier from WorkflowArtifacts by ArtifactId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_workflow_artifacts_identifier(p_artifact_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT identifier FROM workflow_artifacts WHERE artifact_id = p_artifact_id);
$$ LANGUAGE sql STABLE;

-- get_workflow_artifacts_created
-- Helper function: Get Created from WorkflowArtifacts by ArtifactId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_workflow_artifacts_created(p_artifact_id TEXT)
RETURNS TIMESTAMPTZ AS $$
  SELECT (SELECT created FROM workflow_artifacts WHERE artifact_id = p_artifact_id);
$$ LANGUAGE sql STABLE;

-- get_approval_gates_display_name
-- Helper function: Get DisplayName from ApprovalGates by ApprovalGateId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_approval_gates_display_name(p_approval_gate_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT display_name FROM approval_gates WHERE approval_gate_id = p_approval_gate_id);
$$ LANGUAGE sql STABLE;

-- get_approval_gates_escalation_threshold_hours
-- Helper function: Get EscalationThresholdHours from ApprovalGates by ApprovalGateId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_approval_gates_escalation_threshold_hours(p_approval_gate_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT escalation_threshold_hours FROM approval_gates WHERE approval_gate_id = p_approval_gate_id);
$$ LANGUAGE sql STABLE;

-- calc_workflow_steps_relative_path
-- Field: WorkflowSteps.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_workflow_steps_relative_path(p_workflow_step_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT(calc_workflow_steps_parent_path(p_workflow_step_id), '/steps/', (SELECT NULLIF(workflow_step_id, '') FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_workflow_steps_iri
-- Field: WorkflowSteps.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_workflow_steps_iri(p_workflow_step_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_workflow_steps_relative_path(p_workflow_step_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_workflow_steps_name
-- Field: WorkflowSteps.Name
-- Type: calculated | DataType: string | Returns: TEXT

CREATE OR REPLACE FUNCTION calc_workflow_steps_name(p_workflow_step_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(display_name, '') FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_workflow_steps_preceding_step_count
-- Field: WorkflowSteps.PrecedingStepCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflow_steps_preceding_step_count(p_workflow_step_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM vw_step_precedence_closure WHERE to_id = (SELECT NULLIF(workflow_step_id, '') FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflow_steps_inferred_sequence_position
-- Field: WorkflowSteps.InferredSequencePosition
-- Type: calculated | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflow_steps_inferred_sequence_position(p_workflow_step_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_workflow_steps_preceding_step_count(p_workflow_step_id)) AS v) __safe_numeric), 0) + COALESCE(1, 0)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflow_steps_sequence_position
-- Field: WorkflowSteps.SequencePosition
-- Type: calculated | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_workflow_steps_sequence_position(p_workflow_step_id TEXT)
RETURNS INTEGER AS $$
  SELECT (CASE WHEN (SELECT sequence_position_override FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id) IS NOT NULL THEN ((SELECT sequence_position_override FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id))::text ELSE (calc_workflow_steps_inferred_sequence_position(p_workflow_step_id))::text END)::integer;
$$ LANGUAGE sql STABLE;

-- calc_workflow_steps_executing_agent_type
-- Field: WorkflowSteps.ExecutingAgentType
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_workflow_steps_executing_agent_type(p_workflow_step_id TEXT)
RETURNS TEXT AS $$
  WITH __erb_dedup_v1 AS (SELECT calc_workflow_steps_executing_human_agent(p_workflow_step_id) AS val), __erb_dedup_v2 AS (SELECT calc_workflow_steps_executing_ai_agent(p_workflow_step_id) AS val), __erb_dedup_v3 AS (SELECT calc_workflow_steps_executing_automated_pipeline(p_workflow_step_id) AS val) SELECT (CASE WHEN NOT ((((SELECT val FROM __erb_dedup_v1)) IS NULL OR ((SELECT val FROM __erb_dedup_v1))::text = '')) THEN ('HumanAgent')::text ELSE (CASE WHEN NOT ((((SELECT val FROM __erb_dedup_v2)) IS NULL OR ((SELECT val FROM __erb_dedup_v2))::text = '')) THEN ('AIAgent')::text ELSE (CASE WHEN NOT ((((SELECT val FROM __erb_dedup_v3)) IS NULL OR ((SELECT val FROM __erb_dedup_v3))::text = '')) THEN ('AutomatedPipeline')::text ELSE ('')::text END)::text END)::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_workflow_steps_is_executed_by_ai
-- Field: WorkflowSteps.IsExecutedByAI
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflow_steps_is_executed_by_ai(p_workflow_step_id TEXT)
RETURNS BOOLEAN AS $$
  WITH __erb_dedup_v1 AS (SELECT calc_workflow_steps_executing_ai_agent(p_workflow_step_id) AS val) SELECT (NOT ((((SELECT val FROM __erb_dedup_v1)) IS NULL OR ((SELECT val FROM __erb_dedup_v1))::text = '')))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_workflow_steps_is_executed_by_human
-- Field: WorkflowSteps.IsExecutedByHuman
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflow_steps_is_executed_by_human(p_workflow_step_id TEXT)
RETURNS BOOLEAN AS $$
  WITH __erb_dedup_v1 AS (SELECT calc_workflow_steps_executing_human_agent(p_workflow_step_id) AS val) SELECT (NOT ((((SELECT val FROM __erb_dedup_v1)) IS NULL OR ((SELECT val FROM __erb_dedup_v1))::text = '')))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_workflow_steps_is_approval_gate
-- Field: WorkflowSteps.IsApprovalGate
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflow_steps_is_approval_gate(p_workflow_step_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (NOT ((((SELECT NULLIF(approval_gate, '') FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id)) IS NULL OR ((SELECT NULLIF(approval_gate, '') FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id))::text = '')))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_workflow_steps_approval_consistency_violation
-- Field: WorkflowSteps.ApprovalConsistencyViolation
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflow_steps_approval_consistency_violation(p_workflow_step_id TEXT)
RETURNS BOOLEAN AS $$
  WITH __erb_dedup_v1 AS (SELECT calc_workflow_steps_executing_human_agent(p_workflow_step_id) AS val) SELECT ((COALESCE((SELECT requires_human_approval FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id), FALSE) AND (((SELECT val FROM __erb_dedup_v1)) IS NULL OR ((SELECT val FROM __erb_dedup_v1))::text = '')))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_workflow_steps_approval_is_human_filled
-- Field: WorkflowSteps.ApprovalIsHumanFilled
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflow_steps_approval_is_human_filled(p_workflow_step_id TEXT)
RETURNS BOOLEAN AS $$
  WITH __erb_dedup_v1 AS (SELECT calc_workflow_steps_executing_human_agent(p_workflow_step_id) AS val) SELECT (CASE WHEN COALESCE((SELECT requires_human_approval FROM workflow_steps WHERE workflow_step_id = p_workflow_step_id), FALSE) THEN (NOT ((((SELECT val FROM __erb_dedup_v1)) IS NULL OR ((SELECT val FROM __erb_dedup_v1))::text = '')))::text ELSE (TRUE)::text END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_workflow_steps_is_legal_owned
-- Field: WorkflowSteps.IsLegalOwned
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflow_steps_is_legal_owned(p_workflow_step_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (calc_workflow_steps_owning_department(p_workflow_step_id) = 'ntwf-legal-dept')::boolean;
$$ LANGUAGE sql STABLE;

-- calc_workflow_steps_is_engineering_owned
-- Field: WorkflowSteps.IsEngineeringOwned
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflow_steps_is_engineering_owned(p_workflow_step_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (calc_workflow_steps_owning_department(p_workflow_step_id) = 'ntwf-engineering')::boolean;
$$ LANGUAGE sql STABLE;

-- calc_approval_gates_parent_path
-- Field: ApprovalGates.ParentPath
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: RelativePath from related WorkflowSteps


CREATE OR REPLACE FUNCTION calc_approval_gates_parent_path(p_approval_gate_id TEXT)
RETURNS TEXT AS $$
  SELECT calc_workflow_steps_relative_path((SELECT workflow_step FROM approval_gates WHERE approval_gate_id = p_approval_gate_id));
$$ LANGUAGE sql STABLE;

-- calc_approval_gates_gate_role
-- Field: ApprovalGates.GateRole
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: AssignedRole from related WorkflowSteps


CREATE OR REPLACE FUNCTION calc_approval_gates_gate_role(p_approval_gate_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT assigned_role::text FROM workflow_steps WHERE workflow_step_id = (SELECT workflow_step FROM approval_gates WHERE approval_gate_id = p_approval_gate_id));
$$ LANGUAGE sql STABLE;

-- calc_approval_gates_gate_approver_human
-- Field: ApprovalGates.GateApproverHuman
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: FilledByHumanAgent from related Roles


CREATE OR REPLACE FUNCTION calc_approval_gates_gate_approver_human(p_approval_gate_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT filled_by_human_agent::text FROM roles WHERE role_id = calc_approval_gates_gate_role(p_approval_gate_id));
$$ LANGUAGE sql STABLE;

-- calc_approval_gates_relative_path
-- Field: ApprovalGates.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_approval_gates_relative_path(p_approval_gate_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT(calc_approval_gates_parent_path(p_approval_gate_id), '/approval-gates/', (SELECT NULLIF(approval_gate_id, '') FROM approval_gates WHERE approval_gate_id = p_approval_gate_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_approval_gates_iri
-- Field: ApprovalGates.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_approval_gates_iri(p_approval_gate_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_approval_gates_relative_path(p_approval_gate_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_approval_gates_name
-- Field: ApprovalGates.Name
-- Type: calculated | DataType: string | Returns: TEXT

CREATE OR REPLACE FUNCTION calc_approval_gates_name(p_approval_gate_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(display_name, '') FROM approval_gates WHERE approval_gate_id = p_approval_gate_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_approval_gates_has_human_approver
-- Field: ApprovalGates.HasHumanApprover
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_approval_gates_has_human_approver(p_approval_gate_id TEXT)
RETURNS BOOLEAN AS $$
  WITH __erb_dedup_v1 AS (SELECT calc_approval_gates_gate_approver_human(p_approval_gate_id) AS val) SELECT (NOT ((((SELECT val FROM __erb_dedup_v1)) IS NULL OR ((SELECT val FROM __erb_dedup_v1))::text = '')))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_step_precedence_parent_path
-- Field: StepPrecedence.ParentPath
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: RelativePath from related WorkflowSteps


CREATE OR REPLACE FUNCTION calc_step_precedence_parent_path(p_step_precedence_id TEXT)
RETURNS TEXT AS $$
  SELECT calc_workflow_steps_relative_path((SELECT from_step FROM step_precedence WHERE step_precedence_id = p_step_precedence_id));
$$ LANGUAGE sql STABLE;

-- calc_step_precedence_relative_path
-- Field: StepPrecedence.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_step_precedence_relative_path(p_step_precedence_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT(calc_step_precedence_parent_path(p_step_precedence_id), '/precedence/', (SELECT NULLIF(step_precedence_id, '') FROM step_precedence WHERE step_precedence_id = p_step_precedence_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_step_precedence_iri
-- Field: StepPrecedence.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_step_precedence_iri(p_step_precedence_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_step_precedence_relative_path(p_step_precedence_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_step_precedence_name
-- Field: StepPrecedence.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_step_precedence_name(p_step_precedence_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(from_step, '') FROM step_precedence WHERE step_precedence_id = p_step_precedence_id), ' -> ', (SELECT NULLIF(to_step, '') FROM step_precedence WHERE step_precedence_id = p_step_precedence_id)))::text;
$$ LANGUAGE sql STABLE;

-- get_agent_capability_concepts_pref_label
-- Helper function: Get PrefLabel from AgentCapabilityConcepts by ConceptId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_agent_capability_concepts_pref_label(p_concept_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT pref_label FROM agent_capability_concepts WHERE concept_id = p_concept_id);
$$ LANGUAGE sql STABLE;

-- get_agent_capability_concepts_alt_label
-- Helper function: Get AltLabel from AgentCapabilityConcepts by ConceptId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_agent_capability_concepts_alt_label(p_concept_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT alt_label FROM agent_capability_concepts WHERE concept_id = p_concept_id);
$$ LANGUAGE sql STABLE;

-- get_agent_capability_concepts_definition
-- Helper function: Get Definition from AgentCapabilityConcepts by ConceptId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_agent_capability_concepts_definition(p_concept_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT definition FROM agent_capability_concepts WHERE concept_id = p_concept_id);
$$ LANGUAGE sql STABLE;

-- get_agent_capability_concepts_scope_note
-- Helper function: Get ScopeNote from AgentCapabilityConcepts by ConceptId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_agent_capability_concepts_scope_note(p_concept_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT scope_note FROM agent_capability_concepts WHERE concept_id = p_concept_id);
$$ LANGUAGE sql STABLE;

-- get_human_agents_name
-- Helper function: Get Name from HumanAgents by HumanAgentId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_human_agents_name(p_human_agent_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name FROM human_agents WHERE human_agent_id = p_human_agent_id);
$$ LANGUAGE sql STABLE;

-- get_human_agents_display_name
-- Helper function: Get DisplayName from HumanAgents by HumanAgentId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_human_agents_display_name(p_human_agent_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT display_name FROM human_agents WHERE human_agent_id = p_human_agent_id);
$$ LANGUAGE sql STABLE;

-- get_human_agents_mbox
-- Helper function: Get Mbox from HumanAgents by HumanAgentId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_human_agents_mbox(p_human_agent_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT mbox FROM human_agents WHERE human_agent_id = p_human_agent_id);
$$ LANGUAGE sql STABLE;

-- get_ai_agents_name
-- Helper function: Get Name from AIAgents by AIAgentId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_ai_agents_name(p_ai_agent_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name FROM ai_agents WHERE ai_agent_id = p_ai_agent_id);
$$ LANGUAGE sql STABLE;

-- get_ai_agents_title
-- Helper function: Get Title from AIAgents by AIAgentId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_ai_agents_title(p_ai_agent_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT title FROM ai_agents WHERE ai_agent_id = p_ai_agent_id);
$$ LANGUAGE sql STABLE;

-- get_ai_agents_display_name
-- Helper function: Get DisplayName from AIAgents by AIAgentId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_ai_agents_display_name(p_ai_agent_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT display_name FROM ai_agents WHERE ai_agent_id = p_ai_agent_id);
$$ LANGUAGE sql STABLE;

-- get_ai_agents_model_version
-- Helper function: Get ModelVersion from AIAgents by AIAgentId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_ai_agents_model_version(p_ai_agent_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT model_version FROM ai_agents WHERE ai_agent_id = p_ai_agent_id);
$$ LANGUAGE sql STABLE;

-- get_ai_agents_deployed_on
-- Helper function: Get DeployedOn from AIAgents by AIAgentId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_ai_agents_deployed_on(p_ai_agent_id TEXT)
RETURNS DATE AS $$
  SELECT (SELECT deployed_on FROM ai_agents WHERE ai_agent_id = p_ai_agent_id);
$$ LANGUAGE sql STABLE;

-- get_automated_pipelines_name
-- Helper function: Get Name from AutomatedPipelines by AutomatedPipelineId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_automated_pipelines_name(p_automated_pipeline_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name FROM automated_pipelines WHERE automated_pipeline_id = p_automated_pipeline_id);
$$ LANGUAGE sql STABLE;

-- get_automated_pipelines_description
-- Helper function: Get Description from AutomatedPipelines by AutomatedPipelineId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_automated_pipelines_description(p_automated_pipeline_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM automated_pipelines WHERE automated_pipeline_id = p_automated_pipeline_id);
$$ LANGUAGE sql STABLE;

-- get_automated_pipelines_display_name
-- Helper function: Get DisplayName from AutomatedPipelines by AutomatedPipelineId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_automated_pipelines_display_name(p_automated_pipeline_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT display_name FROM automated_pipelines WHERE automated_pipeline_id = p_automated_pipeline_id);
$$ LANGUAGE sql STABLE;

-- get_departments_title
-- Helper function: Get Title from Departments by DepartmentId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_departments_title(p_department_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT title FROM departments WHERE department_id = p_department_id);
$$ LANGUAGE sql STABLE;

-- get_departments_display_name
-- Helper function: Get DisplayName from Departments by DepartmentId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_departments_display_name(p_department_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT display_name FROM departments WHERE department_id = p_department_id);
$$ LANGUAGE sql STABLE;

-- get_role_assignments_valid_from
-- Helper function: Get ValidFrom from RoleAssignments by RoleAssignmentId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_role_assignments_valid_from(p_role_assignment_id TEXT)
RETURNS DATE AS $$
  SELECT (SELECT valid_from FROM role_assignments WHERE role_assignment_id = p_role_assignment_id);
$$ LANGUAGE sql STABLE;

-- get_role_assignments_valid_to
-- Helper function: Get ValidTo from RoleAssignments by RoleAssignmentId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_role_assignments_valid_to(p_role_assignment_id TEXT)
RETURNS DATE AS $$
  SELECT (SELECT valid_to FROM role_assignments WHERE role_assignment_id = p_role_assignment_id);
$$ LANGUAGE sql STABLE;

-- get_role_assignments_reason
-- Helper function: Get Reason from RoleAssignments by RoleAssignmentId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_role_assignments_reason(p_role_assignment_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT reason FROM role_assignments WHERE role_assignment_id = p_role_assignment_id);
$$ LANGUAGE sql STABLE;

-- get_role_assignments_prior_filler_type
-- Helper function: Get PriorFillerType from RoleAssignments by RoleAssignmentId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_role_assignments_prior_filler_type(p_role_assignment_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT prior_filler_type FROM role_assignments WHERE role_assignment_id = p_role_assignment_id);
$$ LANGUAGE sql STABLE;

-- calc_roles_relative_path
-- Field: Roles.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_roles_relative_path(p_role_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT('roles/', (SELECT NULLIF(role_id, '') FROM roles WHERE role_id = p_role_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_roles_iri
-- Field: Roles.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_roles_iri(p_role_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_roles_relative_path(p_role_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_roles_name
-- Field: Roles.Name
-- Type: calculated | DataType: string | Returns: TEXT

CREATE OR REPLACE FUNCTION calc_roles_name(p_role_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(display_name, '') FROM roles WHERE role_id = p_role_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_roles_filled_by_arm_count
-- Field: Roles.FilledByArmCount
-- Type: calculated | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_roles_filled_by_arm_count(p_role_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (CASE WHEN NOT ((((SELECT NULLIF(filled_by_human_agent, '') FROM roles WHERE role_id = p_role_id)) IS NULL OR ((SELECT NULLIF(filled_by_human_agent, '') FROM roles WHERE role_id = p_role_id))::text = '')) THEN (1)::text ELSE (0)::text END) AS v) __safe_numeric), 0) + COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (CASE WHEN NOT ((((SELECT NULLIF(filled_by_ai_agent, '') FROM roles WHERE role_id = p_role_id)) IS NULL OR ((SELECT NULLIF(filled_by_ai_agent, '') FROM roles WHERE role_id = p_role_id))::text = '')) THEN (1)::text ELSE (0)::text END) AS v) __safe_numeric), 0) + COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (CASE WHEN NOT ((((SELECT NULLIF(filled_by_automated_pipeline, '') FROM roles WHERE role_id = p_role_id)) IS NULL OR ((SELECT NULLIF(filled_by_automated_pipeline, '') FROM roles WHERE role_id = p_role_id))::text = '')) THEN (1)::text ELSE (0)::text END) AS v) __safe_numeric), 0))) AS v) __safe_numeric), 0)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_roles_has_exactly_one_filler
-- Field: Roles.HasExactlyOneFiller
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_roles_has_exactly_one_filler(p_role_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((calc_roles_filled_by_arm_count(p_role_id))::NUMERIC = 1)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_roles_filler_type
-- Field: Roles.FillerType
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_roles_filler_type(p_role_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN NOT ((((SELECT NULLIF(filled_by_human_agent, '') FROM roles WHERE role_id = p_role_id)) IS NULL OR ((SELECT NULLIF(filled_by_human_agent, '') FROM roles WHERE role_id = p_role_id))::text = '')) THEN ('HumanAgent')::text ELSE (CASE WHEN NOT ((((SELECT NULLIF(filled_by_ai_agent, '') FROM roles WHERE role_id = p_role_id)) IS NULL OR ((SELECT NULLIF(filled_by_ai_agent, '') FROM roles WHERE role_id = p_role_id))::text = '')) THEN ('AIAgent')::text ELSE (CASE WHEN NOT ((((SELECT NULLIF(filled_by_automated_pipeline, '') FROM roles WHERE role_id = p_role_id)) IS NULL OR ((SELECT NULLIF(filled_by_automated_pipeline, '') FROM roles WHERE role_id = p_role_id))::text = '')) THEN ('AutomatedPipeline')::text ELSE ('')::text END)::text END)::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_roles_fills_approval_gate
-- Field: Roles.FillsApprovalGate
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_roles_fills_approval_gate(p_role_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM workflow_steps WHERE assigned_role = (SELECT NULLIF(role_id, '') FROM roles WHERE role_id = p_role_id) AND calc_workflow_steps_is_approval_gate(workflow_step_id) = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_roles_escalation_violation
-- Field: Roles.EscalationViolation
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_roles_escalation_violation(p_role_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (((calc_roles_fills_approval_gate(p_role_id))::NUMERIC > 0 AND (((SELECT NULLIF(delegates_to, '') FROM roles WHERE role_id = p_role_id)) IS NULL OR ((SELECT NULLIF(delegates_to, '') FROM roles WHERE role_id = p_role_id))::text = '')));
$$ LANGUAGE sql STABLE;

-- calc_role_assignments_parent_path
-- Field: RoleAssignments.ParentPath
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: RelativePath from related Roles


CREATE OR REPLACE FUNCTION calc_role_assignments_parent_path(p_role_assignment_id TEXT)
RETURNS TEXT AS $$
  SELECT calc_roles_relative_path((SELECT role FROM role_assignments WHERE role_assignment_id = p_role_assignment_id));
$$ LANGUAGE sql STABLE;

-- calc_role_assignments_relative_path
-- Field: RoleAssignments.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_role_assignments_relative_path(p_role_assignment_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT(calc_role_assignments_parent_path(p_role_assignment_id), '/assignments/', (SELECT NULLIF(role_assignment_id, '') FROM role_assignments WHERE role_assignment_id = p_role_assignment_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_role_assignments_iri
-- Field: RoleAssignments.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_role_assignments_iri(p_role_assignment_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_role_assignments_relative_path(p_role_assignment_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_role_assignments_name
-- Field: RoleAssignments.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_role_assignments_name(p_role_assignment_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(role, '') FROM role_assignments WHERE role_assignment_id = p_role_assignment_id), ' [', (SELECT valid_from::timestamptz FROM role_assignments WHERE role_assignment_id = p_role_assignment_id), ' -> ', CASE WHEN (((SELECT valid_to::timestamptz FROM role_assignments WHERE role_assignment_id = p_role_assignment_id)) IS NULL OR ((SELECT valid_to::timestamptz FROM role_assignments WHERE role_assignment_id = p_role_assignment_id))::text = '') THEN ('open')::text ELSE ((SELECT valid_to::timestamptz FROM role_assignments WHERE role_assignment_id = p_role_assignment_id))::text END, ']'))::text;
$$ LANGUAGE sql STABLE;

-- calc_role_assignments_filler_type
-- Field: RoleAssignments.FillerType
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_role_assignments_filler_type(p_role_assignment_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN NOT ((((SELECT NULLIF(filled_by_human_agent, '') FROM role_assignments WHERE role_assignment_id = p_role_assignment_id)) IS NULL OR ((SELECT NULLIF(filled_by_human_agent, '') FROM role_assignments WHERE role_assignment_id = p_role_assignment_id))::text = '')) THEN ('HumanAgent')::text ELSE (CASE WHEN NOT ((((SELECT NULLIF(filled_by_ai_agent, '') FROM role_assignments WHERE role_assignment_id = p_role_assignment_id)) IS NULL OR ((SELECT NULLIF(filled_by_ai_agent, '') FROM role_assignments WHERE role_assignment_id = p_role_assignment_id))::text = '')) THEN ('AIAgent')::text ELSE (CASE WHEN NOT ((((SELECT NULLIF(filled_by_automated_pipeline, '') FROM role_assignments WHERE role_assignment_id = p_role_assignment_id)) IS NULL OR ((SELECT NULLIF(filled_by_automated_pipeline, '') FROM role_assignments WHERE role_assignment_id = p_role_assignment_id))::text = '')) THEN ('AutomatedPipeline')::text ELSE ('')::text END)::text END)::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_role_assignments_is_current
-- Field: RoleAssignments.IsCurrent
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_role_assignments_is_current(p_role_assignment_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((((SELECT valid_to::timestamptz FROM role_assignments WHERE role_assignment_id = p_role_assignment_id)) IS NULL OR ((SELECT valid_to::timestamptz FROM role_assignments WHERE role_assignment_id = p_role_assignment_id))::text = ''))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_role_assignments_was_active_as_of_audit_date
-- Field: RoleAssignments.WasActiveAsOfAuditDate
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_role_assignments_was_active_as_of_audit_date(p_role_assignment_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (((SELECT valid_from::timestamptz FROM role_assignments WHERE role_assignment_id = p_role_assignment_id) <= '2026-03-01' AND ((((SELECT valid_to::timestamptz FROM role_assignments WHERE role_assignment_id = p_role_assignment_id)) IS NULL OR ((SELECT valid_to::timestamptz FROM role_assignments WHERE role_assignment_id = p_role_assignment_id))::text = '') OR (SELECT valid_to::timestamptz FROM role_assignments WHERE role_assignment_id = p_role_assignment_id) > '2026-03-01')))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_role_assignments_is_agent_type_change
-- Field: RoleAssignments.IsAgentTypeChange
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_role_assignments_is_agent_type_change(p_role_assignment_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((NOT ((((SELECT NULLIF(prior_filler_type, '') FROM role_assignments WHERE role_assignment_id = p_role_assignment_id)) IS NULL OR ((SELECT NULLIF(prior_filler_type, '') FROM role_assignments WHERE role_assignment_id = p_role_assignment_id))::text = '')) AND (SELECT NULLIF(prior_filler_type, '') FROM role_assignments WHERE role_assignment_id = p_role_assignment_id) <> calc_role_assignments_filler_type(p_role_assignment_id)))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_role_assignments_requires_compliance_audit
-- Field: RoleAssignments.RequiresComplianceAudit
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_role_assignments_requires_compliance_audit(p_role_assignment_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((NOT ((((SELECT NULLIF(prior_filler_type, '') FROM role_assignments WHERE role_assignment_id = p_role_assignment_id)) IS NULL OR ((SELECT NULLIF(prior_filler_type, '') FROM role_assignments WHERE role_assignment_id = p_role_assignment_id))::text = '')) AND (SELECT NULLIF(prior_filler_type, '') FROM role_assignments WHERE role_assignment_id = p_role_assignment_id) = 'AIAgent' AND calc_role_assignments_filler_type(p_role_assignment_id) = 'HumanAgent'))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_departments_relative_path
-- Field: Departments.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_departments_relative_path(p_department_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT('departments/', (SELECT NULLIF(department_id, '') FROM departments WHERE department_id = p_department_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_departments_iri
-- Field: Departments.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_departments_iri(p_department_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_departments_relative_path(p_department_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_departments_name
-- Field: Departments.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_departments_name(p_department_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(display_name, '') FROM departments WHERE department_id = p_department_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_human_agents_relative_path
-- Field: HumanAgents.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_human_agents_relative_path(p_human_agent_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT('human-agents/', (SELECT NULLIF(human_agent_id, '') FROM human_agents WHERE human_agent_id = p_human_agent_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_human_agents_iri
-- Field: HumanAgents.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_human_agents_iri(p_human_agent_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_human_agents_relative_path(p_human_agent_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_ai_agents_relative_path
-- Field: AIAgents.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_ai_agents_relative_path(p_ai_agent_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT('ai-agents/', (SELECT NULLIF(ai_agent_id, '') FROM ai_agents WHERE ai_agent_id = p_ai_agent_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_ai_agents_iri
-- Field: AIAgents.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_ai_agents_iri(p_ai_agent_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_ai_agents_relative_path(p_ai_agent_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_ai_agents_count_attributed_artifacts
-- Field: AIAgents.CountAttributedArtifacts
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_ai_agents_count_attributed_artifacts(p_ai_agent_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM workflow_artifacts WHERE attributed_to_ai_agent = (SELECT NULLIF(ai_agent_id, '') FROM ai_agents WHERE ai_agent_id = p_ai_agent_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_ai_agents_count_impacted_workflows
-- Field: AIAgents.CountImpactedWorkflows
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_ai_agents_count_impacted_workflows(p_ai_agent_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM workflow_artifacts WHERE attributed_to_ai_agent = (SELECT NULLIF(ai_agent_id, '') FROM ai_agents WHERE ai_agent_id = p_ai_agent_id) AND calc_workflow_artifacts_has_producing_workflow(artifact_id) = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_automated_pipelines_relative_path
-- Field: AutomatedPipelines.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_automated_pipelines_relative_path(p_automated_pipeline_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT('automated-pipelines/', (SELECT NULLIF(automated_pipeline_id, '') FROM automated_pipelines WHERE automated_pipeline_id = p_automated_pipeline_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_automated_pipelines_iri
-- Field: AutomatedPipelines.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_automated_pipelines_iri(p_automated_pipeline_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_automated_pipelines_relative_path(p_automated_pipeline_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_workflow_status_concepts_relative_path
-- Field: WorkflowStatusConcepts.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_workflow_status_concepts_relative_path(p_concept_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT('concepts/workflow-status/', (SELECT NULLIF(concept_id, '') FROM workflow_status_concepts WHERE concept_id = p_concept_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_workflow_status_concepts_iri
-- Field: WorkflowStatusConcepts.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_workflow_status_concepts_iri(p_concept_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_workflow_status_concepts_relative_path(p_concept_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_agent_capability_concepts_relative_path
-- Field: AgentCapabilityConcepts.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_agent_capability_concepts_relative_path(p_concept_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT('concepts/agent-capability/', (SELECT NULLIF(concept_id, '') FROM agent_capability_concepts WHERE concept_id = p_concept_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_agent_capability_concepts_iri
-- Field: AgentCapabilityConcepts.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_agent_capability_concepts_iri(p_concept_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_agent_capability_concepts_relative_path(p_concept_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_artifact_type_concepts_relative_path
-- Field: ArtifactTypeConcepts.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_artifact_type_concepts_relative_path(p_concept_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT('concepts/artifact-type/', (SELECT NULLIF(concept_id, '') FROM artifact_type_concepts WHERE concept_id = p_concept_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_artifact_type_concepts_iri
-- Field: ArtifactTypeConcepts.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_artifact_type_concepts_iri(p_concept_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_artifact_type_concepts_relative_path(p_concept_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_datasets_relative_path
-- Field: Datasets.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_datasets_relative_path(p_dataset_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT('datasets/', (SELECT NULLIF(dataset_id, '') FROM datasets WHERE dataset_id = p_dataset_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_datasets_iri
-- Field: Datasets.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_datasets_iri(p_dataset_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_datasets_relative_path(p_dataset_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_datasets_is_consumed
-- Field: Datasets.IsConsumed
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_datasets_is_consumed(p_dataset_id TEXT)
RETURNS BOOLEAN AS $$
  WITH __erb_dedup_v1 AS (SELECT calc_datasets_consumed_by_steps(p_dataset_id) AS val) SELECT (NOT ((((SELECT val FROM __erb_dedup_v1)) IS NULL OR ((SELECT val FROM __erb_dedup_v1))::text = '')))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_workflow_artifacts_parent_path
-- Field: WorkflowArtifacts.ParentPath
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: RelativePath from related WorkflowSteps


CREATE OR REPLACE FUNCTION calc_workflow_artifacts_parent_path(p_artifact_id TEXT)
RETURNS TEXT AS $$
  SELECT calc_workflow_steps_relative_path((SELECT produced_by_step FROM workflow_artifacts WHERE artifact_id = p_artifact_id));
$$ LANGUAGE sql STABLE;

-- calc_workflow_artifacts_produced_by_workflow
-- Field: WorkflowArtifacts.ProducedByWorkflow
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: Workflow from related WorkflowSteps


CREATE OR REPLACE FUNCTION calc_workflow_artifacts_produced_by_workflow(p_artifact_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT workflow::text FROM workflow_steps WHERE workflow_step_id = (SELECT produced_by_step FROM workflow_artifacts WHERE artifact_id = p_artifact_id));
$$ LANGUAGE sql STABLE;

-- get_artifact_type_concepts_pref_label
-- Helper function: Get PrefLabel from ArtifactTypeConcepts by ConceptId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_artifact_type_concepts_pref_label(p_concept_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT pref_label FROM artifact_type_concepts WHERE concept_id = p_concept_id);
$$ LANGUAGE sql STABLE;

-- get_artifact_type_concepts_alt_label
-- Helper function: Get AltLabel from ArtifactTypeConcepts by ConceptId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_artifact_type_concepts_alt_label(p_concept_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT alt_label FROM artifact_type_concepts WHERE concept_id = p_concept_id);
$$ LANGUAGE sql STABLE;

-- get_artifact_type_concepts_definition
-- Helper function: Get Definition from ArtifactTypeConcepts by ConceptId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_artifact_type_concepts_definition(p_concept_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT definition FROM artifact_type_concepts WHERE concept_id = p_concept_id);
$$ LANGUAGE sql STABLE;

-- get_artifact_type_concepts_scope_note
-- Helper function: Get ScopeNote from ArtifactTypeConcepts by ConceptId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_artifact_type_concepts_scope_note(p_concept_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT scope_note FROM artifact_type_concepts WHERE concept_id = p_concept_id);
$$ LANGUAGE sql STABLE;

-- calc_workflow_artifacts_relative_path
-- Field: WorkflowArtifacts.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_workflow_artifacts_relative_path(p_artifact_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT(calc_workflow_artifacts_parent_path(p_artifact_id), '/artifacts/', (SELECT NULLIF(artifact_id, '') FROM workflow_artifacts WHERE artifact_id = p_artifact_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_workflow_artifacts_iri
-- Field: WorkflowArtifacts.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_workflow_artifacts_iri(p_artifact_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_workflow_artifacts_relative_path(p_artifact_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_workflow_artifacts_producing_agent_type
-- Field: WorkflowArtifacts.ProducingAgentType
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_workflow_artifacts_producing_agent_type(p_artifact_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN NOT ((((SELECT NULLIF(attributed_to_human_agent, '') FROM workflow_artifacts WHERE artifact_id = p_artifact_id)) IS NULL OR ((SELECT NULLIF(attributed_to_human_agent, '') FROM workflow_artifacts WHERE artifact_id = p_artifact_id))::text = '')) THEN ('HumanAgent')::text ELSE (CASE WHEN NOT ((((SELECT NULLIF(attributed_to_ai_agent, '') FROM workflow_artifacts WHERE artifact_id = p_artifact_id)) IS NULL OR ((SELECT NULLIF(attributed_to_ai_agent, '') FROM workflow_artifacts WHERE artifact_id = p_artifact_id))::text = '')) THEN ('AIAgent')::text ELSE (CASE WHEN NOT ((((SELECT NULLIF(attributed_to_automated_pipeline, '') FROM workflow_artifacts WHERE artifact_id = p_artifact_id)) IS NULL OR ((SELECT NULLIF(attributed_to_automated_pipeline, '') FROM workflow_artifacts WHERE artifact_id = p_artifact_id))::text = '')) THEN ('AutomatedPipeline')::text ELSE ('')::text END)::text END)::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_workflow_artifacts_has_derivation_parent
-- Field: WorkflowArtifacts.HasDerivationParent
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflow_artifacts_has_derivation_parent(p_artifact_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (NOT ((((SELECT NULLIF(derived_from_artifact, '') FROM workflow_artifacts WHERE artifact_id = p_artifact_id)) IS NULL OR ((SELECT NULLIF(derived_from_artifact, '') FROM workflow_artifacts WHERE artifact_id = p_artifact_id))::text = '')))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_workflow_artifacts_has_producing_workflow
-- Field: WorkflowArtifacts.HasProducingWorkflow
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_workflow_artifacts_has_producing_workflow(p_artifact_id TEXT)
RETURNS BOOLEAN AS $$
  WITH __erb_dedup_v1 AS (SELECT calc_workflow_artifacts_produced_by_workflow(p_artifact_id) AS val) SELECT (NOT ((((SELECT val FROM __erb_dedup_v1)) IS NULL OR ((SELECT val FROM __erb_dedup_v1))::text = '')))::boolean;
$$ LANGUAGE sql STABLE;

-- get_change_log_version
-- Helper function: Get Version from ChangeLog by ChangeLogId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_change_log_version(p_change_log_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT version FROM change_log WHERE change_log_id = p_change_log_id);
$$ LANGUAGE sql STABLE;

-- get_change_log_change_date
-- Helper function: Get ChangeDate from ChangeLog by ChangeLogId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_change_log_change_date(p_change_log_id TEXT)
RETURNS DATE AS $$
  SELECT (SELECT change_date FROM change_log WHERE change_log_id = p_change_log_id);
$$ LANGUAGE sql STABLE;

-- get_change_log_change_kind
-- Helper function: Get ChangeKind from ChangeLog by ChangeLogId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_change_log_change_kind(p_change_log_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT change_kind FROM change_log WHERE change_log_id = p_change_log_id);
$$ LANGUAGE sql STABLE;

-- get_change_log_motivating_question
-- Helper function: Get MotivatingQuestion from ChangeLog by ChangeLogId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_change_log_motivating_question(p_change_log_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT motivating_question FROM change_log WHERE change_log_id = p_change_log_id);
$$ LANGUAGE sql STABLE;

-- get_change_log_terms_affected
-- Helper function: Get TermsAffected from ChangeLog by ChangeLogId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_change_log_terms_affected(p_change_log_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT terms_affected FROM change_log WHERE change_log_id = p_change_log_id);
$$ LANGUAGE sql STABLE;

-- get_change_log_rationale
-- Helper function: Get Rationale from ChangeLog by ChangeLogId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_change_log_rationale(p_change_log_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT rationale FROM change_log WHERE change_log_id = p_change_log_id);
$$ LANGUAGE sql STABLE;

-- calc_governance_roles_relative_path
-- Field: GovernanceRoles.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_governance_roles_relative_path(p_governance_role_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT('governance-roles/', (SELECT NULLIF(governance_role_id, '') FROM governance_roles WHERE governance_role_id = p_governance_role_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_governance_roles_iri
-- Field: GovernanceRoles.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_governance_roles_iri(p_governance_role_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_governance_roles_relative_path(p_governance_role_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_governance_roles_name
-- Field: GovernanceRoles.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_governance_roles_name(p_governance_role_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(display_name, '') FROM governance_roles WHERE governance_role_id = p_governance_role_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_governance_roles_can_approve_changes
-- Field: GovernanceRoles.CanApproveChanges
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_governance_roles_can_approve_changes(p_governance_role_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((SELECT NULLIF(kind, '') FROM governance_roles WHERE governance_role_id = p_governance_role_id) = 'Authority')::boolean;
$$ LANGUAGE sql STABLE;

-- get_governance_roles_display_name
-- Helper function: Get DisplayName from GovernanceRoles by GovernanceRoleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_governance_roles_display_name(p_governance_role_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT display_name FROM governance_roles WHERE governance_role_id = p_governance_role_id);
$$ LANGUAGE sql STABLE;

-- get_governance_roles_kind
-- Helper function: Get Kind from GovernanceRoles by GovernanceRoleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_governance_roles_kind(p_governance_role_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT kind FROM governance_roles WHERE governance_role_id = p_governance_role_id);
$$ LANGUAGE sql STABLE;

-- get_governance_roles_responsibilities
-- Helper function: Get Responsibilities from GovernanceRoles by GovernanceRoleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_governance_roles_responsibilities(p_governance_role_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT responsibilities FROM governance_roles WHERE governance_role_id = p_governance_role_id);
$$ LANGUAGE sql STABLE;

-- get_governance_roles_approval_scope
-- Helper function: Get ApprovalScope from GovernanceRoles by GovernanceRoleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_governance_roles_approval_scope(p_governance_role_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT approval_scope FROM governance_roles WHERE governance_role_id = p_governance_role_id);
$$ LANGUAGE sql STABLE;

-- get_governance_roles_held_by
-- Helper function: Get HeldBy from GovernanceRoles by GovernanceRoleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_governance_roles_held_by(p_governance_role_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT held_by FROM governance_roles WHERE governance_role_id = p_governance_role_id);
$$ LANGUAGE sql STABLE;

-- calc_change_log_relative_path
-- Field: ChangeLog.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_change_log_relative_path(p_change_log_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT('change-log/', (SELECT NULLIF(change_log_id, '') FROM change_log WHERE change_log_id = p_change_log_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_change_log_iri
-- Field: ChangeLog.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_change_log_iri(p_change_log_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_change_log_relative_path(p_change_log_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_change_log_name
-- Field: ChangeLog.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_change_log_name(p_change_log_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(version, '') FROM change_log WHERE change_log_id = p_change_log_id), ' (', (SELECT change_date::timestamptz FROM change_log WHERE change_log_id = p_change_log_id), ')'))::text;
$$ LANGUAGE sql STABLE;

-- calc_change_log_is_breaking_change
-- Field: ChangeLog.IsBreakingChange
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_change_log_is_breaking_change(p_change_log_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((SELECT NULLIF(change_kind, '') FROM change_log WHERE change_log_id = p_change_log_id) = 'major')::boolean;
$$ LANGUAGE sql STABLE;

-- calc_change_log_is_backward_compatible
-- Field: ChangeLog.IsBackwardCompatible
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_change_log_is_backward_compatible(p_change_log_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (((SELECT NULLIF(change_kind, '') FROM change_log WHERE change_log_id = p_change_log_id) = 'patch' OR (SELECT NULLIF(change_kind, '') FROM change_log WHERE change_log_id = p_change_log_id) = 'minor'))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_vocabulary_reconciliations_relative_path
-- Field: VocabularyReconciliations.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_vocabulary_reconciliations_relative_path(p_reconciliation_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT('reconciliations/', (SELECT NULLIF(reconciliation_id, '') FROM vocabulary_reconciliations WHERE reconciliation_id = p_reconciliation_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_vocabulary_reconciliations_iri
-- Field: VocabularyReconciliations.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_vocabulary_reconciliations_iri(p_reconciliation_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_vocabulary_reconciliations_relative_path(p_reconciliation_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_vocabulary_reconciliations_name
-- Field: VocabularyReconciliations.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_vocabulary_reconciliations_name(p_reconciliation_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(deprecated_term, '') FROM vocabulary_reconciliations WHERE reconciliation_id = p_reconciliation_id), ' owl:sameAs ', (SELECT NULLIF(replacement_term, '') FROM vocabulary_reconciliations WHERE reconciliation_id = p_reconciliation_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_scenarios_relative_path
-- Field: Scenarios.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_scenarios_relative_path(p_scenario_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT('scenarios/', (SELECT NULLIF(scenario_id, '') FROM scenarios WHERE scenario_id = p_scenario_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_scenarios_iri
-- Field: Scenarios.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_scenarios_iri(p_scenario_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_scenarios_relative_path(p_scenario_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_scenarios_name
-- Field: Scenarios.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_scenarios_name(p_scenario_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(label, '') FROM scenarios WHERE scenario_id = p_scenario_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- get_scenarios_label
-- Helper function: Get Label from Scenarios by ScenarioId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_scenarios_label(p_scenario_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT label FROM scenarios WHERE scenario_id = p_scenario_id);
$$ LANGUAGE sql STABLE;

-- get_scenarios_icon
-- Helper function: Get Icon from Scenarios by ScenarioId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_scenarios_icon(p_scenario_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT icon FROM scenarios WHERE scenario_id = p_scenario_id);
$$ LANGUAGE sql STABLE;

-- get_scenarios_explanation
-- Helper function: Get Explanation from Scenarios by ScenarioId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_scenarios_explanation(p_scenario_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT explanation FROM scenarios WHERE scenario_id = p_scenario_id);
$$ LANGUAGE sql STABLE;

-- get_scenarios_sort_order
-- Helper function: Get SortOrder from Scenarios by ScenarioId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_scenarios_sort_order(p_scenario_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT sort_order FROM scenarios WHERE scenario_id = p_scenario_id);
$$ LANGUAGE sql STABLE;

-- get_scenarios_is_reset
-- Helper function: Get IsReset from Scenarios by ScenarioId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_scenarios_is_reset(p_scenario_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT is_reset FROM scenarios WHERE scenario_id = p_scenario_id);
$$ LANGUAGE sql STABLE;

-- get_scenarios_edits
-- Helper function: Get Edits from Scenarios by ScenarioId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_scenarios_edits(p_scenario_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT edits FROM scenarios WHERE scenario_id = p_scenario_id);
$$ LANGUAGE sql STABLE;

-- calc_competency_questions_relative_path
-- Field: CompetencyQuestions.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_competency_questions_relative_path(p_competency_question_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT('competency-questions/', (SELECT NULLIF(competency_question_id, '') FROM competency_questions WHERE competency_question_id = p_competency_question_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_competency_questions_iri
-- Field: CompetencyQuestions.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_competency_questions_iri(p_competency_question_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_competency_questions_relative_path(p_competency_question_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_competency_questions_name
-- Field: CompetencyQuestions.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_competency_questions_name(p_competency_question_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(display_name, '') FROM competency_questions WHERE competency_question_id = p_competency_question_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- get_competency_questions_number
-- Helper function: Get Number from CompetencyQuestions by CompetencyQuestionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_competency_questions_number(p_competency_question_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (SELECT number FROM competency_questions WHERE competency_question_id = p_competency_question_id);
$$ LANGUAGE sql STABLE;

-- get_competency_questions_display_name
-- Helper function: Get DisplayName from CompetencyQuestions by CompetencyQuestionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_competency_questions_display_name(p_competency_question_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT display_name FROM competency_questions WHERE competency_question_id = p_competency_question_id);
$$ LANGUAGE sql STABLE;

-- get_competency_questions_question_text
-- Helper function: Get QuestionText from CompetencyQuestions by CompetencyQuestionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_competency_questions_question_text(p_competency_question_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT question_text FROM competency_questions WHERE competency_question_id = p_competency_question_id);
$$ LANGUAGE sql STABLE;

-- get_competency_questions_target_table
-- Helper function: Get TargetTable from CompetencyQuestions by CompetencyQuestionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_competency_questions_target_table(p_competency_question_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT target_table FROM competency_questions WHERE competency_question_id = p_competency_question_id);
$$ LANGUAGE sql STABLE;

-- get_competency_questions_target_field
-- Helper function: Get TargetField from CompetencyQuestions by CompetencyQuestionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_competency_questions_target_field(p_competency_question_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT target_field FROM competency_questions WHERE competency_question_id = p_competency_question_id);
$$ LANGUAGE sql STABLE;

-- get_competency_questions_answer_kind
-- Helper function: Get AnswerKind from CompetencyQuestions by CompetencyQuestionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_competency_questions_answer_kind(p_competency_question_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT answer_kind FROM competency_questions WHERE competency_question_id = p_competency_question_id);
$$ LANGUAGE sql STABLE;

-- get_competency_questions_expected_answer
-- Helper function: Get ExpectedAnswer from CompetencyQuestions by CompetencyQuestionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_competency_questions_expected_answer(p_competency_question_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT expected_answer FROM competency_questions WHERE competency_question_id = p_competency_question_id);
$$ LANGUAGE sql STABLE;

-- get_competency_questions_satisfied_field
-- Helper function: Get SatisfiedField from CompetencyQuestions by CompetencyQuestionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_competency_questions_satisfied_field(p_competency_question_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT satisfied_field FROM competency_questions WHERE competency_question_id = p_competency_question_id);
$$ LANGUAGE sql STABLE;

-- get_competency_questions_explanation
-- Helper function: Get Explanation from CompetencyQuestions by CompetencyQuestionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_competency_questions_explanation(p_competency_question_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT explanation FROM competency_questions WHERE competency_question_id = p_competency_question_id);
$$ LANGUAGE sql STABLE;

-- get_competency_questions_sort_order
-- Helper function: Get SortOrder from CompetencyQuestions by CompetencyQuestionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_competency_questions_sort_order(p_competency_question_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (SELECT sort_order FROM competency_questions WHERE competency_question_id = p_competency_question_id);
$$ LANGUAGE sql STABLE;

-- get_competency_questions_is_active
-- Helper function: Get IsActive from CompetencyQuestions by CompetencyQuestionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_competency_questions_is_active(p_competency_question_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT is_active FROM competency_questions WHERE competency_question_id = p_competency_question_id);
$$ LANGUAGE sql STABLE;

-- calc_scenario_cq_effects_relative_path
-- Field: ScenarioCQEffects.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_scenario_cq_effects_relative_path(p_scenario_cq_effect_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT('scenario-cq-effects/', (SELECT NULLIF(scenario_cq_effect_id, '') FROM scenario_cq_effects WHERE scenario_cq_effect_id = p_scenario_cq_effect_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_scenario_cq_effects_iri
-- Field: ScenarioCQEffects.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_scenario_cq_effects_iri(p_scenario_cq_effect_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_scenario_cq_effects_relative_path(p_scenario_cq_effect_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_scenario_cq_effects_name
-- Field: ScenarioCQEffects.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_scenario_cq_effects_name(p_scenario_cq_effect_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(scenario_cq_effect_id, '') FROM scenario_cq_effects WHERE scenario_cq_effect_id = p_scenario_cq_effect_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_conformance_tests_relative_path
-- Field: ConformanceTests.RelativePath
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_conformance_tests_relative_path(p_conformance_test_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT('conformance-tests/', (SELECT NULLIF(conformance_test_id, '') FROM conformance_tests WHERE conformance_test_id = p_conformance_test_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_conformance_tests_iri
-- Field: ConformanceTests.Iri
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_conformance_tests_iri(p_conformance_test_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(calc_conformance_tests_relative_path(p_conformance_test_id), '/', '-'))::text;
$$ LANGUAGE sql STABLE;

-- calc_conformance_tests_name
-- Field: ConformanceTests.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_conformance_tests_name(p_conformance_test_id TEXT)
RETURNS TEXT AS $$
  SELECT (REPLACE(LOWER((SELECT NULLIF(display_name, '') FROM conformance_tests WHERE conformance_test_id = p_conformance_test_id)), ' ', '-'))::text;
$$ LANGUAGE sql STABLE;

-- ============================================================================
-- MANY-SIDE RELATIONSHIP FUNCTIONS
-- These functions aggregate child records for many-side relationships
-- ============================================================================

-- ============================================================================
-- INVERSE RELATIONSHIP FUNCTIONS
-- These functions perform reverse FK lookups for inverse-side relationships
-- ============================================================================

-- calc_datasets_consumed_by_steps
-- Field: Datasets.ConsumedBySteps
-- Type: Inverse relationship (reverse FK lookup from WorkflowSteps.ConsumesDataset)

CREATE OR REPLACE FUNCTION calc_datasets_consumed_by_steps(p_dataset_id TEXT)
RETURNS TEXT AS $$
  SELECT (
    SELECT STRING_AGG(workflow_step_id::TEXT, ', ' ORDER BY workflow_step_id)
    FROM workflow_steps
    WHERE consumes_dataset = p_dataset_id
  );
$$ LANGUAGE sql STABLE;

