-- ============================================================================
-- CREATE TABLES (check-add mode) - Idempotent schema, never drops columns
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Tables: 10
-- Total Raw Fields: 76
-- ============================================================================

SET timezone = 'UTC';

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Loops: Table: Loops — build history and forward plan. Each row documents what new concept is introduced, what was witnessed, and what the next empirical question is.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS loops (
  loop_id                             TEXT                 PRIMARY KEY          -- Unique identifier: loop-01, loop-02, …
);
ALTER TABLE loops ADD COLUMN IF NOT EXISTS title TEXT;                                              -- Short title for what this loop adds.
ALTER TABLE loops ADD COLUMN IF NOT EXISTS status TEXT;                                             -- planned | in-progress | complete
ALTER TABLE loops ADD COLUMN IF NOT EXISTS new_concept TEXT;                                        -- The new first-class domain concept introduced this loop.
ALTER TABLE loops ADD COLUMN IF NOT EXISTS domain_question TEXT;                                    -- The natural-language question this loop's concept answers.
ALTER TABLE loops ADD COLUMN IF NOT EXISTS mock_data_note TEXT;                                     -- What the seed data is designed to show.
ALTER TABLE loops ADD COLUMN IF NOT EXISTS next_suggestion TEXT;                                    -- Suggestion for the next loop.
ALTER TABLE loops ADD COLUMN IF NOT EXISTS commit_hash TEXT;                                        -- Git SHA where this loop first landed.
ALTER TABLE loops ADD COLUMN IF NOT EXISTS commit_date DATE;                                        -- ISO date of the commit.
COMMENT ON TABLE loops IS 'Table: Loops — build history and forward plan. Each row documents what new concept is introduced, what was witnessed, and what the next empirical question is.';
COMMENT ON COLUMN loops.loop_id IS 'Unique identifier: loop-01, loop-02, …';
COMMENT ON COLUMN loops.title IS 'Short title for what this loop adds.';
COMMENT ON COLUMN loops.status IS 'planned | in-progress | complete';
COMMENT ON COLUMN loops.new_concept IS 'The new first-class domain concept introduced this loop.';
COMMENT ON COLUMN loops.domain_question IS 'The natural-language question this loop''s concept answers.';
COMMENT ON COLUMN loops.mock_data_note IS 'What the seed data is designed to show.';
COMMENT ON COLUMN loops.next_suggestion IS 'Suggestion for the next loop.';
COMMENT ON COLUMN loops.commit_hash IS 'Git SHA where this loop first landed.';
COMMENT ON COLUMN loops.commit_date IS 'ISO date of the commit.';

-- ----------------------------------------------------------------------------
-- PhysicsConstants: Table: PhysicsConstants — fundamental constants used in Coulomb's Law calculations. Single source of truth for k, e, a₀, etc.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS physics_constants (
  constant_id                         TEXT                 PRIMARY KEY          -- Unique identifier (e.g. coulomb_k, elem_charge)
);
ALTER TABLE physics_constants ADD COLUMN IF NOT EXISTS name TEXT;                                   -- Human-readable name
ALTER TABLE physics_constants ADD COLUMN IF NOT EXISTS symbol TEXT;                                 -- Physics symbol (k, e, a₀, …)
ALTER TABLE physics_constants ADD COLUMN IF NOT EXISTS value NUMERIC;                               -- Numeric value in SI units
ALTER TABLE physics_constants ADD COLUMN IF NOT EXISTS units TEXT;                                  -- SI unit string
ALTER TABLE physics_constants ADD COLUMN IF NOT EXISTS description TEXT;                            -- What this constant represents
COMMENT ON TABLE physics_constants IS 'Table: PhysicsConstants — fundamental constants used in Coulomb''s Law calculations. Single source of truth for k, e, a₀, etc.';
COMMENT ON COLUMN physics_constants.constant_id IS 'Unique identifier (e.g. coulomb_k, elem_charge)';
COMMENT ON COLUMN physics_constants.name IS 'Human-readable name';
COMMENT ON COLUMN physics_constants.symbol IS 'Physics symbol (k, e, a₀, …)';
COMMENT ON COLUMN physics_constants.value IS 'Numeric value in SI units';
COMMENT ON COLUMN physics_constants.units IS 'SI unit string';
COMMENT ON COLUMN physics_constants.description IS 'What this constant represents';

-- ----------------------------------------------------------------------------
-- Particles: Table: Particles — named particle archetypes with canonical charge and mass values. Used as reference for Charges rows.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS particles (
  particle_id                         TEXT                 PRIMARY KEY          -- Unique identifier
);
ALTER TABLE particles ADD COLUMN IF NOT EXISTS name TEXT;                                           -- Common name (Proton, Electron, …)
ALTER TABLE particles ADD COLUMN IF NOT EXISTS canonical_charge NUMERIC;                            -- Charge in Coulombs (positive or negative)
ALTER TABLE particles ADD COLUMN IF NOT EXISTS canonical_mass NUMERIC;                              -- Rest mass in kg
ALTER TABLE particles ADD COLUMN IF NOT EXISTS description TEXT;                                    -- Physical description
COMMENT ON TABLE particles IS 'Table: Particles — named particle archetypes with canonical charge and mass values. Used as reference for Charges rows.';
COMMENT ON COLUMN particles.particle_id IS 'Unique identifier';
COMMENT ON COLUMN particles.name IS 'Common name (Proton, Electron, …)';
COMMENT ON COLUMN particles.canonical_charge IS 'Charge in Coulombs (positive or negative)';
COMMENT ON COLUMN particles.canonical_mass IS 'Rest mass in kg';
COMMENT ON COLUMN particles.description IS 'Physical description';

-- ----------------------------------------------------------------------------
-- Charges: Table: Charges — individual charged particles with 3D position and physical properties. The raw leaves of the Coulomb's Law DAG.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS charges (
  charge_id                           TEXT                 PRIMARY KEY          -- Unique identifier
);
ALTER TABLE charges ADD COLUMN IF NOT EXISTS name TEXT;                                             -- Human-readable label (Proton A, Electron B, …)
ALTER TABLE charges ADD COLUMN IF NOT EXISTS system_id TEXT;                                        -- FK → Systems.SystemId — which physical system this charge belongs to
ALTER TABLE charges ADD COLUMN IF NOT EXISTS particle_id TEXT;                                      -- FK → Particles.ParticleId — archetype (optional)
ALTER TABLE charges ADD COLUMN IF NOT EXISTS charge_value NUMERIC;                                  -- Charge in Coulombs (signed: positive or negative)
ALTER TABLE charges ADD COLUMN IF NOT EXISTS position_x NUMERIC;                                    -- X coordinate in meters
ALTER TABLE charges ADD COLUMN IF NOT EXISTS position_y NUMERIC;                                    -- Y coordinate in meters
ALTER TABLE charges ADD COLUMN IF NOT EXISTS position_z NUMERIC;                                    -- Z coordinate in meters
ALTER TABLE charges ADD COLUMN IF NOT EXISTS mass NUMERIC;                                          -- Mass in kg (null = massless / not tracked)
COMMENT ON TABLE charges IS 'Table: Charges — individual charged particles with 3D position and physical properties. The raw leaves of the Coulomb''s Law DAG.';
COMMENT ON COLUMN charges.charge_id IS 'Unique identifier';
COMMENT ON COLUMN charges.name IS 'Human-readable label (Proton A, Electron B, …)';
COMMENT ON COLUMN charges.system_id IS 'FK → Systems.SystemId — which physical system this charge belongs to';
COMMENT ON COLUMN charges.particle_id IS 'FK → Particles.ParticleId — archetype (optional)';
COMMENT ON COLUMN charges.charge_value IS 'Charge in Coulombs (signed: positive or negative)';
COMMENT ON COLUMN charges.position_x IS 'X coordinate in meters';
COMMENT ON COLUMN charges.position_y IS 'Y coordinate in meters';
COMMENT ON COLUMN charges.position_z IS 'Z coordinate in meters';
COMMENT ON COLUMN charges.mass IS 'Mass in kg (null = massless / not tracked)';

-- ----------------------------------------------------------------------------
-- Systems: Table: Systems — named physical configurations of charges. Groups Charges into testable scenarios (hydrogen atom, NaCl pair, triangle of charges, etc.).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS systems (
  system_id                           TEXT                 PRIMARY KEY          -- Unique identifier
);
ALTER TABLE systems ADD COLUMN IF NOT EXISTS name TEXT;                                             -- Human-readable name
ALTER TABLE systems ADD COLUMN IF NOT EXISTS description TEXT;                                      -- What physical situation this represents
ALTER TABLE systems ADD COLUMN IF NOT EXISTS is_synthetic BOOLEAN;                                  -- True if this is a constructed example; false if from real measurements
COMMENT ON TABLE systems IS 'Table: Systems — named physical configurations of charges. Groups Charges into testable scenarios (hydrogen atom, NaCl pair, triangle of charges, etc.).';
COMMENT ON COLUMN systems.system_id IS 'Unique identifier';
COMMENT ON COLUMN systems.name IS 'Human-readable name';
COMMENT ON COLUMN systems.description IS 'What physical situation this represents';
COMMENT ON COLUMN systems.is_synthetic IS 'True if this is a constructed example; false if from real measurements';

-- ----------------------------------------------------------------------------
-- ChargeInteractions: Table: ChargeInteractions — pairwise electrostatic interactions. One row per ordered pair (Charge1, Charge2) within a system. Position and charge values are stored directly (denormalized from Charges) so that DeltaX/Y/Z, DistanceMeters, ForceMagnitude, IsAttractive, and IsRepulsive can be computed as calculated fields. F = k·|q₁·q₂|/r² falls out of the DAG.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS charge_interactions (
  interaction_id                      TEXT                 PRIMARY KEY          -- Unique identifier
);
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS system_id TEXT;                            -- FK → Systems.SystemId
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS charge1_id TEXT;                           -- FK → Charges.ChargeId (first particle)
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS charge2_id TEXT;                           -- FK → Charges.ChargeId (second particle)
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS charge1_label TEXT;                        -- Human label copied from Charges.Name at seed time
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS charge2_label TEXT;                        -- Human label copied from Charges.Name at seed time
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS q1 NUMERIC;                                -- Charge value of Charge1 in Coulombs (copied from Charges.ChargeValue)
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS q2 NUMERIC;                                -- Charge value of Charge2 in Coulombs (copied from Charges.ChargeValue)
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS x1 NUMERIC;                                -- X position of Charge1 in meters (copied from Charges.PositionX)
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS y1 NUMERIC;                                -- Y position of Charge1 in meters (copied from Charges.PositionY)
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS z1 NUMERIC;                                -- Z position of Charge1 in meters (copied from Charges.PositionZ)
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS x2 NUMERIC;                                -- X position of Charge2 in meters (copied from Charges.PositionX)
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS y2 NUMERIC;                                -- Y position of Charge2 in meters (copied from Charges.PositionY)
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS z2 NUMERIC;                                -- Z position of Charge2 in meters (copied from Charges.PositionZ)
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS coulomb_k NUMERIC;                         -- Coulomb's constant: 8.99×10⁹ N·m²·C⁻². Stored per-row so the formula is self-contained.
COMMENT ON TABLE charge_interactions IS 'Table: ChargeInteractions — pairwise electrostatic interactions. One row per ordered pair (Charge1, Charge2) within a system. Position and charge values are stored directly (denormalized from Charges) so that DeltaX/Y/Z, DistanceMeters, ForceMagnitude, IsAttractive, and IsRepulsive can be computed as calculated fields. F = k·|q₁·q₂|/r² falls out of the DAG.';
COMMENT ON COLUMN charge_interactions.interaction_id IS 'Unique identifier';
COMMENT ON COLUMN charge_interactions.system_id IS 'FK → Systems.SystemId';
COMMENT ON COLUMN charge_interactions.charge1_id IS 'FK → Charges.ChargeId (first particle)';
COMMENT ON COLUMN charge_interactions.charge2_id IS 'FK → Charges.ChargeId (second particle)';
COMMENT ON COLUMN charge_interactions.charge1_label IS 'Human label copied from Charges.Name at seed time';
COMMENT ON COLUMN charge_interactions.charge2_label IS 'Human label copied from Charges.Name at seed time';
COMMENT ON COLUMN charge_interactions.q1 IS 'Charge value of Charge1 in Coulombs (copied from Charges.ChargeValue)';
COMMENT ON COLUMN charge_interactions.q2 IS 'Charge value of Charge2 in Coulombs (copied from Charges.ChargeValue)';
COMMENT ON COLUMN charge_interactions.x1 IS 'X position of Charge1 in meters (copied from Charges.PositionX)';
COMMENT ON COLUMN charge_interactions.y1 IS 'Y position of Charge1 in meters (copied from Charges.PositionY)';
COMMENT ON COLUMN charge_interactions.z1 IS 'Z position of Charge1 in meters (copied from Charges.PositionZ)';
COMMENT ON COLUMN charge_interactions.x2 IS 'X position of Charge2 in meters (copied from Charges.PositionX)';
COMMENT ON COLUMN charge_interactions.y2 IS 'Y position of Charge2 in meters (copied from Charges.PositionY)';
COMMENT ON COLUMN charge_interactions.z2 IS 'Z position of Charge2 in meters (copied from Charges.PositionZ)';
COMMENT ON COLUMN charge_interactions.coulomb_k IS 'Coulomb''s constant: 8.99×10⁹ N·m²·C⁻². Stored per-row so the formula is self-contained.';

-- ----------------------------------------------------------------------------
-- ForceVectors: Table: ForceVectors — unit vector and full Cartesian force components for each ChargeInteraction. FX, FY, FZ decompose the scalar ForceMagnitude along the displacement direction. Force on Charge1 due to Charge2: attractive → pulls C1 toward C2 (−r̂); repulsive → pushes C1 away from C2 (+r̂). Position and interaction values are stored directly (denormalized) so all components compute as pure calculated fields.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS force_vectors (
  force_vector_id                     TEXT                 PRIMARY KEY          -- Unique identifier (mirrors InteractionId)
);
ALTER TABLE force_vectors ADD COLUMN IF NOT EXISTS interaction_id TEXT;                             -- FK → ChargeInteractions.InteractionId
ALTER TABLE force_vectors ADD COLUMN IF NOT EXISTS force_magnitude_raw NUMERIC;                     -- Scalar force magnitude in Newtons (copied from ChargeInteractions.ForceMagnitude)
ALTER TABLE force_vectors ADD COLUMN IF NOT EXISTS dx NUMERIC;                                      -- ΔX = X2 − X1 in meters (copied from ChargeInteractions.DeltaX)
ALTER TABLE force_vectors ADD COLUMN IF NOT EXISTS dy NUMERIC;                                      -- ΔY = Y2 − Y1 in meters (copied from ChargeInteractions.DeltaY)
ALTER TABLE force_vectors ADD COLUMN IF NOT EXISTS dz NUMERIC;                                      -- ΔZ = Z2 − Z1 in meters (copied from ChargeInteractions.DeltaZ)
ALTER TABLE force_vectors ADD COLUMN IF NOT EXISTS dist_raw NUMERIC;                                -- Separation distance r in meters (copied from ChargeInteractions.DistanceMeters)
ALTER TABLE force_vectors ADD COLUMN IF NOT EXISTS is_attractive_raw BOOLEAN;                       -- Attraction flag (copied from ChargeInteractions.IsAttractive)
COMMENT ON TABLE force_vectors IS 'Table: ForceVectors — unit vector and full Cartesian force components for each ChargeInteraction. FX, FY, FZ decompose the scalar ForceMagnitude along the displacement direction. Force on Charge1 due to Charge2: attractive → pulls C1 toward C2 (−r̂); repulsive → pushes C1 away from C2 (+r̂). Position and interaction values are stored directly (denormalized) so all components compute as pure calculated fields.';
COMMENT ON COLUMN force_vectors.force_vector_id IS 'Unique identifier (mirrors InteractionId)';
COMMENT ON COLUMN force_vectors.interaction_id IS 'FK → ChargeInteractions.InteractionId';
COMMENT ON COLUMN force_vectors.force_magnitude_raw IS 'Scalar force magnitude in Newtons (copied from ChargeInteractions.ForceMagnitude)';
COMMENT ON COLUMN force_vectors.dx IS 'ΔX = X2 − X1 in meters (copied from ChargeInteractions.DeltaX)';
COMMENT ON COLUMN force_vectors.dy IS 'ΔY = Y2 − Y1 in meters (copied from ChargeInteractions.DeltaY)';
COMMENT ON COLUMN force_vectors.dz IS 'ΔZ = Z2 − Z1 in meters (copied from ChargeInteractions.DeltaZ)';
COMMENT ON COLUMN force_vectors.dist_raw IS 'Separation distance r in meters (copied from ChargeInteractions.DistanceMeters)';
COMMENT ON COLUMN force_vectors.is_attractive_raw IS 'Attraction flag (copied from ChargeInteractions.IsAttractive)';

-- ----------------------------------------------------------------------------
-- ElectricFieldPoints: Table: ElectricFieldPoints — observation points in space at which the electric field contribution of a single source Charge is evaluated. E = k·q/r² pointing away from positive sources. One row per (ObservationPoint, SourceCharge) pair. Source charge and position values stored directly (denormalized) so EX, EY, EZ compute as pure calculated fields.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS electric_field_points (
  field_point_id                      TEXT                 PRIMARY KEY          -- Unique identifier
);
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS system_id TEXT;                          -- FK → Systems.SystemId
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS source_charge_id TEXT;                   -- FK → Charges.ChargeId — the charge creating this field contribution
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS source_charge_name TEXT;                 -- Human label of source charge (copied from Charges.Name)
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS observation_label TEXT;                  -- Human label for the observation point (midpoint, centroid, etc.)
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS obs_x NUMERIC;                           -- Observation point X coordinate in meters
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS obs_y NUMERIC;                           -- Observation point Y coordinate in meters
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS obs_z NUMERIC;                           -- Observation point Z coordinate in meters
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS coulomb_k NUMERIC;                       -- Coulomb's constant per-row (8.99×10⁹ N·m²·C⁻²)
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS source_q NUMERIC;                        -- Charge value of source charge in Coulombs (copied from Charges.ChargeValue)
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS src_x NUMERIC;                           -- X position of source charge in meters (copied from Charges.PositionX)
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS src_y NUMERIC;                           -- Y position of source charge in meters (copied from Charges.PositionY)
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS src_z NUMERIC;                           -- Z position of source charge in meters (copied from Charges.PositionZ)
COMMENT ON TABLE electric_field_points IS 'Table: ElectricFieldPoints — observation points in space at which the electric field contribution of a single source Charge is evaluated. E = k·q/r² pointing away from positive sources. One row per (ObservationPoint, SourceCharge) pair. Source charge and position values stored directly (denormalized) so EX, EY, EZ compute as pure calculated fields.';
COMMENT ON COLUMN electric_field_points.field_point_id IS 'Unique identifier';
COMMENT ON COLUMN electric_field_points.system_id IS 'FK → Systems.SystemId';
COMMENT ON COLUMN electric_field_points.source_charge_id IS 'FK → Charges.ChargeId — the charge creating this field contribution';
COMMENT ON COLUMN electric_field_points.source_charge_name IS 'Human label of source charge (copied from Charges.Name)';
COMMENT ON COLUMN electric_field_points.observation_label IS 'Human label for the observation point (midpoint, centroid, etc.)';
COMMENT ON COLUMN electric_field_points.obs_x IS 'Observation point X coordinate in meters';
COMMENT ON COLUMN electric_field_points.obs_y IS 'Observation point Y coordinate in meters';
COMMENT ON COLUMN electric_field_points.obs_z IS 'Observation point Z coordinate in meters';
COMMENT ON COLUMN electric_field_points.coulomb_k IS 'Coulomb''s constant per-row (8.99×10⁹ N·m²·C⁻²)';
COMMENT ON COLUMN electric_field_points.source_q IS 'Charge value of source charge in Coulombs (copied from Charges.ChargeValue)';
COMMENT ON COLUMN electric_field_points.src_x IS 'X position of source charge in meters (copied from Charges.PositionX)';
COMMENT ON COLUMN electric_field_points.src_y IS 'Y position of source charge in meters (copied from Charges.PositionY)';
COMMENT ON COLUMN electric_field_points.src_z IS 'Z position of source charge in meters (copied from Charges.PositionZ)';

-- ----------------------------------------------------------------------------
-- InvariantChecks: Table: InvariantChecks — one row per algebraic invariant that the Coulomb's Law DAG must satisfy. These are the model's built-in correctness witnesses.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS invariant_checks (
  invariant_id                        TEXT                 PRIMARY KEY          -- Unique identifier
);
ALTER TABLE invariant_checks ADD COLUMN IF NOT EXISTS algebraic_statement TEXT;                     -- The mathematical identity being checked
ALTER TABLE invariant_checks ADD COLUMN IF NOT EXISTS natural_language TEXT;                        -- Plain English: what must be true?
ALTER TABLE invariant_checks ADD COLUMN IF NOT EXISTS physics_law TEXT;                             -- Which physics principle this invariant encodes
ALTER TABLE invariant_checks ADD COLUMN IF NOT EXISTS severity TEXT;                                -- critical | warning | informational
COMMENT ON TABLE invariant_checks IS 'Table: InvariantChecks — one row per algebraic invariant that the Coulomb''s Law DAG must satisfy. These are the model''s built-in correctness witnesses.';
COMMENT ON COLUMN invariant_checks.invariant_id IS 'Unique identifier';
COMMENT ON COLUMN invariant_checks.algebraic_statement IS 'The mathematical identity being checked';
COMMENT ON COLUMN invariant_checks.natural_language IS 'Plain English: what must be true?';
COMMENT ON COLUMN invariant_checks.physics_law IS 'Which physics principle this invariant encodes';
COMMENT ON COLUMN invariant_checks.severity IS 'critical | warning | informational';

-- ----------------------------------------------------------------------------
-- SystemSummary: Table: SystemSummary — one row per system, aggregating all interactions and field points. The model witnesses its own state: total force, dominant pair, net charge, field at midpoints.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS system_summary (
  summary_id                          TEXT                 PRIMARY KEY          -- Unique identifier (mirrors SystemId)
);
ALTER TABLE system_summary ADD COLUMN IF NOT EXISTS system_id TEXT;                                 -- FK → Systems.SystemId
COMMENT ON TABLE system_summary IS 'Table: SystemSummary — one row per system, aggregating all interactions and field points. The model witnesses its own state: total force, dominant pair, net charge, field at midpoints.';
COMMENT ON COLUMN system_summary.summary_id IS 'Unique identifier (mirrors SystemId)';
COMMENT ON COLUMN system_summary.system_id IS 'FK → Systems.SystemId';

-- ============================================================================
-- FK INDEXES - Performance only, always applied
-- ============================================================================

-- Charges
CREATE INDEX IF NOT EXISTS idx_charges_system_id ON charges (system_id);
CREATE INDEX IF NOT EXISTS idx_charges_particle_id ON charges (particle_id);

-- SystemSummary
CREATE INDEX IF NOT EXISTS idx_system_summary_system_id ON system_summary (system_id);

-- 3 FK index(es) declared.
