-- ============================================================================
-- CREATE FUNCTIONS - Calculation functions for lookup/calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- ============================================================================


-- Disable body validation so LANGUAGE sql functions can forward-reference
-- each other within this file. (pg_dump does the same thing for the same
-- reason.) Without this, SQL functions parse-check at CREATE time and fail
-- on the first forward call site; plpgsql didn't, which is how this file
-- ever worked. Dependency order is still enforced at EXECUTION time.
SET check_function_bodies = off;

-- ============================================================================
-- LOOKUP FUNCTIONS
-- These functions perform lookups via foreign key relationships
-- ============================================================================

-- calc_policies_name
-- Field: Policies.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_policies_name(p_policy_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(policy_id, '') FROM policies WHERE policy_id = p_policy_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_policies_count_of_covered_claimants
-- Field: Policies.CountOfCoveredClaimants
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_policies_count_of_covered_claimants(p_policy_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM claimants WHERE policy = (SELECT NULLIF(policy_id, '') FROM policies WHERE policy_id = p_policy_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_claimants_policy_is_active
-- Field: Claimants.PolicyIsActive
-- Type: lookup | DataType: boolean | Returns: BOOLEAN
-- Lookup: IsActive from related Policies


CREATE OR REPLACE FUNCTION calc_claimants_policy_is_active(p_claimant_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT is_active::boolean FROM policies WHERE policy_id = (SELECT policy FROM claimants WHERE claimant_id = p_claimant_id));
$$ LANGUAGE sql STABLE;

-- get_policies_policyholder_name
-- Helper function: Get PolicyholderName from Policies by PolicyId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_policies_policyholder_name(p_policy_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT policyholder_name FROM policies WHERE policy_id = p_policy_id);
$$ LANGUAGE sql STABLE;

-- get_policies_is_active
-- Helper function: Get IsActive from Policies by PolicyId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_policies_is_active(p_policy_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT is_active FROM policies WHERE policy_id = p_policy_id);
$$ LANGUAGE sql STABLE;

-- calc_claimants_name
-- Field: Claimants.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_claimants_name(p_claimant_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(claimant_name, '') FROM claimants WHERE claimant_id = p_claimant_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_claimants_count_of_incidents
-- Field: Claimants.CountOfIncidents
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_claimants_count_of_incidents(p_claimant_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM incidents WHERE claimant = (SELECT NULLIF(claimant_id, '') FROM claimants WHERE claimant_id = p_claimant_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_claimants_is_high_risk
-- Field: Claimants.IsHighRisk
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_claimants_is_high_risk(p_claimant_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((calc_claimants_count_of_incidents(p_claimant_id))::NUMERIC > 2)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_incidents_incident_claimant_name
-- Field: Incidents.IncidentClaimantName
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: ClaimantName from related Claimants


CREATE OR REPLACE FUNCTION calc_incidents_incident_claimant_name(p_incident_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT claimant_name::text FROM claimants WHERE claimant_id = (SELECT claimant FROM incidents WHERE incident_id = p_incident_id));
$$ LANGUAGE sql STABLE;

-- get_claimants_claimant_name
-- Helper function: Get ClaimantName from Claimants by ClaimantId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_claimants_claimant_name(p_claimant_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT claimant_name FROM claimants WHERE claimant_id = p_claimant_id);
$$ LANGUAGE sql STABLE;

-- get_claimants_favorite_color
-- Helper function: Get FavoriteColor from Claimants by ClaimantId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_claimants_favorite_color(p_claimant_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT favorite_color FROM claimants WHERE claimant_id = p_claimant_id);
$$ LANGUAGE sql STABLE;

-- get_claimants_policy
-- Helper function: Get Policy from Claimants by ClaimantId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_claimants_policy(p_claimant_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT policy FROM claimants WHERE claimant_id = p_claimant_id);
$$ LANGUAGE sql STABLE;

-- calc_incidents_name
-- Field: Incidents.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_incidents_name(p_incident_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(incident_id, '') FROM incidents WHERE incident_id = p_incident_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_claims_incident_claimant
-- Field: Claims.IncidentClaimant
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: Claimant from related Incidents


CREATE OR REPLACE FUNCTION calc_claims_incident_claimant(p_claim_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT claimant::text FROM incidents WHERE incident_id = (SELECT incident FROM claims WHERE claim_id = p_claim_id));
$$ LANGUAGE sql STABLE;

-- calc_claims_incident_claimant_policy_active
-- Field: Claims.IncidentClaimantPolicyActive
-- Type: lookup | DataType: boolean | Returns: BOOLEAN
-- Lookup: PolicyIsActive from related Claimants


CREATE OR REPLACE FUNCTION calc_claims_incident_claimant_policy_active(p_claim_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT calc_claimants_policy_is_active(calc_claims_incident_claimant(p_claim_id));
$$ LANGUAGE sql STABLE;

-- calc_claims_additional_claimant_policy_active
-- Field: Claims.AdditionalClaimantPolicyActive
-- Type: lookup | DataType: boolean | Returns: BOOLEAN
-- Lookup: PolicyIsActive from related Claimants


CREATE OR REPLACE FUNCTION calc_claims_additional_claimant_policy_active(p_claim_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT calc_claimants_policy_is_active((SELECT additional_claimant FROM claims WHERE claim_id = p_claim_id));
$$ LANGUAGE sql STABLE;

-- calc_claims_additional_claimant_favorite_color
-- Field: Claims.AdditionalClaimantFavoriteColor
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: FavoriteColor from related Claimants


CREATE OR REPLACE FUNCTION calc_claims_additional_claimant_favorite_color(p_claim_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT favorite_color::text FROM claimants WHERE claimant_id = (SELECT additional_claimant FROM claims WHERE claim_id = p_claim_id));
$$ LANGUAGE sql STABLE;

-- calc_claims_claimant_of_record_incident_count
-- Field: Claims.ClaimantOfRecordIncidentCount
-- Type: lookup | DataType: integer | Returns: INTEGER
-- Lookup: CountOfIncidents from related Claimants


CREATE OR REPLACE FUNCTION calc_claims_claimant_of_record_incident_count(p_claim_id TEXT)
RETURNS INTEGER AS $$
  SELECT calc_claimants_count_of_incidents(calc_claims_claimant_of_record(p_claim_id));
$$ LANGUAGE sql STABLE;

-- calc_claims_claimant_of_record_is_high_risk
-- Field: Claims.ClaimantOfRecordIsHighRisk
-- Type: lookup | DataType: boolean | Returns: BOOLEAN
-- Lookup: IsHighRisk from related Claimants


CREATE OR REPLACE FUNCTION calc_claims_claimant_of_record_is_high_risk(p_claim_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT calc_claimants_is_high_risk(calc_claims_claimant_of_record(p_claim_id));
$$ LANGUAGE sql STABLE;

-- get_incidents_incident_description
-- Helper function: Get IncidentDescription from Incidents by IncidentId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_incidents_incident_description(p_incident_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT incident_description FROM incidents WHERE incident_id = p_incident_id);
$$ LANGUAGE sql STABLE;

-- get_incidents_claimant
-- Helper function: Get Claimant from Incidents by IncidentId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_incidents_claimant(p_incident_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT claimant FROM incidents WHERE incident_id = p_incident_id);
$$ LANGUAGE sql STABLE;

-- calc_claims_name
-- Field: Claims.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_claims_name(p_claim_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(claim_id, '') FROM claims WHERE claim_id = p_claim_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_claims_references_incident
-- Field: Claims.ReferencesIncident
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_claims_references_incident(p_claim_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((SELECT NULLIF(incident, '') FROM claims WHERE claim_id = p_claim_id) IS NOT NULL)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_claims_has_additional_claimant
-- Field: Claims.HasAdditionalClaimant
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_claims_has_additional_claimant(p_claim_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((SELECT NULLIF(additional_claimant, '') FROM claims WHERE claim_id = p_claim_id) IS NOT NULL)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_claims_claimant_of_record
-- Field: Claims.ClaimantOfRecord
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_claims_claimant_of_record(p_claim_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN calc_claims_has_additional_claimant(p_claim_id) THEN ((SELECT NULLIF(additional_claimant, '') FROM claims WHERE claim_id = p_claim_id))::text ELSE (calc_claims_incident_claimant(p_claim_id))::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_claims_is_valid
-- Field: Claims.IsValid
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_claims_is_valid(p_claim_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((calc_claims_references_incident(p_claim_id) AND (calc_claims_incident_claimant_policy_active(p_claim_id) OR calc_claims_additional_claimant_policy_active(p_claim_id)) AND (NOT (calc_claims_has_additional_claimant(p_claim_id)) OR LOWER(calc_claims_additional_claimant_favorite_color(p_claim_id)) = 'red') AND NOT (calc_claims_claimant_of_record_is_high_risk(p_claim_id))))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_claims_validity_deciding_factor
-- Field: Claims.ValidityDecidingFactor
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_claims_validity_deciding_factor(p_claim_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN calc_claims_is_valid(p_claim_id) THEN ('Valid — all conditions met')::text ELSE (CASE WHEN NOT (calc_claims_references_incident(p_claim_id)) THEN ('No incident referenced')::text ELSE (CASE WHEN NOT ((calc_claims_incident_claimant_policy_active(p_claim_id) OR calc_claims_additional_claimant_policy_active(p_claim_id))) THEN ('No active policy on incident claimant or additional claimant')::text ELSE (CASE WHEN (calc_claims_has_additional_claimant(p_claim_id) AND LOWER(calc_claims_additional_claimant_favorite_color(p_claim_id)) <> 'red') THEN ('Additional claimant''s favorite color is not red')::text ELSE (CASE WHEN calc_claims_claimant_of_record_is_high_risk(p_claim_id) THEN ('Claimant of record is high-risk (DR-2)')::text ELSE ('Undetermined')::text END)::text END)::text END)::text END)::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_claims_is_approvable
-- Field: Claims.IsApprovable
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_claims_is_approvable(p_claim_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((calc_claims_is_valid(p_claim_id) AND NOT (COALESCE((SELECT is_flagged_for_review FROM claims WHERE claim_id = p_claim_id), FALSE))))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_claims_approvability_deciding_factor
-- Field: Claims.ApprovabilityDecidingFactor
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_claims_approvability_deciding_factor(p_claim_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN calc_claims_is_approvable(p_claim_id) THEN ('Approvable')::text ELSE (CASE WHEN NOT (calc_claims_is_valid(p_claim_id)) THEN ('Not approvable — claim is not valid')::text ELSE (CASE WHEN COALESCE((SELECT is_flagged_for_review FROM claims WHERE claim_id = p_claim_id), FALSE) THEN ('Valid, but flagged for review')::text ELSE ('Undetermined')::text END)::text END)::text END)::text;
$$ LANGUAGE sql STABLE;

-- ============================================================================
-- MANY-SIDE RELATIONSHIP FUNCTIONS
-- These functions aggregate child records for many-side relationships
-- ============================================================================

-- ============================================================================
-- INVERSE RELATIONSHIP FUNCTIONS
-- These functions perform reverse FK lookups for inverse-side relationships
-- ============================================================================

