#!/usr/bin/env bash
# ============================================================================
# demo - RESET the dev database from the rulebook
# ============================================================================
# Generated by rulebook-to-postgres tool.
#
# DESTRUCTIVE. LOCALHOST ONLY. This drops and rebuilds the database so it
# mirrors the rulebook exactly — "the loop". Any row not in the rulebook
# is gone. It is NOT a migration and must never be pointed at staging,
# beta or production.
#
# To move a non-dev database forward, run update-effortless-schema.sql
# (rebuilds views/functions/RLS from the rulebook, touches no row data)
# plus any additive table/column migration.
#
# Two responsibilities: install magic-links auth, then run all
# NN[b]?-*.sql files in lex order. Skips *.sql.disabled.
#
# THIS IS THE DEV LOOP (per plan 04). Re-running against a populated
# DB should be safe — every file is meant to be idempotent. If it
# isn't, fix the file, not this script.
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_CONN="postgresql://postgres@localhost:5432/demo"
DATABASE_URL="${DATABASE_URL:-${1:-$DEFAULT_CONN}}"

# ----------------------------------------------------------------------
# Plan 04 §8: bases-URL refusal (defense in depth).
# bases.effortlessapi.com is migration-only. Any rebuild against it
# would drop tables and lose data. Use postgres/apply-migration.sh
# instead. This check has no escape hatch by design.
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# Localhost-only guard. This script is destructive by design, so it
# refuses any host that isn't clearly local. Set ERB_ALLOW_REMOTE_RESET=1
# only if you genuinely intend to wipe a remote database.
# ----------------------------------------------------------------------
DB_HOST="$(printf '%s' "$DATABASE_URL" | sed -E 's|^[^:]+://||; s|^[^@]*@||; s|[:/].*$||')"
case "${DB_HOST:-localhost}" in
    localhost|127.0.0.1|::1|host.docker.internal|"") ;;
    *)
        if [ "${ERB_ALLOW_REMOTE_RESET:-}" != "1" ]; then
            echo "refusing to reset a non-local database: $DB_HOST" >&2
            echo "this script DROPS AND REBUILDS the database from the rulebook." >&2
            echo "to move a remote db forward, run update-effortless-schema.sql" >&2
            echo "plus an additive migration — not this script." >&2
            exit 2
        fi
        echo "[reset] WARNING: ERB_ALLOW_REMOTE_RESET=1 — resetting REMOTE $DB_HOST" >&2
        ;;
esac

if echo "$DATABASE_URL" | grep -qi 'bases\.effortlessapi\.com' ; then
    echo "refusing to run reset-rulebook-db.sh against bases." >&2
    echo "bases is migration-only — see CLAUDE.md \"Bases is migration-only\"" >&2
    echo "use postgres/apply-migration.sh postgres/migrations/NNNN-….sql" >&2
    exit 2
fi
if [ -n "${BASES_DATABASE_URL:-}" ] && [ "$DATABASE_URL" = "$BASES_DATABASE_URL" ]; then
    echo "refusing to run reset-rulebook-db.sh: DATABASE_URL == BASES_DATABASE_URL" >&2
    echo "bases is migration-only — use postgres/apply-migration.sh" >&2
    exit 2
fi

echo "[reset] target: $DATABASE_URL"

# ----------------------------------------------------------------------
# 1. Always (re-)install magic-links auth. Idempotent → safe to repeat.
# ----------------------------------------------------------------------
if [ -f "${SCRIPT_DIR}/install-magic-links.sql" ]; then
    echo "[reset] [RUN]  install-magic-links.sql"
    psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "${SCRIPT_DIR}/install-magic-links.sql"
else
    echo "[reset] note: install-magic-links.sql not present — skipping auth install"
    echo "[reset]       fetch from https://magiclink.effortlessapi.com/install-magic-links/v1.sql"
fi

# ----------------------------------------------------------------------
# 2. Run all NN[b]?-*.sql files in lex order. Skip *.sql.disabled.
# ----------------------------------------------------------------------
shopt -s nullglob
FILES_RUN=()
FILES_SKIP=()
for f in "${SCRIPT_DIR}"/[0-9][0-9]*-*.sql "${SCRIPT_DIR}"/[0-9][0-9]*-*.sql.disabled; do
    [ -f "$f" ] || continue
    base=$(basename "$f")
    if [[ "$base" == *.disabled ]]; then
        echo "[reset] [SKIP] $base"
        FILES_SKIP+=("$base")
        continue
    fi
    # 99-fk-constraints.sql — FK enforcement is opt-in. Demos must never
    # fail on FK violations; the rulebook still documents the relationships
    # and 01-drop-and-create-tables.sql installs the FK indexes inline.
    if [[ "$base" == "99-fk-constraints.sql" && "${EFFORTLESS_ENFORCE_FKS:-false}" != "true" ]]; then
        echo "[reset] [SKIP] $base (set EFFORTLESS_ENFORCE_FKS=true to apply FK constraints)"
        FILES_SKIP+=("$base")
        continue
    fi
    echo "[reset] [RUN]  $base"
    if [[ "$base" == *b-* ]]; then
        # customize files (NNb-*) tolerate per-row errors
        psql "$DATABASE_URL" -f "$f"
    elif [[ "$base" == "05-insert-data.sql" ]]; then
        psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$f"
    else
        psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$f"
    fi
    FILES_RUN+=("$base")
done

# ----------------------------------------------------------------------
# 3. function-overrides/*.sql (per-function tweaks; errors non-fatal).
#    Two-pass: non-policy files first, then policy__* files (policies
#    often reference custom functions).
# ----------------------------------------------------------------------
run_override() {
    local sql_file="$1"
    local base; base=$(basename "$sql_file")
    if [[ "$base" == *.disabled ]]; then
        echo "[reset] [SKIP] function-overrides/$base"
        return 0
    fi
    echo "[reset] [RUN]  function-overrides/$base"
    psql "$DATABASE_URL" -f "$sql_file" || echo "[reset] [WARN] $base failed (non-fatal)"
}
if compgen -G "${SCRIPT_DIR}/function-overrides/*.sql" > /dev/null 2>&1; then
    for sql_file in "${SCRIPT_DIR}/function-overrides/"*.sql; do
        base=$(basename "$sql_file")
        [[ "$base" == policy__* ]] && continue
        run_override "$sql_file"
    done
    for sql_file in "${SCRIPT_DIR}/function-overrides/"policy__*.sql; do
        [[ -f "$sql_file" ]] || continue
        run_override "$sql_file"
    done
fi

# ----------------------------------------------------------------------
# 4. Plan 04 §9: write postgres/.applied-manifest.json so tooling can
#    compare to .build-manifest.json and detect drift.
# ----------------------------------------------------------------------
APPLIED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
MANIFEST="${SCRIPT_DIR}/.applied-manifest.json"
{
    printf '{\n'
    printf '  "applied_at": "%s",\n' "$APPLIED_AT"
    printf '  "target": "%s",\n' "$DATABASE_URL"
    printf '  "files_run": ['
    sep=''
    for f in "${FILES_RUN[@]:-}"; do
        [ -z "$f" ] && continue
        printf '%s"%s"' "$sep" "$f"
        sep=','
    done
    printf '],\n'
    printf '  "files_skipped": ['
    sep=''
    for f in "${FILES_SKIP[@]:-}"; do
        [ -z "$f" ] && continue
        printf '%s"%s"' "$sep" "$f"
        sep=','
    done
    printf ']\n'
    printf '}\n'
} > "$MANIFEST"

echo "[reset] complete (manifest: .applied-manifest.json)"
