#!/bin/bash
# edit-rulebook.local.sh -- project-local fork of the GENERATED edit-rulebook.sh.
#
# The generated script hardcodes a fixed container name and ports
# (effortless-rulebook-editor / 42441 / 42442 / 5442) shared across EVERY
# project using this transpiler, so two projects running it at once fight
# over the same container name and ports. This fork gives
# traffic-ticket-contest its own container name and ports so it can run
# alongside other rulebook-editor instances without taking them down.
#
# Regenerated by: NOT auto-regenerated -- this file is hand-maintained,
# unlike edit-rulebook.sh (which the transpiler overwrites on every build).
# If edit-rulebook.sh changes upstream, re-diff and reapply the port/name
# changes here.
#
# Dockerfile and its sibling files (container-entrypoint.sh, boot-server.js,
# effortless.editor.json) live at docker/Dockerfile relative to THIS script's
# own folder.
#
# Ports: 42451 (API), 42452 (UI), 5452 (Postgres).
#
# Refresh your browser after editing traffic-ticket-contest-rulebook.json -- the container's
# filesystem watcher detects the change, re-runs `effortless build`, and
# restarts the API + UI automatically.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

DOCKERFILE_PATH="docker/Dockerfile"
EXTERNAL_SRC_MOUNTED=
EXTERNAL_SRC_HOST_PATH=""

# On Windows Git Bash (MSYS), MSYS silently rewrites POSIX-looking paths in
# command arguments before docker.exe ever sees them. Applied blindly to a
# `docker run -v SRC:DST` argument, it mangles the CONTAINER-side path too
# (observed in practice: "/app/effortless-rulebook" became
# "\Program Files\Git\app\effortless-rulebook"), so the rulebook folder never
# actually appears inside the container at all. Disabling MSYS's path
# conversion for the docker commands below and converting the HOST-side path
# ourselves (native Windows path via cygpath) fixes this without affecting
# macOS/Linux, where none of this applies (MSYSTEM is unset there).
if [ -n "${MSYSTEM:-}" ] && command -v cygpath >/dev/null 2>&1; then
  export MSYS_NO_PATHCONV=1
  to_native_path() { cygpath -w "$1"; }
else
  to_native_path() { printf '%s' "$1"; }
fi

IMAGE_NAME="effortless-rulebook-editor-traffic-ticket-contest"
CONTAINER_NAME="effortless-rulebook-editor-traffic-ticket-contest"
API_PORT=42451
UI_PORT=42452
PG_PORT=5452

# Stop our own previous container, AND whatever else is squatting on these
# three ports (e.g. a stale instance of THIS project's container from a
# previous run). Unlike the shared generated script, these ports are
# project-pinned, so we only ever clear instances of our own container name.
for PORT in "$API_PORT" "$UI_PORT" "$PG_PORT"; do
  STALE_CIDS=$(docker ps -q --filter "publish=$PORT" --filter "name=$CONTAINER_NAME")
  [ -n "$STALE_CIDS" ] && docker rm -f $STALE_CIDS >/dev/null 2>&1 || true
done
docker rm -f "$CONTAINER_NAME" >/dev/null 2>&1 || true

# Build only if the image doesn't exist yet. Run ./edit-rulebook.local.sh --rebuild
# to force a fresh image build (e.g. after pulling a new Dockerfile).
DOCKERFILE_DIR="$(dirname "$DOCKERFILE_PATH")"
if [ "${1:-}" = "--rebuild" ] || ! docker image inspect "$IMAGE_NAME" >/dev/null 2>&1; then
  echo "Building $IMAGE_NAME image..."
  docker build -t "$IMAGE_NAME" -f "$DOCKERFILE_PATH" "$DOCKERFILE_DIR"
fi

RULEBOOK_DIR_NATIVE="$(to_native_path "$(pwd)")"
SSOTME_DIR_NATIVE="$(to_native_path "$HOME/.ssotme")"

DOCKER_RUN_ARGS=(
  -d
  --name "$CONTAINER_NAME"
  -p "$API_PORT:5177"
  -p "$UI_PORT:5174"
  -p "$PG_PORT:5432"
  -v "$RULEBOOK_DIR_NATIVE:/app/effortless-rulebook"
  -v "$SSOTME_DIR_NATIVE:/root/.ssotme-ro:ro"
)

# Second bind-mount: only when -p pathToExternalSrc=... was passed at
# generation time. Otherwise the container keeps ALL of its scratch/
# generated-code state purely internal (see container-entrypoint.sh's
# effortless-root symlink target) -- nothing lands on the host, nothing
# needs a .gitignore entry.
if [ -n "$EXTERNAL_SRC_MOUNTED" ]; then
  mkdir -p "$EXTERNAL_SRC_HOST_PATH"
  # .gitignore the whole external-src folder -- it's disposable container
  # scratch state (effortless.json + every generated file), not something
  # to commit.
  if [ ! -f "$EXTERNAL_SRC_HOST_PATH/.gitignore" ]; then
    printf '*\n' > "$EXTERNAL_SRC_HOST_PATH/.gitignore"
  fi
  EXTERNAL_SRC_NATIVE="$(to_native_path "$(cd "$EXTERNAL_SRC_HOST_PATH" && pwd)")"
  DOCKER_RUN_ARGS+=( -v "$EXTERNAL_SRC_NATIVE:/app/effortless-editor-tmp" )
  DOCKER_RUN_ARGS+=( -e "EFFORTLESS_EDITOR_TEMPDIR_MOUNTED=1" )
fi

# Forward the host's Anthropic key into the container so the generated API's
# chat endpoint (POST /api/chat, see chatbot.js) can reach Claude.
ENV_FILE="$(dirname "$0")/effortless.env"
if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
fi

if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
  DOCKER_RUN_ARGS+=( -e ANTHROPIC_API_KEY )
else
  echo "NOTE: ANTHROPIC_API_KEY is not set, so the admin portal's chat widget"
  echo "      will report itself unavailable. Everything else runs normally."
  echo "      To enable it, create $ENV_FILE containing:"
  echo "          ANTHROPIC_API_KEY=sk-ant-..."
  echo "      (that filename is already gitignored), or export the variable"
  echo "      in the shell you run this script from."
fi

echo "Starting $CONTAINER_NAME container on project-pinned ports ($API_PORT, $UI_PORT, $PG_PORT)..."
docker run "${DOCKER_RUN_ARGS[@]}" "$IMAGE_NAME"

echo ""
echo "effortless-rulebook-editor (traffic-ticket-contest) is starting up."
echo "  API:  http://localhost:$API_PORT/api/state"
echo "  DOCS: http://localhost:$API_PORT/api/docs"
echo "                            (START HERE to build an app against this API: every"
echo "                            route, the read-snake_case/write-PascalCase rule, and"
echo "                            pointers to /api/rulespeak + /api/source. Derived from"
echo "                            the live route table, so it cannot go stale.)"
echo "  UI:   http://localhost:$UI_PORT   (shows a live boot/progress page immediately --"
echo "                            no need to wait before opening it; it hands off"
echo "                            to the real app automatically once ready, and has"
echo "                            its own Rebuild button + log view at any time)"
echo "  PG:   postgresql://postgres:postgres@localhost:$PG_PORT/effortless-rulebook"
echo "                            (for a host psql client / GUI tool -- this is the"
echo "                            ONLY supported way to inspect data directly; the"
echo "                            DB is reseeded from the rulebook on every rebuild)"
echo ""
echo "Edit traffic-ticket-contest-rulebook.json to trigger a rebuild -- the container watches"
echo "the file (and the UI's Rebuild button) and rebuilds automatically."
echo ""
echo "Following container logs now (Ctrl-C stops watching logs -- the container keeps running;"
echo "re-run this script, or 'docker logs -f $CONTAINER_NAME', to watch again)..."
echo ""
exec docker logs -f "$CONTAINER_NAME"
