-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Views: 36
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Drop pass: every rulebook-owned view, reverse iteration order, CASCADE.
-- The rulebook is HEAD — the surviving view set must mirror it exactly.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_lower_bound_validity_at_snapshot CASCADE;
DROP VIEW IF EXISTS vw_temporal_snapshots CASCADE;
DROP VIEW IF EXISTS vw_answer_key CASCADE;
DROP VIEW IF EXISTS vw_citation_links CASCADE;
DROP VIEW IF EXISTS vw_proof_obligations CASCADE;
DROP VIEW IF EXISTS vw_conjectures CASCADE;
DROP VIEW IF EXISTS vw_mirror_contract CASCADE;
DROP VIEW IF EXISTS vw_lemmas CASCADE;
DROP VIEW IF EXISTS vw_source_references CASCADE;
DROP VIEW IF EXISTS vw_semantic_route_steps CASCADE;
DROP VIEW IF EXISTS vw_semantic_routes CASCADE;
DROP VIEW IF EXISTS vw_semantic_bridges CASCADE;
DROP VIEW IF EXISTS vw_golod_shafarevich_criteria CASCADE;
DROP VIEW IF EXISTS vw_projected_short_vectors CASCADE;
DROP VIEW IF EXISTS vw_planar_projections CASCADE;
DROP VIEW IF EXISTS vw_gram_matrices CASCADE;
DROP VIEW IF EXISTS vw_minkowski_embeddings CASCADE;
DROP VIEW IF EXISTS vw_field_embeddings CASCADE;
DROP VIEW IF EXISTS vw_metrics CASCADE;
DROP VIEW IF EXISTS vw_theorems CASCADE;
DROP VIEW IF EXISTS vw_asymptotic_lower_bounds CASCADE;
DROP VIEW IF EXISTS vw_asymptotic_functions CASCADE;
DROP VIEW IF EXISTS vw_growth_sequences CASCADE;
DROP VIEW IF EXISTS vw_construction_instances CASCADE;
DROP VIEW IF EXISTS vw_construction_families CASCADE;
DROP VIEW IF EXISTS vw_short_vectors CASCADE;
DROP VIEW IF EXISTS vw_minkowski_lattices CASCADE;
DROP VIEW IF EXISTS vw_prime_ideals CASCADE;
DROP VIEW IF EXISTS vw_number_fields CASCADE;
DROP VIEW IF EXISTS vw_unit_distance_graphs CASCADE;
DROP VIEW IF EXISTS vw_point_pairs CASCADE;
DROP VIEW IF EXISTS vw_point_set_members CASCADE;
DROP VIEW IF EXISTS vw_point_sets CASCADE;
DROP VIEW IF EXISTS vw_points CASCADE;
DROP VIEW IF EXISTS vw_contexts CASCADE;
DROP VIEW IF EXISTS vw_domains CASCADE;

-- ----------------------------------------------------------------------------
-- vw_domains: Table: Domains. Top-level mathematical neighborhoods used to group entities for navigation. Not load-bearing for computation — purely a tag.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_domains CASCADE;
CREATE VIEW vw_domains WITH (security_invoker = ON) AS
SELECT
  t.domain_id,
  calc_domains_name(t.domain_id) AS name,
  t.display_name,
  t.role_in_model,
  t.description
FROM domains t;

-- ----------------------------------------------------------------------------
-- vw_contexts: Table: Contexts. Mathematical worlds in which assertions are interpreted. Used as the valid-time context for facts (e.g. 'this lattice fact is valid in the Euclidean plane with standard metric').
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_contexts CASCADE;
CREATE VIEW vw_contexts WITH (security_invoker = ON) AS
SELECT
  t.context_id,
  calc_contexts_name(t.context_id) AS name,
  t.display_name,
  t.kind,
  t.assumptions_json,
  t.description
FROM contexts t;

-- ----------------------------------------------------------------------------
-- vw_points: Table: Points. A single point in R^2. Coordinates are raw; everything else lives on PointPairs / PointSets.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_points CASCADE;
CREATE VIEW vw_points WITH (security_invoker = ON) AS
SELECT
  t.point_id,
  calc_points_name(t.point_id) AS name,
  t.display_name,
  t.x,
  t.y,
  t.context                                                                     -- Which mathematical context the coordinates are interpreted in.
FROM points t;

-- ----------------------------------------------------------------------------
-- vw_point_sets: Table: PointSets. A finite configuration P ⊂ R^2. Aggregations count membership and unit-distance pairs; calculated fields derive density and exponent estimates. The Erdős unit-distance question lives on this table — 'how many unit pairs can n points have?' is literally `UnitDistancePairCount` for varying `PointCount`.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_point_sets CASCADE;
CREATE VIEW vw_point_sets WITH (security_invoker = ON) AS
SELECT
  t.point_set_id,
  calc_point_sets_name(t.point_set_id) AS name,
  t.display_name,
  t.description,
  t.members,
  t.pairs,
  calc_point_sets_point_count(t.point_set_id) AS point_count,                   -- n in U(n).
  calc_point_sets_unit_distance_pair_count(t.point_set_id) AS unit_distance_pair_count,-- e(G(P)) — the number of edges in the induced unit-distance graph.
  calc_point_sets_max_possible_edges(t.point_set_id) AS max_possible_edges,     -- n choose 2 — the trivial upper bound on UnitDistancePairCount.
  calc_point_sets_edge_density(t.point_set_id) AS edge_density,                 -- Fraction of point pairs that are unit pairs.
  calc_point_sets_density_exponent_estimate(t.point_set_id) AS density_exponent_estimate-- The exponent c such that UnitDistancePairCount ≈ PointCount^c. Lower bounds for U(n) are claims that this exponent is ≥ some target for arbitrarily large PointCount.
FROM point_sets t;

-- ----------------------------------------------------------------------------
-- vw_point_set_members: Table: PointSetMembers. Junction: which Points belong to which PointSet. Promoted to a first-class entity because membership is itself a fact that may carry context.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_point_set_members CASCADE;
CREATE VIEW vw_point_set_members WITH (security_invoker = ON) AS
SELECT
  t.point_set_member_id,
  calc_point_set_members_name(t.point_set_member_id) AS name,
  t.point_set,
  t.point
FROM point_set_members t;

-- ----------------------------------------------------------------------------
-- vw_point_pairs: Table: PointPairs. An ordered pair (PointA, PointB) drawn from the same PointSet. Every step the mathematician would name is here as its own column — DeltaX, DeltaXSquared, DistanceSquared, Distance, DistanceFromUnit, IsUnitDistance. The reader can audit each step.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_point_pairs CASCADE;
CREATE VIEW vw_point_pairs WITH (security_invoker = ON) AS
SELECT
  t.point_pair_id,
  calc_point_pairs_name(t.point_pair_id) AS name,
  t.point_set,
  t.point_a,
  t.point_b,
  calc_point_pairs_point_ax(t.point_pair_id) AS point_ax,                       -- Lookup of PointA.X.
  calc_point_pairs_point_ay(t.point_pair_id) AS point_ay,
  calc_point_pairs_point_bx(t.point_pair_id) AS point_bx,
  calc_point_pairs_point_by(t.point_pair_id) AS point_by,
  calc_point_pairs_delta_x(t.point_pair_id) AS delta_x,
  calc_point_pairs_delta_y(t.point_pair_id) AS delta_y,
  calc_point_pairs_delta_x_squared(t.point_pair_id) AS delta_x_squared,
  calc_point_pairs_delta_y_squared(t.point_pair_id) AS delta_y_squared,
  calc_point_pairs_distance_squared(t.point_pair_id) AS distance_squared,       -- Pythagoras, made explicit. Promoted because every downstream check uses it directly.
  calc_point_pairs_distance(t.point_pair_id) AS distance,
  t.tolerance,                                                                  -- Numerical tolerance for the unit-distance check.
  calc_point_pairs_distance_from_unit(t.point_pair_id) AS distance_from_unit,
  calc_point_pairs_is_unit_distance(t.point_pair_id) AS is_unit_distance,       -- The unit-distance predicate — the entire problem turns on this boolean.
  t.description                                                                 -- Free-text annotation for this row.
FROM point_pairs t;

-- ----------------------------------------------------------------------------
-- vw_unit_distance_graphs: Table: UnitDistanceGraphs. The induced graph G(P) for a PointSet P. Has one row per PointSet that we choose to project into graph-form. Vertex count is the point count, edge count is the unit-distance pair count — these are not duplicated facts, they are lookups.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_unit_distance_graphs CASCADE;
CREATE VIEW vw_unit_distance_graphs WITH (security_invoker = ON) AS
SELECT
  t.unit_distance_graph_id,
  calc_unit_distance_graphs_name(t.unit_distance_graph_id) AS name,
  t.point_set,
  calc_unit_distance_graphs_vertex_count(t.unit_distance_graph_id) AS vertex_count,
  calc_unit_distance_graphs_edge_count(t.unit_distance_graph_id) AS edge_count,
  calc_unit_distance_graphs_max_possible_edges(t.unit_distance_graph_id) AS max_possible_edges,
  calc_unit_distance_graphs_edge_density(t.unit_distance_graph_id) AS edge_density,
  calc_unit_distance_graphs_density_exponent_estimate(t.unit_distance_graph_id) AS density_exponent_estimate-- Witness for the exponent in U(n) ≥ n^c, finite-sample.
FROM unit_distance_graphs t;

-- ----------------------------------------------------------------------------
-- vw_number_fields: Table: NumberFields. A finite extension K of Q. Discriminant, degree, class number, and signature are raw inputs — but IsTotallyReal, IsTotallyComplex, and SatisfiesGolodShafarevich are first-class calculated booleans on the same row, not separate property rows.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_number_fields CASCADE;
CREATE VIEW vw_number_fields WITH (security_invoker = ON) AS
SELECT
  t.number_field_id,
  calc_number_fields_name(t.number_field_id) AS name,
  t.display_name,
  t.defining_polynomial,
  t.degree,
  t.discriminant,
  t.class_number,
  t.signature_real_embeddings,                                                  -- r_1: number of real embeddings.
  t.signature_complex_embeddings,                                               -- r_2: number of complex-conjugate pairs.
  calc_number_fields_ambient_lattice_dimension(t.number_field_id) AS ambient_lattice_dimension,-- The R-dimension of the Minkowski embedding image.
  calc_number_fields_is_totally_real(t.number_field_id) AS is_totally_real,
  calc_number_fields_is_totally_complex(t.number_field_id) AS is_totally_complex,
  calc_number_fields_is_pid(t.number_field_id) AS is_pid,                       -- Ring of integers is a principal ideal domain iff class number is 1.
  t.prime_ideals,
  calc_number_fields_small_norm_prime_ideal_count(t.number_field_id) AS small_norm_prime_ideal_count,-- How many prime ideals fall below the small-norm threshold. Drives multiplicity in construction families.
  calc_number_fields_golod_shafarevich_passing_count(t.number_field_id) AS golod_shafarevich_passing_count,-- Aggregation count of GolodShafarevichCriteria rows for this field that satisfy the GS tower inequality. Used as the bridge from raw GS parameters to a per-field boolean.
  calc_number_fields_satisfies_golod_shafarevich(t.number_field_id) AS satisfies_golod_shafarevich,-- TRUE if some GolodShafarevichCriteria row for this field passes the tower inequality. This is the gate that determines whether the field is a candidate algebraic source for many short vectors.
  calc_number_fields_is_algebraic_source_candidate(t.number_field_id) AS is_algebraic_source_candidate,-- TRUE when the field both satisfies GS and has at least one small-norm prime ideal — the two-condition algebraic precondition for producing a Minkowski lattice with many short vectors.
  calc_number_fields_field_embedding_count(t.number_field_id) AS field_embedding_count,-- How many field embeddings (real or complex) are explicitly loaded for this field. Sanity check: should equal SignatureRealEmbeddings + SignatureComplexEmbeddings.
  calc_number_fields_field_embedding_count_matches_signature(t.number_field_id) AS field_embedding_count_matches_signature-- Read-time integrity check: did we load every embedding the signature claims to exist?
FROM number_fields t;

-- ----------------------------------------------------------------------------
-- vw_prime_ideals: Table: PrimeIdeals. A prime ideal in the ring of integers of a NumberField. Norm is raw; IsSmallNorm is a first-class calculated predicate that downstream aggregations consume.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_prime_ideals CASCADE;
CREATE VIEW vw_prime_ideals WITH (security_invoker = ON) AS
SELECT
  t.prime_ideal_id,
  calc_prime_ideals_name(t.prime_ideal_id) AS name,
  t.number_field,
  t.generator_description,
  t.norm,
  t.norm_threshold,                                                             -- Per-prime threshold for the 'small norm' classification.
  calc_prime_ideals_is_small_norm(t.prime_ideal_id) AS is_small_norm,
  t.splits_completely                                                           -- Whether the prime in Q splits completely in O_K. Nullable: null when splitting behavior has been named but not yet computed.
FROM prime_ideals t;

-- ----------------------------------------------------------------------------
-- vw_minkowski_lattices: Table: MinkowskiLattices. The image of O_K under the Minkowski embedding into R^(r_1 + 2*r_2). Carries Gram matrix as raw JSON (matrix algebra is not in scope for ERB formulas), but everything derivable from already-promoted quantities — Dimension, the determinant-equals-discriminant identity check — is a first-class field.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_minkowski_lattices CASCADE;
CREATE VIEW vw_minkowski_lattices WITH (security_invoker = ON) AS
SELECT
  t.minkowski_lattice_id,
  calc_minkowski_lattices_name(t.minkowski_lattice_id) AS name,
  t.number_field,
  calc_minkowski_lattices_dimension(t.minkowski_lattice_id) AS dimension,
  calc_minkowski_lattices_field_discriminant(t.minkowski_lattice_id) AS field_discriminant,
  t.determinant,
  calc_minkowski_lattices_determinant_squared(t.minkowski_lattice_id) AS determinant_squared,
  calc_minkowski_lattices_absolute_field_discriminant(t.minkowski_lattice_id) AS absolute_field_discriminant,
  calc_minkowski_lattices_determinant_squared_equals_discriminant(t.minkowski_lattice_id) AS determinant_squared_equals_discriminant,-- Classical identity: covolume(O_K)^2 = |disc(K)|. Promoted as a first-class sanity check the model verifies on read.
  t.gram_matrix_json,                                                           -- JSON-encoded Gram matrix. Matrix algebra is held opaque because ERB formulas are scalar; downstream substrates that support matrices may extend this.
  t.short_vector_threshold_squared,
  t.short_vectors,
  calc_minkowski_lattices_short_vector_count(t.minkowski_lattice_id) AS short_vector_count,
  calc_minkowski_lattices_source_field_degree(t.minkowski_lattice_id) AS source_field_degree,-- The degree [K:Q] of the source field, surfaced on the lattice for downstream chain checks.
  calc_minkowski_lattices_source_field_satisfies_golod_shafarevich(t.minkowski_lattice_id) AS source_field_satisfies_golod_shafarevich,-- The single most important upstream gate. TRUE means the field-side ingredient (GS tower) is satisfied — a necessary condition for the lattice to carry enough short vectors for a superlinear unit-distance construction.
  calc_minkowski_lattices_source_field_is_algebraic_source_candidate(t.minkowski_lattice_id) AS source_field_is_algebraic_source_candidate,
  t.projections,
  calc_minkowski_lattices_projection_count(t.minkowski_lattice_id) AS projection_count,-- How many distinct planar projections have been registered from this lattice.
  calc_minkowski_lattices_has_any_planar_projection(t.minkowski_lattice_id) AS has_any_planar_projection,-- TRUE if any planar projection has been registered — the geometry-side leg of the bridge from lattice to plane.
  calc_minkowski_lattices_is_load_bearing_for_unit_distance_const(t.minkowski_lattice_id) AS is_load_bearing_for_unit_distance_construction,-- TRUE when the lattice has a GS-satisfying source field, at least one short vector, and at least one planar projection — i.e. it is positioned to feed a ConstructionFamily that produces unit-distance witnesses.
  t.description                                                                 -- Free-text annotation for this row.
FROM minkowski_lattices t;

-- ----------------------------------------------------------------------------
-- vw_short_vectors: Table: ShortVectors. A vector in a MinkowskiLattice with bounded norm. NormSquared is raw (we are storing the lattice point's known squared length); IsShort is a calculated predicate against the lattice's threshold. The promotion: every individual short vector is a row — not a count, not a list — because each one carries a specific algebraic origin worth inspecting.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_short_vectors CASCADE;
CREATE VIEW vw_short_vectors WITH (security_invoker = ON) AS
SELECT
  t.short_vector_id,
  calc_short_vectors_name(t.short_vector_id) AS name,
  t.minkowski_lattice,
  t.coords_json,
  t.norm_squared,
  calc_short_vectors_threshold_squared(t.short_vector_id) AS threshold_squared,
  calc_short_vectors_is_short(t.short_vector_id) AS is_short,
  t.description                                                                 -- Free-text annotation for this row.
FROM short_vectors t;

-- ----------------------------------------------------------------------------
-- vw_construction_families: Table: ConstructionFamilies. A parametrized family {P_n} of point sets. SourceNumberField and SourceLattice are optional — non-null only for algebraic constructions. Each row produces a sequence of ConstructionInstances which feed a GrowthSequence.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_construction_families CASCADE;
CREATE VIEW vw_construction_families WITH (security_invoker = ON) AS
SELECT
  t.construction_family_id,
  calc_construction_families_name(t.construction_family_id) AS name,
  t.display_name,
  t.description_of_nth_member,
  t.source_number_field,
  t.source_minkowski_lattice,
  t.instances,
  calc_construction_families_instance_count(t.construction_family_id) AS instance_count,
  calc_construction_families_source_field_satisfies_golod_shafarevich(t.construction_family_id) AS source_field_satisfies_golod_shafarevich,-- The GS-satisfaction of the source field, inherited via SourceNumberField. Null if the family is non-algebraic (no source field set).
  calc_construction_families_source_lattice_is_load_bearing(t.construction_family_id) AS source_lattice_is_load_bearing,
  calc_construction_families_is_algebraic_construction(t.construction_family_id) AS is_algebraic_construction,-- TRUE iff the family's algebraic upstream is GS-passing AND its lattice has a projection + short vectors. Non-algebraic families (random points, ad-hoc geometric tricks) will be FALSE.
  t.description                                                                 -- Free-text annotation for this row.
FROM construction_families t;

-- ----------------------------------------------------------------------------
-- vw_construction_instances: Table: ConstructionInstances. The materialized P_n for a specific n. The PointSet it produces is a real row in PointSets — so all the geometry-layer aggregations apply to it without re-implementation. EdgeCount and DensityExponentEstimate are LOOKUPS, not duplicates.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_construction_instances CASCADE;
CREATE VIEW vw_construction_instances WITH (security_invoker = ON) AS
SELECT
  t.construction_instance_id,
  calc_construction_instances_name(t.construction_instance_id) AS name,
  t.construction_family,
  t.param_n,
  t.point_set,
  calc_construction_instances_point_count(t.construction_instance_id) AS point_count,
  calc_construction_instances_edge_count(t.construction_instance_id) AS edge_count,
  calc_construction_instances_density_exponent_estimate(t.construction_instance_id) AS density_exponent_estimate,
  calc_construction_instances_param_n_matches_point_count(t.construction_instance_id) AS param_n_matches_point_count,-- Sanity check: did the n-th instance actually produce n points?
  calc_construction_instances_family_is_algebraic(t.construction_instance_id) AS family_is_algebraic,-- Surfaces the family-level algebraic-construction flag onto each instance so per-row checks can see it.
  calc_construction_instances_is_explicit_superlinear(t.construction_instance_id) AS is_explicit_superlinear,-- TRUE if this single finite instance already exhibits log(edges)/log(points) > 1 — a per-instance witness that the family is achieving superlinear edge growth at this n.
  calc_construction_instances_is_algebraic_superlinear_witness(t.construction_instance_id) AS is_algebraic_superlinear_witness-- A single instance that is both (a) coming from an algebraically valid family AND (b) finitely superlinear. This is the most direct per-row evidence we have that the algebra is producing the geometry.
FROM construction_instances t;

-- ----------------------------------------------------------------------------
-- vw_growth_sequences: Table: GrowthSequences. The sequence (n, e(P_n)) realized by a ConstructionFamily, summarized as aggregations over its instances. MaxObservedDensityExponentEstimate is the strongest finite-sample witness the family currently provides — and is the value AsymptoticLowerBounds compares against to decide whether a claimed bound is finitely consistent.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_growth_sequences CASCADE;
CREATE VIEW vw_growth_sequences WITH (security_invoker = ON) AS
SELECT
  t.growth_sequence_id,
  calc_growth_sequences_name(t.growth_sequence_id) AS name,
  t.construction_family,
  calc_growth_sequences_observed_instance_count(t.growth_sequence_id) AS observed_instance_count,
  calc_growth_sequences_max_param_n(t.growth_sequence_id) AS max_param_n,
  calc_growth_sequences_max_edge_count(t.growth_sequence_id) AS max_edge_count,
  calc_growth_sequences_max_observed_density_exponent_estimate(t.growth_sequence_id) AS max_observed_density_exponent_estimate
FROM growth_sequences t;

-- ----------------------------------------------------------------------------
-- vw_asymptotic_functions: Table: AsymptoticFunctions. Named asymptotic functions like U(n). DefinitionText is the human-readable definition; the function's content is fully specified by the AsymptoticLowerBounds and (eventually) AsymptoticUpperBounds that reference it.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_asymptotic_functions CASCADE;
CREATE VIEW vw_asymptotic_functions WITH (security_invoker = ON) AS
SELECT
  t.asymptotic_function_id,
  calc_asymptotic_functions_name(t.asymptotic_function_id) AS name,
  t.display_name,
  t.definition_text,
  t.lower_bounds,
  calc_asymptotic_functions_lower_bound_count(t.asymptotic_function_id) AS lower_bound_count,
  calc_asymptotic_functions_best_known_lower_bound_exponent(t.asymptotic_function_id) AS best_known_lower_bound_exponent,-- ALL-TIME best lower-bound exponent across every loaded row, including retracted ones. Useful for forensic queries; usually NOT what you want for 'what does the rulebook currently believe'.
  calc_asymptotic_functions_best_known_current_lower_bound_expone(t.asymptotic_function_id) AS best_known_current_lower_bound_exponent,-- Bitemporally-filtered best lower-bound exponent: only counts bounds where IsCurrentlyValid=TRUE. This is what 'best known' actually means under the bitemporal discipline. Retracted overclaims, withdrawn preprints, and pending-evaluation rows are excluded.
  calc_asymptotic_functions_retracted_lower_bound_count(t.asymptotic_function_id) AS retracted_lower_bound_count,-- How many lower-bound rows for this function have been retracted/superseded. Cumulative scar count.
  calc_asymptotic_functions_max_overclaimed_exponent(t.asymptotic_function_id) AS max_overclaimed_exponent-- Highest exponent that was once claimed but is no longer current. Forensic indicator of overclaim history.
FROM asymptotic_functions t;

-- ----------------------------------------------------------------------------
-- vw_asymptotic_lower_bounds: Table: AsymptoticLowerBounds. A claim of the form 'AsymptoticFunction(n) ≥ Coefficient · n^Exponent for sufficiently large n'. Exponent is raw. IsSuperlinear, WitnessConsistent, and ExceedsTrivialLinearBound are all first-class calculated checks. WitnessConsistent compares the claimed exponent against MaxObservedDensityExponentEstimate from the supporting GrowthSequence — a finite-sample sanity check that doesn't replace the proof but does flag inconsistency.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_asymptotic_lower_bounds CASCADE;
CREATE VIEW vw_asymptotic_lower_bounds WITH (security_invoker = ON) AS
SELECT
  t.asymptotic_lower_bound_id,
  calc_asymptotic_lower_bounds_name(t.asymptotic_lower_bound_id) AS name,
  t.display_name,
  t.asymptotic_function,
  t.growth_sequence,
  t.exponent,
  t.coefficient,
  t.statement_text,
  t.source_citation,
  t.is_explicit,                                                                -- True if the exponent is named numerically (e.g. 1.014), false if only existential ('some ε > 0').
  calc_asymptotic_lower_bounds_is_superlinear(t.asymptotic_lower_bound_id) AS is_superlinear,
  calc_asymptotic_lower_bounds_exceeds_trivial_linear_bound(t.asymptotic_lower_bound_id) AS exceeds_trivial_linear_bound,
  calc_asymptotic_lower_bounds_witnessed_by_max_density_exponent(t.asymptotic_lower_bound_id) AS witnessed_by_max_density_exponent,
  calc_asymptotic_lower_bounds_witness_consistent(t.asymptotic_lower_bound_id) AS witness_consistent,-- Finite-sample sanity check: do the family's observed instances achieve at least the claimed exponent? FALSE means either more instances are needed or the claim is wrong for this family.
  calc_asymptotic_lower_bounds_witness_source_family(t.asymptotic_lower_bound_id) AS witness_source_family,-- Surfaces the ConstructionFamily backing this bound's witness, two FK hops upstream.
  calc_asymptotic_lower_bounds_witness_family_is_algebraic(t.asymptotic_lower_bound_id) AS witness_family_is_algebraic,-- TRUE iff the family providing this bound's finite witness is an algebraic construction with GS-passing source field. Distinguishes 'algebraically-anchored bound' from 'bound with a generic geometric witness'.
  calc_asymptotic_lower_bounds_is_algebraically_anchored(t.asymptotic_lower_bound_id) AS is_algebraically_anchored,-- TRUE when (a) the finite witness is consistent with the claimed exponent, (b) the witness family is algebraic-source, and (c) the claim itself is superlinear. This is the cleanest single-cell answer to 'does this bound carry the algebraic ladder all the way through?'
  calc_asymptotic_lower_bounds_obligation_count(t.asymptotic_lower_bound_id) AS obligation_count,
  calc_asymptotic_lower_bounds_satisfied_obligation_count(t.asymptotic_lower_bound_id) AS satisfied_obligation_count,
  calc_asymptotic_lower_bounds_open_obligation_count(t.asymptotic_lower_bound_id) AS open_obligation_count,
  calc_asymptotic_lower_bounds_all_obligations_satisfied(t.asymptotic_lower_bound_id) AS all_obligations_satisfied,-- TRUE iff every proof obligation referencing this bound is satisfied. FALSE means at least one obligation is unsatisfied or unevaluated.
  t.valid_from,                                                                 -- ISO date when this claim first entered valid-time (typically the publication date of the paper that asserts it).
  t.valid_to,                                                                   -- ISO date when this claim left valid-time (retraction, withdrawal). Null = still valid in the real world.
  t.tx_from,                                                                    -- ISO date when this row was first recorded in the rulebook (transaction-time audit start).
  t.tx_to,                                                                      -- ISO date when this row was logically removed from the rulebook. Null = still present in current transaction.
  t.is_currently_valid,                                                         -- Bitemporal current-validity flag. TRUE = claim is still considered valid; FALSE = superseded/withdrawn; null = not yet evaluated. Drives every 'current best known' aggregation in the asymptotic layer.
  t.proof_pathway,                                                              -- How the bound is proven. One of: 'algebraic-tower' (Sawin-style, via class field towers + Minkowski lattices), 'combinatorial-pigeonhole' (Erdős 1946, via integer-grid + divisor-function argument), 'crossing-number' (via crossing-number inequality), 'incidence-counting' (via point-line incidence bounds), 'witness-only' (finite-sample claim with no asymptotic proof), 'other'.
  calc_asymptotic_lower_bounds_is_algebraic_tower_proof(t.asymptotic_lower_bound_id) AS is_algebraic_tower_proof,
  calc_asymptotic_lower_bounds_is_combinatorial_proof(t.asymptotic_lower_bound_id) AS is_combinatorial_proof,
  calc_asymptotic_lower_bounds_is_auditable_via_its_pathway(t.asymptotic_lower_bound_id) AS is_auditable_via_its_pathway-- Pathway-appropriate audit gate. Algebraic-tower proofs need IsAlgebraicallyAnchored; combinatorial-pigeonhole proofs need obligations satisfied + finite witness consistent; witness-only claims just need WitnessConsistent. Fixes the bias of the older AlgebraicChainClosed gate, which would mis-rule Erdős's pigeonhole proof as 'not closed' simply because it doesn't use class field towers.
FROM asymptotic_lower_bounds t;

-- ----------------------------------------------------------------------------
-- vw_theorems: Table: Theorems. Fixed-point anchors. A theorem refers to an AsymptoticFunction and (when anchoring a bound) a specific AsymptoticLowerBound. AnchorMatchesBoundExponent is a calculated check that the anchor's named exponent equals the referenced bound's exponent — the kind of paperwork mistake that should be caught at read-time, not in review.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_theorems CASCADE;
CREATE VIEW vw_theorems WITH (security_invoker = ON) AS
SELECT
  t.theorem_id,
  calc_theorems_name(t.theorem_id) AS name,
  t.display_name,
  t.statement_text,
  t.is_anchor,
  t.is_proven,
  t.proof_citation,
  t.asymptotic_function,
  t.anchored_lower_bound,
  calc_theorems_anchored_bound_exponent(t.theorem_id) AS anchored_bound_exponent,
  calc_theorems_anchored_bound_is_superlinear(t.theorem_id) AS anchored_bound_is_superlinear,
  t.claimed_exponent,                                                           -- The exponent the theorem statement claims, recorded redundantly so the read-time check below can compare it against the bound's recorded exponent.
  calc_theorems_anchor_matches_bound_exponent(t.theorem_id) AS anchor_matches_bound_exponent,-- Read-time integrity check that the theorem and its anchored bound agree on the exponent.
  calc_theorems_anchored_bound_witness_consistent(t.theorem_id) AS anchored_bound_witness_consistent,-- Surfaces the bound-level finite-witness consistency onto the theorem row.
  calc_theorems_anchored_bound_is_algebraically_anchored(t.theorem_id) AS anchored_bound_is_algebraically_anchored,-- Surfaces the bound-level algebraic-anchoring onto the theorem row.
  calc_theorems_algebraic_chain_closed(t.theorem_id) AS algebraic_chain_closed, -- THE ladder check. TRUE iff (a) the theorem's claimed exponent matches the anchored bound, (b) the bound is superlinear, (c) the finite witness is consistent with the claim, (d) the witness family is algebraic with GS-passing source. When this is TRUE for a row, the entire chain from number field to theorem is closed in the rulebook.
  calc_theorems_applies_to_function(t.theorem_id) AS applies_to_function,       -- Human-readable name of the function the theorem talks about. Multi-anchor support — different theorems anchor different functions in the same neighborhood.
  calc_theorems_is_unit_distance_theorem(t.theorem_id) AS is_unit_distance_theorem,-- TRUE if this theorem is about U(n). Other anchors in this neighborhood (Szemerédi–Trotter, etc.) are about different functions.
  calc_theorems_anchored_bound_all_obligations_satisfied(t.theorem_id) AS anchored_bound_all_obligations_satisfied,-- Surfaces the anchored bound's full-obligation status onto the theorem row.
  calc_theorems_anchored_bound_open_obligation_count(t.theorem_id) AS anchored_bound_open_obligation_count,
  calc_theorems_fully_audited_and_closed(t.theorem_id) AS fully_audited_and_closed,-- The final, fully-paranoid theorem-level gate: the algebraic chain is closed AND every proof obligation against the anchored bound is satisfied. TRUE means the theorem row is end-to-end witnessed in the rulebook with no open obligations.
  t.valid_from,                                                                 -- ISO date this theorem was first established (proof publication date for proven; statement date for unproven anchors).
  t.valid_to,
  t.tx_from,
  t.tx_to,
  t.is_currently_valid,                                                         -- TRUE for current valid theorems; FALSE for retracted/disproven; null for unevaluated.
  calc_theorems_anchored_bound_is_currently_valid(t.theorem_id) AS anchored_bound_is_currently_valid,-- Surfaces the anchored bound's current-validity onto the theorem. If the anchored bound got retracted, this goes FALSE — and the theorem either needs re-anchoring or also needs retraction.
  calc_theorems_is_historically_anchored(t.theorem_id) AS is_historically_anchored,-- TRUE iff both the theorem and its anchored bound are currently valid. Bitemporally-aware version of the older AlgebraicChainClosed gate — catches the case where a theorem's anchored bound has been retracted.
  calc_theorems_anchored_bound_is_auditable_via_its_pathway(t.theorem_id) AS anchored_bound_is_auditable_via_its_pathway,-- Surfaces the anchored bound's pathway-appropriate audit gate onto the theorem.
  calc_theorems_is_audited_and_closed(t.theorem_id) AS is_audited_and_closed    -- The pathway-aware replacement for FullyAuditedAndClosed. TRUE iff the theorem is bitemporally valid, its anchored bound is bitemporally valid, AND the anchored bound passes its OWN pathway's audit gate (algebraic chain for Sawin-style; obligations+witness for Erdős-style pigeonhole). Erdős's theorem closes here even though the older algebraic-only gate said it couldn't.
FROM theorems t;

-- ----------------------------------------------------------------------------
-- vw_metrics: Table: Metrics. First-class distance functions on a space. The Euclidean metric on R^2, the Gram-matrix-induced metric on a lattice, and non-metric similarity functions all live here as named rows. Downstream tables that 'use a distance' should point at a Metrics row rather than hard-coding the formula.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_metrics CASCADE;
CREATE VIEW vw_metrics WITH (security_invoker = ON) AS
SELECT
  t.metric_id,
  calc_metrics_name(t.metric_id) AS name,
  t.display_name,
  t.ambient_context,
  t.metric_kind,                                                                -- One of: euclidean, lattice-gram, taxicab, cosine-similarity, experimental.
  t.definition_text,
  calc_metrics_is_euclidean(t.metric_id) AS is_euclidean,
  calc_metrics_is_lattice_gram(t.metric_id) AS is_lattice_gram,
  t.satisfies_triangle_inequality,                                              -- Nullable: TRUE for genuine metrics, FALSE for similarity-only functions, null for unevaluated experimental rows.
  t.description
FROM metrics t;

-- ----------------------------------------------------------------------------
-- vw_field_embeddings: Table: FieldEmbeddings. The individual embeddings σ_i: K → R or σ_j: K → C that constitute the Minkowski embedding. One row per σ. Aggregation by EmbeddingType reproduces the signature (r_1, r_2) at read time.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_field_embeddings CASCADE;
CREATE VIEW vw_field_embeddings WITH (security_invoker = ON) AS
SELECT
  t.field_embedding_id,
  calc_field_embeddings_name(t.field_embedding_id) AS name,
  t.number_field,
  t.embedding_type,                                                             -- One of: 'real' or 'complex'.
  t.index_in_signature,                                                         -- 1-based index within the signature.
  t.target_space_dim,                                                           -- 1 for real, 2 for complex.
  calc_field_embeddings_is_real_embedding(t.field_embedding_id) AS is_real_embedding,
  calc_field_embeddings_is_complex_embedding(t.field_embedding_id) AS is_complex_embedding,
  t.has_conjugate_pair_in_field,                                                -- Null for real embeddings (concept doesn't apply); TRUE for complex embeddings whose conjugate is in K; FALSE for hypothetical degenerate complex embeddings without their partner.
  t.description
FROM field_embeddings t;

-- ----------------------------------------------------------------------------
-- vw_minkowski_embeddings: Table: MinkowskiEmbeddings. The canonical embedding σ = (σ_1, …, σ_d): K → R^d as a first-class named map. Each row binds one NumberField to (at most) one TargetLattice it produces.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_minkowski_embeddings CASCADE;
CREATE VIEW vw_minkowski_embeddings WITH (security_invoker = ON) AS
SELECT
  t.minkowski_embedding_id,
  calc_minkowski_embeddings_name(t.minkowski_embedding_id) AS name,
  t.number_field,
  t.target_lattice,                                                             -- Nullable: the field may have a defined embedding map even if the materialised lattice row isn't loaded yet.
  calc_minkowski_embeddings_ambient_dimension(t.minkowski_embedding_id) AS ambient_dimension,
  calc_minkowski_embeddings_target_lattice_dimension(t.minkowski_embedding_id) AS target_lattice_dimension,
  calc_minkowski_embeddings_dimension_match(t.minkowski_embedding_id) AS dimension_match,
  t.is_canonical,                                                               -- TRUE if this is the canonical Minkowski embedding.
  t.preserves_additive_structure,                                               -- Nullable: TRUE for canonical embeddings, FALSE for non-additive maps, null for unevaluated experimental rows.
  t.description
FROM minkowski_embeddings t;

-- ----------------------------------------------------------------------------
-- vw_gram_matrices: Table: GramMatrices. The Gram matrix G_ij = <e_i, e_j> for a chosen basis of a MinkowskiLattice. Matrix entries stay in MatrixJSON (ERB scalar formulas can't operate on matrices), but every scalar property derivable from G — symmetric, positive-definite, diagonal, rank-deficient — is a first-class field.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_gram_matrices CASCADE;
CREATE VIEW vw_gram_matrices WITH (security_invoker = ON) AS
SELECT
  t.gram_matrix_id,
  calc_gram_matrices_name(t.gram_matrix_id) AS name,
  t.minkowski_lattice,
  calc_gram_matrices_dimension(t.gram_matrix_id) AS dimension,
  calc_gram_matrices_lattice_determinant(t.gram_matrix_id) AS lattice_determinant,
  t.matrix_json,
  t.is_symmetric,
  t.is_positive_definite,
  t.is_diagonal,
  t.rank_deficient,
  calc_gram_matrices_encodes_valid_lattice_metric(t.gram_matrix_id) AS encodes_valid_lattice_metric,-- TRUE iff G is symmetric and positive-definite — the algebraic conditions for G to induce a genuine metric.
  t.description
FROM gram_matrices t;

-- ----------------------------------------------------------------------------
-- vw_planar_projections: Table: PlanarProjections. The map π: lattice → R^2 that turns short lattice vectors into points in the plane. THE critical bridge from algebra to geometry. ProjectionKind tags the kind of map; downstream ProjectedShortVectors.ProjectsToUnitDistanceVector depends on this map's behaviour.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_planar_projections CASCADE;
CREATE VIEW vw_planar_projections WITH (security_invoker = ON) AS
SELECT
  t.planar_projection_id,
  calc_planar_projections_name(t.planar_projection_id) AS name,
  t.display_name,
  t.source_lattice,
  t.target_context,
  t.projection_kind,                                                            -- One of: 'first-two-coords', 'rotation-scale', 'rational-affine', 'isometric-embedding'.
  t.scaling_factor,
  t.rotation_degrees,
  calc_planar_projections_is_scaling_preserving(t.planar_projection_id) AS is_scaling_preserving,
  t.is_isometric,
  t.preserves_unit_distance,                                                    -- TRUE if vectors of squared-norm 1 in the lattice map to unit-distance vectors in R^2.
  t.projected_short_vectors,
  calc_planar_projections_projected_short_vector_count(t.planar_projection_id) AS projected_short_vector_count,
  calc_planar_projections_unit_distance_vector_count(t.planar_projection_id) AS unit_distance_vector_count,-- How many projected short vectors land at squared-norm 1 — i.e. survive as unit-distance witnesses. The geometric yield of the algebra-to-plane bridge.
  calc_planar_projections_unit_distance_vector_yield(t.planar_projection_id) AS unit_distance_vector_yield,-- Fraction of projected short vectors that are unit-distance witnesses.
  calc_planar_projections_source_lattice_is_load_bearing(t.planar_projection_id) AS source_lattice_is_load_bearing,
  t.description
FROM planar_projections t;

-- ----------------------------------------------------------------------------
-- vw_projected_short_vectors: Table: ProjectedShortVectors. Each row is one ShortVector under one PlanarProjection — the point in R^2 the algebraic vector becomes. ProjectsToUnitDistanceVector is THE planar-unit target equation <π(v), π(v)> = 1 — the equation Sawin's construction is solving. Every TRUE row is one solution, contributing one unit-distance edge.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_projected_short_vectors CASCADE;
CREATE VIEW vw_projected_short_vectors WITH (security_invoker = ON) AS
SELECT
  t.projected_short_vector_id,
  calc_projected_short_vectors_name(t.projected_short_vector_id) AS name,
  t.short_vector,
  t.planar_projection,
  t.projected_x,
  t.projected_y,
  calc_projected_short_vectors_projected_x_squared(t.projected_short_vector_id) AS projected_x_squared,
  calc_projected_short_vectors_projected_y_squared(t.projected_short_vector_id) AS projected_y_squared,
  calc_projected_short_vectors_projected_norm_squared(t.projected_short_vector_id) AS projected_norm_squared,-- <π(v), π(v)> — the LHS of the planar-unit target equation.
  calc_projected_short_vectors_source_norm_squared(t.projected_short_vector_id) AS source_norm_squared,
  calc_projected_short_vectors_source_is_short(t.projected_short_vector_id) AS source_is_short,
  t.unit_tolerance,
  calc_projected_short_vectors_distance_squared_from_unit(t.projected_short_vector_id) AS distance_squared_from_unit,
  calc_projected_short_vectors_projects_to_unit_distance_vector(t.projected_short_vector_id) AS projects_to_unit_distance_vector,-- THE planar-unit target equation: <π(v), π(v)> = 1. This is the equation Sawin's construction is solving — every TRUE row is one solution.
  calc_projected_short_vectors_is_valid_witness(t.projected_short_vector_id) AS is_valid_witness,-- The two-sided certificate: source vector is short (algebraic side) AND projection has squared norm 1 (geometric side).
  calc_projected_short_vectors_norm_preserved_under_projection(t.projected_short_vector_id) AS norm_preserved_under_projection,-- TRUE if the projection preserved the squared norm on this vector — locally isometric.
  t.description
FROM projected_short_vectors t;

-- ----------------------------------------------------------------------------
-- vw_golod_shafarevich_criteria: Table: GolodShafarevichCriteria. The Golod–Shafarevich tower inequality, evaluated per number field. r > d^2/4 (d = minimal-generator count, r = relation count) implies an infinite class field tower — the algebraic hook used by unit-distance constructions to get many small-norm primes.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_golod_shafarevich_criteria CASCADE;
CREATE VIEW vw_golod_shafarevich_criteria WITH (security_invoker = ON) AS
SELECT
  t.golod_shafarevich_criterion_id,
  calc_golod_shafarevich_criteria_name(t.golod_shafarevich_criterion_id) AS name,
  t.number_field,
  t.minimal_generator_count_d,                                                  -- The 'd' in the GS inequality.
  t.relation_count_r,                                                           -- The 'r' in the GS inequality.
  calc_golod_shafarevich_criteria_field_degree(t.golod_shafarevich_criterion_id) AS field_degree,
  calc_golod_shafarevich_criteria_criterion_threshold(t.golod_shafarevich_criterion_id) AS criterion_threshold,-- d^2/4. The bound that r must exceed.
  calc_golod_shafarevich_criteria_relation_count_exceeds_threshol(t.golod_shafarevich_criterion_id) AS relation_count_exceeds_threshold,
  calc_golod_shafarevich_criteria_satisfies_golod_shafarevich_tow(t.golod_shafarevich_criterion_id) AS satisfies_golod_shafarevich_tower,-- TRUE iff r > d^2/4 — the GS inequality is satisfied and K has an infinite class field tower.
  t.passes_criterion,                                                           -- Curator override (nullable). Null means 'use calculated SatisfiesGolodShafarevichTower'.
  t.source_reference,
  t.description
FROM golod_shafarevich_criteria t;

-- ----------------------------------------------------------------------------
-- vw_semantic_bridges: Table: SemanticBridges. Each row is one named bridge between two domain neighborhoods — the meta-glue between regions of the model. Routing across the model goes through these bridges.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_semantic_bridges CASCADE;
CREATE VIEW vw_semantic_bridges WITH (security_invoker = ON) AS
SELECT
  t.semantic_bridge_id,
  calc_semantic_bridges_name(t.semantic_bridge_id) AS name,
  t.display_name,
  t.from_domain,
  t.to_domain,
  t.bridge_kind,                                                                -- One of: embedding, projection, induction, aggregation, anchor, analogy.
  t.from_concept_table,
  t.to_concept_table,
  t.is_load_bearing,                                                            -- TRUE if removing the bridge breaks the chain to the theorem; FALSE for analogy-only; null when unclassified.
  t.is_closed,                                                                  -- TRUE if every row in FromConceptTable has a witness in ToConceptTable; null when not checked.
  calc_semantic_bridges_is_analogy(t.semantic_bridge_id) AS is_analogy,
  t.description
FROM semantic_bridges t;

-- ----------------------------------------------------------------------------
-- vw_semantic_routes: Table: SemanticRoutes. Named end-to-end paths through the model. The 'full semantic spine' is the route NumberFields → Theorems through every bridge.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_semantic_routes CASCADE;
CREATE VIEW vw_semantic_routes WITH (security_invoker = ON) AS
SELECT
  t.semantic_route_id,
  calc_semantic_routes_name(t.semantic_route_id) AS name,
  t.display_name,
  t.start_concept,
  t.end_concept,
  t.steps,
  calc_semantic_routes_step_count(t.semantic_route_id) AS step_count,
  t.is_full_spine,
  t.ends_at_theorem_anchor,
  calc_semantic_routes_validated_step_count(t.semantic_route_id) AS validated_step_count,
  calc_semantic_routes_all_steps_validated(t.semantic_route_id) AS all_steps_validated,-- TRUE iff every step on the route has IsValidated=TRUE.
  t.description
FROM semantic_routes t;

-- ----------------------------------------------------------------------------
-- vw_semantic_route_steps: Table: SemanticRouteSteps. The ordered inference steps that make up a SemanticRoute. Each step optionally invokes a SemanticBridge.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_semantic_route_steps CASCADE;
CREATE VIEW vw_semantic_route_steps WITH (security_invoker = ON) AS
SELECT
  t.semantic_route_step_id,
  calc_semantic_route_steps_name(t.semantic_route_step_id) AS name,
  t.semantic_route,
  t.step_order,
  t.from_concept,
  t.to_concept,
  t.bridge_used,                                                                -- Null when this step is an intra-domain FK hop; set when crossing domains.
  calc_semantic_route_steps_bridge_is_load_bearing(t.semantic_route_step_id) AS bridge_is_load_bearing,
  t.is_validated,                                                               -- Curator-set: TRUE if verified, FALSE if known broken, null if not yet evaluated.
  t.description
FROM semantic_route_steps t;

-- ----------------------------------------------------------------------------
-- vw_source_references: Table: SourceReferences. The bibliography. Every lemma, theorem, and bound points at exactly one SourceReference row.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_source_references CASCADE;
CREATE VIEW vw_source_references WITH (security_invoker = ON) AS
SELECT
  t.source_reference_id,
  calc_source_references_name(t.source_reference_id) AS name,
  t.short_label,
  t.full_citation,
  t.url,
  t.year,
  t.is_arxiv,
  t.is_published,
  calc_source_references_lemma_count(t.source_reference_id) AS lemma_count,
  calc_source_references_outbound_citation_count(t.source_reference_id) AS outbound_citation_count,-- How many other sources this one cites.
  calc_source_references_inbound_citation_count(t.source_reference_id) AS inbound_citation_count,-- How many other sources cite this one — a crude influence metric.
  t.valid_from,                                                                 -- ISO publication date — the moment this source becomes citable.
  t.valid_to,                                                                   -- ISO retraction date (if any). Null = still in good standing.
  t.tx_from,
  t.tx_to,
  t.is_currently_valid,                                                         -- TRUE if the source is still in good standing; FALSE if retracted; null if standing not yet evaluated.
  t.description
FROM source_references t;

-- ----------------------------------------------------------------------------
-- vw_lemmas: Table: Lemmas. Extracted named statements from source references. FeedsObjectTable + FeedsObjectId point at the row this lemma underwrites.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_lemmas CASCADE;
CREATE VIEW vw_lemmas WITH (security_invoker = ON) AS
SELECT
  t.lemma_id,
  calc_lemmas_name(t.lemma_id) AS name,
  t.label,
  t.source_reference,
  t.statement_text,
  t.feeds_object_table,
  t.feeds_object_id,
  t.is_loaded,                                                                  -- TRUE if the lemma's content has been turned into data; FALSE if known but not loaded; null if unevaluated.
  t.is_load_bearing,
  calc_lemmas_obligation_count(t.lemma_id) AS obligation_count,                 -- How many bounds depend on this lemma.
  t.valid_from,                                                                 -- ISO date this lemma was first asserted (inherits from SourceReference).
  t.valid_to,
  t.tx_from,
  t.tx_to,
  t.is_currently_valid,                                                         -- TRUE if the lemma is still considered valid; FALSE if refuted/retracted; null if unevaluated.
  t.description
FROM lemmas t;

-- ----------------------------------------------------------------------------
-- vw_mirror_contract: Table: MirrorContract. The five-rule contract from THE_PLAN.md §3.1 governing how the rulebook mirrors the math. Each rule is a row so agents and substrates can quote it back rather than reading the markdown.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_mirror_contract CASCADE;
CREATE VIEW vw_mirror_contract WITH (security_invoker = ON) AS
SELECT
  t.mirror_contract_id,
  calc_mirror_contract_name(t.mirror_contract_id) AS name,
  t.rule_label,
  t.rule_statement,
  t.rule_kind,                                                                  -- One of: load, describe, derive, gate, reject.
  t.applies_to_scope,
  t.is_binding_on_agents,                                                       -- TRUE if agents must follow this rule; FALSE if deprecated; null if under discussion.
  calc_mirror_contract_is_rejection_rule(t.mirror_contract_id) AS is_rejection_rule,
  t.description
FROM mirror_contract t;

-- ----------------------------------------------------------------------------
-- vw_conjectures: Table: Conjectures. Open and resolved conjectures about an AsymptoticFunction — distinct from Theorems (which are proved) because a conjecture is named, has a target exponent, and carries a resolution status that may change over time. Erdős's polynomial-improvement conjecture sits here; Sawin's resolved-as-proved conjecture-then-theorem is cross-referenced.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_conjectures CASCADE;
CREATE VIEW vw_conjectures WITH (security_invoker = ON) AS
SELECT
  t.conjecture_id,
  calc_conjectures_name(t.conjecture_id) AS name,
  t.display_name,
  t.statement_text,
  t.target_function,
  t.conjectured_exponent,                                                       -- The exponent the conjecture asserts. Null when the conjecture is non-exponent (e.g., a structural claim).
  t.is_conjectural_upper_bound,
  t.is_conjectural_lower_bound,
  t.proposed_by,
  t.is_resolved,                                                                -- TRUE if proved/disproved; FALSE if explicitly still open; null when status hasn't been classified.
  t.resolved_as,                                                                -- One of: 'proved', 'disproved', 'withdrawn'. Null when not resolved.
  t.resolution_citation,
  t.related_theorem,                                                            -- If this conjecture resolved into a theorem, the theorem row is here.
  calc_conjectures_is_still_open(t.conjecture_id) AS is_still_open,             -- TRUE only when IsResolved is explicitly FALSE. Null IsResolved propagates to non-TRUE.
  t.valid_from,                                                                 -- ISO date this conjecture was first proposed.
  t.valid_to,                                                                   -- ISO date this conjecture left open status (resolved or withdrawn). Null = still open.
  t.tx_from,
  t.tx_to,
  t.is_currently_valid,                                                         -- TRUE iff the conjecture is still an OPEN question. Resolved or withdrawn ⇒ FALSE. Null = unevaluated. NOTE: this is bitemporal-status, NOT the truth of the underlying proposition — a conjecture-that-became-a-theorem has IsCurrentlyValid=FALSE here but the proposition itself is now TRUE in Theorems.
  t.description
FROM conjectures t;

-- ----------------------------------------------------------------------------
-- vw_proof_obligations: Table: ProofObligations. Bidirectional links between AsymptoticLowerBounds and the Lemmas that must be loaded for the bound to be derivable. Each row says 'bound X depends on lemma Y'. Aggregations on the bound side surface how many obligations are open vs satisfied.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_proof_obligations CASCADE;
CREATE VIEW vw_proof_obligations WITH (security_invoker = ON) AS
SELECT
  t.proof_obligation_id,
  calc_proof_obligations_name(t.proof_obligation_id) AS name,
  t.parent_bound,
  t.required_lemma,
  t.obligation_kind,                                                            -- One of: 'necessary', 'sufficient', 'auxiliary'.
  calc_proof_obligations_is_necessary(t.proof_obligation_id) AS is_necessary,
  t.is_satisfied,                                                               -- TRUE if the curator has confirmed the lemma justifies its part of the bound; FALSE if known gap; null if unevaluated.
  calc_proof_obligations_is_lemma_loaded(t.proof_obligation_id) AS is_lemma_loaded,
  calc_proof_obligations_is_lemma_load_bearing(t.proof_obligation_id) AS is_lemma_load_bearing,
  calc_proof_obligations_bound_claimed_exponent(t.proof_obligation_id) AS bound_claimed_exponent,
  calc_proof_obligations_is_currently_open(t.proof_obligation_id) AS is_currently_open,-- TRUE only if explicitly FALSE — i.e. a known gap.
  t.valid_from,
  t.valid_to,
  t.tx_from,
  t.tx_to,
  t.is_currently_valid,
  t.description
FROM proof_obligations t;

-- ----------------------------------------------------------------------------
-- vw_citation_links: Table: CitationLinks. Directed graph of citations and dependencies between SourceReferences. CitationKind classifies whether the citing source extends, improves, depends on, or merely cites the cited source.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_citation_links CASCADE;
CREATE VIEW vw_citation_links WITH (security_invoker = ON) AS
SELECT
  t.citation_link_id,
  calc_citation_links_name(t.citation_link_id) AS name,
  t.citing_source,
  t.cited_source,
  t.citation_kind,                                                              -- One of: 'extends', 'improves', 'cites-for-context', 'depends-on', 'disagrees-with'.
  t.is_load_bearing,                                                            -- TRUE if removing the cited source breaks the citing source's proof; FALSE for context-only; null when unclassified.
  calc_citation_links_is_dependency(t.citation_link_id) AS is_dependency,
  calc_citation_links_is_improvement(t.citation_link_id) AS is_improvement,
  calc_citation_links_citing_year(t.citation_link_id) AS citing_year,
  calc_citation_links_cited_year(t.citation_link_id) AS cited_year,
  t.valid_from,                                                                 -- ISO date this citation became real (matches the citing source's publication date).
  t.valid_to,
  t.tx_from,
  t.tx_to,
  t.is_currently_valid,                                                         -- TRUE iff both the citing and cited sources are themselves still currently valid; FALSE if either has been retracted; null if unevaluated.
  t.description
FROM citation_links t;

-- ----------------------------------------------------------------------------
-- vw_answer_key: Table: AnswerKey. The §14 substrate-equivalence gate from THE_PLAN.md. Each row pins ONE cell (TargetTable + TargetRowId + TargetField) to its expected value. Every conformance-tested substrate (Postgres, Python, OWL, …) must reproduce these values; any mismatch with GateLevel='blocking' fails the build.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_answer_key CASCADE;
CREATE VIEW vw_answer_key WITH (security_invoker = ON) AS
SELECT
  t.answer_key_id,
  calc_answer_key_name(t.answer_key_id) AS name,
  t.target_table,
  t.target_row_id,
  t.target_field,
  t.data_type,                                                                  -- One of: 'string', 'number', 'boolean'.
  t.expected_string,
  t.expected_number,
  t.expected_boolean,
  t.tolerance,                                                                  -- Numeric tolerance for floating-point comparisons. Null for exact-match.
  t.gate_level,                                                                 -- One of: 'blocking', 'warning', 'info'.
  calc_answer_key_is_blocking(t.answer_key_id) AS is_blocking,
  t.is_currently_matched,                                                       -- TRUE if the most recent substrate run matched the expected value; FALSE if it didn't; null if not yet run.
  t.valid_from,                                                                 -- ISO date when this expected-value pin was first asserted.
  t.valid_to,                                                                   -- ISO date when this pin was retired/changed.
  t.tx_from,
  t.tx_to,
  t.is_currently_valid,                                                         -- TRUE if the pin is still the active expected value; FALSE if superseded by a newer pin; null if unevaluated.
  t.description
FROM answer_key t;

-- ----------------------------------------------------------------------------
-- vw_temporal_snapshots: Table: TemporalSnapshots. Named moments in the historical progression of the unit-distance problem. Each row pins a calendar date with a label so chronology becomes a first-class entity. Aggregations against bitemporal columns elsewhere in the rulebook can reference these moments by name instead of by raw ISO string.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_temporal_snapshots CASCADE;
CREATE VIEW vw_temporal_snapshots WITH (security_invoker = ON) AS
SELECT
  t.temporal_snapshot_id,
  calc_temporal_snapshots_name(t.temporal_snapshot_id) AS name,
  t.label,
  t.snapshot_date,                                                              -- ISO date for the moment this snapshot captures.
  t.description,
  t.is_historical,                                                              -- TRUE for past moments; FALSE for the current moment; null for future-projected moments.
  t.anchoring_source_reference,                                                 -- The source whose publication date pins this moment, when applicable.
  calc_temporal_snapshots_valid_lower_bound_count_at_this_moment(t.temporal_snapshot_id) AS valid_lower_bound_count_at_this_moment,-- How many AsymptoticLowerBound rows were considered valid at this moment, per the bitemporal columns.
  calc_temporal_snapshots_best_known_lower_bound_exponent_at_this(t.temporal_snapshot_id) AS best_known_lower_bound_exponent_at_this_moment,-- Date-only as-of rollup: MAX exponent of bounds bitemporally valid at this snapshot, including unevaluated/pending rows. Use this for forensic 'what would have looked best at this moment'.
  calc_temporal_snapshots_curator_confirmed_best_known_lower_boun(t.temporal_snapshot_id) AS curator_confirmed_best_known_lower_bound_exponent_at_this_moment,-- Stricter as-of rollup: MAX exponent of bounds BOTH bitemporally valid at this snapshot AND curator-confirmed (IsCurrentlyValid=TRUE on the bound itself). This is what the rulebook actually believed at this moment — excludes pending/unevaluated rows that just happen to be in their valid-time interval.
  calc_temporal_snapshots_pending_but_valid_by_date_count(t.temporal_snapshot_id) AS pending_but_valid_by_date_count,-- Rows that are bitemporally valid here but the curator hasn't ruled on yet — i.e., the rulebook's open epistemic questions at this snapshot.
  calc_temporal_snapshots_bounds_validated_or_retracted_this_mome(t.temporal_snapshot_id) AS bounds_validated_or_retracted_this_moment-- Total junction rows for this snapshot — should equal the count of all AsymptoticLowerBound rows (a closure check).
FROM temporal_snapshots t;

-- ----------------------------------------------------------------------------
-- vw_lower_bound_validity_at_snapshot: Table: LowerBoundValidityAtSnapshot. Junction between AsymptoticLowerBounds and TemporalSnapshots — one row per (bound × snapshot) pair recording whether the bound was bitemporally valid at that moment. Pre-computed because ERB's MAXIFS filters on equality, not on date ranges; this junction makes 'as-of' rollups expressible as plain aggregations on TemporalSnapshots.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_lower_bound_validity_at_snapshot CASCADE;
CREATE VIEW vw_lower_bound_validity_at_snapshot WITH (security_invoker = ON) AS
SELECT
  t.lower_bound_validity_at_snapshot_id,
  calc_lower_bound_validity_at_snapshot_name(t.lower_bound_validity_at_snapshot_id) AS name,
  t.asymptotic_lower_bound,
  t.temporal_snapshot,
  calc_lower_bound_validity_at_snapshot_bound_exponent(t.lower_bound_validity_at_snapshot_id) AS bound_exponent,
  calc_lower_bound_validity_at_snapshot_bound_valid_from(t.lower_bound_validity_at_snapshot_id) AS bound_valid_from,
  calc_lower_bound_validity_at_snapshot_bound_valid_to(t.lower_bound_validity_at_snapshot_id) AS bound_valid_to,
  calc_lower_bound_validity_at_snapshot_snapshot_date(t.lower_bound_validity_at_snapshot_id) AS snapshot_date,
  t.is_valid_at_this_snapshot,                                                  -- TRUE iff the bound's [ValidFrom, ValidTo) interval contains the SnapshotDate. Pre-computed since ERB MAXIFS doesn't support range filters; substrate-side temporal queries can re-derive this if needed.
  calc_lower_bound_validity_at_snapshot_bound_is_currently_valid(t.lower_bound_validity_at_snapshot_id) AS bound_is_currently_valid,-- Surfaces the bound's curator-set IsCurrentlyValid onto the junction. Distinguishes 'bitemporally valid by date' from 'curator-confirmed valid'.
  calc_lower_bound_validity_at_snapshot_is_curator_confirmed_at_t(t.lower_bound_validity_at_snapshot_id) AS is_curator_confirmed_at_this_snapshot,-- Stricter than IsValidAtThisSnapshot: TRUE iff the bound is BOTH within its valid-time interval at this snapshot AND has been curator-confirmed (IsCurrentlyValid=TRUE). Excludes pending/unevaluated rows from 'as-of' rollups.
  t.description                                                                 -- Free-text annotation for this row.
FROM lower_bound_validity_at_snapshot t;

