-- ============================================================================
-- 00-BOOTSTRAP - Run first by init-db.sh (overwrite Never)
-- ============================================================================
-- Use this file for one-time setup or to add your own bootstrap SQL.
-- The full clean-slate drop is NOT hand-coded here. It is owned by the
-- rulebook-to-postgres tool: effortless.json invokes it with
-- `-p mode=drop-all -p stage=dev -p drop_all=true`, which emits the dynamic
-- DROP (views -> functions -> tables, CASCADE) into 01-drop-and-create-tables.sql,
-- a file the tool regenerates on EVERY build. Keeping the drop there (rather than
-- in this overwrite-Never file) means the rebuild stays automatic and in sync
-- with the tool — nothing to maintain by hand.
--
-- The commented block below is the tool's reference clean-slate script, left
-- here only as documentation. Uncomment it ONLY if you ever run init-db.sh
-- without the drop-all mode and need a manual wipe.
-- ============================================================================

-- DO $$
-- DECLARE r RECORD; v_count INTEGER := 0;
-- BEGIN
--     RAISE NOTICE 'Dropping views...';
--     FOR r IN (SELECT table_name FROM information_schema.views WHERE table_schema = 'public') LOOP
--         EXECUTE 'DROP VIEW IF EXISTS ' || quote_ident(r.table_name) || ' CASCADE';
--         v_count := v_count + 1;
--     END LOOP;
--     RAISE NOTICE 'Dropped % views', v_count; v_count := 0;
--
--     RAISE NOTICE 'Dropping functions...';
--     FOR r IN (SELECT DISTINCT p.proname as function_name, pg_get_function_identity_arguments(p.oid) as function_args
--               FROM pg_proc p JOIN pg_namespace n ON p.pronamespace = n.oid
--               WHERE n.nspname = 'public' AND p.prokind = 'f') LOOP
--         EXECUTE 'DROP FUNCTION IF EXISTS ' || quote_ident(r.function_name) || '(' || r.function_args || ') CASCADE';
--         v_count := v_count + 1;
--     END LOOP;
--     RAISE NOTICE 'Dropped % functions', v_count; v_count := 0;
--
--     RAISE NOTICE 'Dropping tables...';
--     FOR r IN (SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE') LOOP
--         EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.table_name) || ' CASCADE';
--         v_count := v_count + 1;
--     END LOOP;
--     RAISE NOTICE 'Dropped % tables', v_count;
-- END $$;


