-- ============================================================================
-- CREATE FUNCTIONS - Calculation functions for lookup/calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- ============================================================================


-- Disable body validation so LANGUAGE sql functions can forward-reference
-- each other within this file. (pg_dump does the same thing for the same
-- reason.) Without this, SQL functions parse-check at CREATE time and fail
-- on the first forward call site; plpgsql didn't, which is how this file
-- ever worked. Dependency order is still enforced at EXECUTION time.
SET check_function_bodies = off;

-- ============================================================================
-- LOOKUP FUNCTIONS
-- These functions perform lookups via foreign key relationships
-- ============================================================================

-- calc_customers_name
-- Field: Customers.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_customers_name(p_customer_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(last_name, '') FROM customers WHERE customer_id = p_customer_id), ', ', (SELECT NULLIF(first_name, '') FROM customers WHERE customer_id = p_customer_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_customers_initials
-- Field: Customers.Initials
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_customers_initials(p_customer_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT(LEFT(((SELECT NULLIF(first_name, '') FROM customers WHERE customer_id = p_customer_id))::text, (1)::integer), LEFT(((SELECT NULLIF(last_name, '') FROM customers WHERE customer_id = p_customer_id))::text, (1)::integer)))::text;
$$ LANGUAGE sql STABLE;

-- ============================================================================
-- MANY-SIDE RELATIONSHIP FUNCTIONS
-- These functions aggregate child records for many-side relationships
-- ============================================================================

-- ============================================================================
-- INVERSE RELATIONSHIP FUNCTIONS
-- These functions perform reverse FK lookups for inverse-side relationships
-- ============================================================================

