-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- Total Views: 1
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Drop pass: every rulebook-owned view, reverse iteration order, CASCADE.
-- The rulebook is HEAD — the surviving view set must mirror it exactly.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_customers CASCADE;

-- ----------------------------------------------------------------------------
-- vw_customers: View for Customers
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_customers CASCADE;
CREATE VIEW vw_customers WITH (security_invoker = ON) AS
SELECT
  t.customer_id,
  t.first_name,                                                                 -- First Name of the customer
  t.last_name,                                                                  -- Last Name of the customer
  calc_customers_name(t.customer_id) AS name,                                   -- Full name: first and last
  calc_customers_initials(t.customer_id) AS initials                            -- First letter of the first and last name
FROM customers t;

