-- ============================================================================
-- CREATE TABLES (check-add mode) - Idempotent schema, never drops columns
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Tables: 7
-- Total Raw Fields: 47
-- ============================================================================

SET timezone = 'UTC';

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- systems: Each row is a fractal or power-law system described in a common schema.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS systems (
  system_id                           TEXT                 PRIMARY KEY          -- Primary key for the system.
);
ALTER TABLE systems ADD COLUMN IF NOT EXISTS display_name TEXT;                                     -- Human readable label.
ALTER TABLE systems ADD COLUMN IF NOT EXISTS class TEXT;                                            -- High-level class: 'fractal' or 'power_law'.
ALTER TABLE systems ADD COLUMN IF NOT EXISTS base_scale NUMERIC;                                    -- Reference scale x0 for iteration 0.
ALTER TABLE systems ADD COLUMN IF NOT EXISTS scale_factor NUMERIC;                                  -- Multiplicative change in scale per iteration.
ALTER TABLE systems ADD COLUMN IF NOT EXISTS measure_name TEXT;                                     -- What the measured quantity represents (count, perimeter, frequency, etc.).
ALTER TABLE systems ADD COLUMN IF NOT EXISTS fractal_dimension NUMERIC;                             -- Fractal (Hausdorff / similarity) dimension where defined (geometric fractals). Null for purely statistical laws.
ALTER TABLE systems ADD COLUMN IF NOT EXISTS theoretical_log_log_slope NUMERIC;                     -- Theoretical slope d(log Measure)/d(log Scale) for this system under the chosen definition of Scale.
COMMENT ON TABLE systems IS 'Each row is a fractal or power-law system described in a common schema.';
COMMENT ON COLUMN systems.system_id IS 'Primary key for the system.';
COMMENT ON COLUMN systems.display_name IS 'Human readable label.';
COMMENT ON COLUMN systems.class IS 'High-level class: ''fractal'' or ''power_law''.';
COMMENT ON COLUMN systems.base_scale IS 'Reference scale x0 for iteration 0.';
COMMENT ON COLUMN systems.scale_factor IS 'Multiplicative change in scale per iteration.';
COMMENT ON COLUMN systems.measure_name IS 'What the measured quantity represents (count, perimeter, frequency, etc.).';
COMMENT ON COLUMN systems.fractal_dimension IS 'Fractal (Hausdorff / similarity) dimension where defined (geometric fractals). Null for purely statistical laws.';
COMMENT ON COLUMN systems.theoretical_log_log_slope IS 'Theoretical slope d(log Measure)/d(log Scale) for this system under the chosen definition of Scale.';

-- ----------------------------------------------------------------------------
-- scales: Generic log–log points for each system at multiple iterations / scales.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS scales (
  scale_id                            TEXT                 PRIMARY KEY          -- Primary key for this scale measurement.
);
ALTER TABLE scales ADD COLUMN IF NOT EXISTS "system" TEXT;                                          -- FK to systems table.
ALTER TABLE scales ADD COLUMN IF NOT EXISTS iteration INTEGER;                                      -- Discrete zoom level or rank index.
ALTER TABLE scales ADD COLUMN IF NOT EXISTS measure NUMERIC;                                        -- Y-axis measured quantity at this scale.
ALTER TABLE scales ADD COLUMN IF NOT EXISTS is_projected BOOLEAN;                                   -- True if this data point is a projection/estimate rather than measured data.
ALTER TABLE scales ADD COLUMN IF NOT EXISTS data_regime TEXT;                                       -- Data regime for this point: 'ideal' (constructed/projection) or 'measured' (noisy real-world measurement).
ALTER TABLE scales ADD COLUMN IF NOT EXISTS measurement_model TEXT;                                 -- Optional FK to measurement_models describing noise/cutoff/discretization used to generate or interpret this point.
COMMENT ON TABLE scales IS 'Generic log–log points for each system at multiple iterations / scales.';
COMMENT ON COLUMN scales.scale_id IS 'Primary key for this scale measurement.';
COMMENT ON COLUMN scales."system" IS 'FK to systems table.';
COMMENT ON COLUMN scales.iteration IS 'Discrete zoom level or rank index.';
COMMENT ON COLUMN scales.measure IS 'Y-axis measured quantity at this scale.';
COMMENT ON COLUMN scales.is_projected IS 'True if this data point is a projection/estimate rather than measured data.';
COMMENT ON COLUMN scales.data_regime IS 'Data regime for this point: ''ideal'' (constructed/projection) or ''measured'' (noisy real-world measurement).';
COMMENT ON COLUMN scales.measurement_model IS 'Optional FK to measurement_models describing noise/cutoff/discretization used to generate or interpret this point.';

-- ----------------------------------------------------------------------------
-- system_stats: Statistical analysis of each system's log-log behavior, with rollups from scales and lookups to systems.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS system_stats (
  system_stats_id                     TEXT                 PRIMARY KEY          -- Primary key for this stats record.
);
ALTER TABLE system_stats ADD COLUMN IF NOT EXISTS "system" TEXT;                                    -- FK to systems table.
ALTER TABLE system_stats ADD COLUMN IF NOT EXISTS analysis_name TEXT;                               -- Human-readable name for this analysis run.
ALTER TABLE system_stats ADD COLUMN IF NOT EXISTS status TEXT;                                      -- Status of analysis: draft, validated, published.
COMMENT ON TABLE system_stats IS 'Statistical analysis of each system''s log-log behavior, with rollups from scales and lookups to systems.';
COMMENT ON COLUMN system_stats.system_stats_id IS 'Primary key for this stats record.';
COMMENT ON COLUMN system_stats."system" IS 'FK to systems table.';
COMMENT ON COLUMN system_stats.analysis_name IS 'Human-readable name for this analysis run.';
COMMENT ON COLUMN system_stats.status IS 'Status of analysis: draft, validated, published.';

-- ----------------------------------------------------------------------------
-- measurement_models: Measurement/de-idealization specs used to produce or interpret real-world (noisy, finite-size, discretized) scale records.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS measurement_models (
  measurement_model_id                TEXT                 PRIMARY KEY          -- Primary key for this measurement model.
);
ALTER TABLE measurement_models ADD COLUMN IF NOT EXISTS "system" TEXT;                              -- FK to systems table (measurement model is typically system-specific).
ALTER TABLE measurement_models ADD COLUMN IF NOT EXISTS data_regime TEXT;                           -- Regime this model describes. Usually 'measured'.
ALTER TABLE measurement_models ADD COLUMN IF NOT EXISTS scale_regime TEXT;                          -- Optional RegimeID this measurement model applies to
ALTER TABLE measurement_models ADD COLUMN IF NOT EXISTS noise_type TEXT;                            -- Noise model applied to measures (e.g., lognormal multiplicative).
ALTER TABLE measurement_models ADD COLUMN IF NOT EXISTS noise_sigma NUMERIC;                        -- Noise strength parameter (e.g., sigma in log space for lognormal).
ALTER TABLE measurement_models ADD COLUMN IF NOT EXISTS cutoff_min_scale NUMERIC;                   -- Minimum scale included (finite-size / censoring lower bound).
ALTER TABLE measurement_models ADD COLUMN IF NOT EXISTS cutoff_max_scale NUMERIC;                   -- Maximum scale included (finite-size / censoring upper bound).
ALTER TABLE measurement_models ADD COLUMN IF NOT EXISTS discretization_type TEXT;                   -- How observations are discretized (none, rounding, binning, log-binning).
ALTER TABLE measurement_models ADD COLUMN IF NOT EXISTS discretization_param TEXT;                  -- Parameterization of discretization (e.g., decimals=2 or binwidth=log2).
COMMENT ON TABLE measurement_models IS 'Measurement/de-idealization specs used to produce or interpret real-world (noisy, finite-size, discretized) scale records.';
COMMENT ON COLUMN measurement_models.measurement_model_id IS 'Primary key for this measurement model.';
COMMENT ON COLUMN measurement_models."system" IS 'FK to systems table (measurement model is typically system-specific).';
COMMENT ON COLUMN measurement_models.data_regime IS 'Regime this model describes. Usually ''measured''.';
COMMENT ON COLUMN measurement_models.scale_regime IS 'Optional RegimeID this measurement model applies to';
COMMENT ON COLUMN measurement_models.noise_type IS 'Noise model applied to measures (e.g., lognormal multiplicative).';
COMMENT ON COLUMN measurement_models.noise_sigma IS 'Noise strength parameter (e.g., sigma in log space for lognormal).';
COMMENT ON COLUMN measurement_models.cutoff_min_scale IS 'Minimum scale included (finite-size / censoring lower bound).';
COMMENT ON COLUMN measurement_models.cutoff_max_scale IS 'Maximum scale included (finite-size / censoring upper bound).';
COMMENT ON COLUMN measurement_models.discretization_type IS 'How observations are discretized (none, rounding, binning, log-binning).';
COMMENT ON COLUMN measurement_models.discretization_param IS 'Parameterization of discretization (e.g., decimals=2 or binwidth=log2).';

-- ----------------------------------------------------------------------------
-- observed_scales: Noisy, finite-range, discretized observations of each system's scaling law. Mirrors scales but with DataRegime='measured'.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS observed_scales (
  observed_scale_id                   TEXT                 PRIMARY KEY          -- Primary key for this observed scale measurement.
);
ALTER TABLE observed_scales ADD COLUMN IF NOT EXISTS "system" TEXT;                                 -- FK to systems table.
ALTER TABLE observed_scales ADD COLUMN IF NOT EXISTS measurement_model TEXT;                        -- FK to measurement model used/assumed for this observation set.
ALTER TABLE observed_scales ADD COLUMN IF NOT EXISTS iteration INTEGER;                             -- Discrete zoom level or rank index.
ALTER TABLE observed_scales ADD COLUMN IF NOT EXISTS measure NUMERIC;                               -- Observed (noisy) Y-axis quantity at this scale.
ALTER TABLE observed_scales ADD COLUMN IF NOT EXISTS data_regime TEXT;                              -- Data regime. For observed_scales this is 'measured'.
COMMENT ON TABLE observed_scales IS 'Noisy, finite-range, discretized observations of each system''s scaling law. Mirrors scales but with DataRegime=''measured''.';
COMMENT ON COLUMN observed_scales.observed_scale_id IS 'Primary key for this observed scale measurement.';
COMMENT ON COLUMN observed_scales."system" IS 'FK to systems table.';
COMMENT ON COLUMN observed_scales.measurement_model IS 'FK to measurement model used/assumed for this observation set.';
COMMENT ON COLUMN observed_scales.iteration IS 'Discrete zoom level or rank index.';
COMMENT ON COLUMN observed_scales.measure IS 'Observed (noisy) Y-axis quantity at this scale.';
COMMENT ON COLUMN observed_scales.data_regime IS 'Data regime. For observed_scales this is ''measured''.';

-- ----------------------------------------------------------------------------
-- inference_runs: Inference outputs (fits and residual geometry) computed from observed_scales relative to each system fixed point.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS inference_runs (
  inference_run_id                    TEXT                 PRIMARY KEY          -- Primary key for this inference run.
);
ALTER TABLE inference_runs ADD COLUMN IF NOT EXISTS "system" TEXT;                                  -- FK to systems table.
ALTER TABLE inference_runs ADD COLUMN IF NOT EXISTS data_regime TEXT;                               -- Regime of the fitted data (ideal/measured).
ALTER TABLE inference_runs ADD COLUMN IF NOT EXISTS measurement_model TEXT;                         -- FK to measurement model used/assumed (nullable for ideal).
ALTER TABLE inference_runs ADD COLUMN IF NOT EXISTS fit_method TEXT;                                -- Fitting method used (e.g., OLS on log-log).
ALTER TABLE inference_runs ADD COLUMN IF NOT EXISTS point_count INTEGER;                            -- Count of observed points used in fit (measured).
ALTER TABLE inference_runs ADD COLUMN IF NOT EXISTS theoretical_log_log_slope NUMERIC;              -- Fixed-point slope for the system.
ALTER TABLE inference_runs ADD COLUMN IF NOT EXISTS fitted_slope NUMERIC;                           -- Estimated slope from observed data under FitMethod.
ALTER TABLE inference_runs ADD COLUMN IF NOT EXISTS fitted_intercept NUMERIC;                       -- Estimated intercept in log10 space (logMeasure = intercept + slope*logScale).
ALTER TABLE inference_runs ADD COLUMN IF NOT EXISTS slope_delta NUMERIC;                            -- Difference between fitted slope and fixed-point slope.
ALTER TABLE inference_runs ADD COLUMN IF NOT EXISTS r2 NUMERIC;                                     -- Coefficient of determination for the log-log fit.
ALTER TABLE inference_runs ADD COLUMN IF NOT EXISTS residual_rms NUMERIC;                           -- Root-mean-square residual in log10 space (vertical residuals).
ALTER TABLE inference_runs ADD COLUMN IF NOT EXISTS residual_max_abs NUMERIC;                       -- Maximum absolute residual in log10 space.
ALTER TABLE inference_runs ADD COLUMN IF NOT EXISTS orthogonal_rms NUMERIC;                         -- RMS orthogonal distance to the fitted log-log line in (logScale, logMeasure) coordinates.
ALTER TABLE inference_runs ADD COLUMN IF NOT EXISTS deviation_score NUMERIC;                        -- Composite deviation score combining residual RMS and slope delta (units: log10 + slope).
COMMENT ON TABLE inference_runs IS 'Inference outputs (fits and residual geometry) computed from observed_scales relative to each system fixed point.';
COMMENT ON COLUMN inference_runs.inference_run_id IS 'Primary key for this inference run.';
COMMENT ON COLUMN inference_runs."system" IS 'FK to systems table.';
COMMENT ON COLUMN inference_runs.data_regime IS 'Regime of the fitted data (ideal/measured).';
COMMENT ON COLUMN inference_runs.measurement_model IS 'FK to measurement model used/assumed (nullable for ideal).';
COMMENT ON COLUMN inference_runs.fit_method IS 'Fitting method used (e.g., OLS on log-log).';
COMMENT ON COLUMN inference_runs.point_count IS 'Count of observed points used in fit (measured).';
COMMENT ON COLUMN inference_runs.theoretical_log_log_slope IS 'Fixed-point slope for the system.';
COMMENT ON COLUMN inference_runs.fitted_slope IS 'Estimated slope from observed data under FitMethod.';
COMMENT ON COLUMN inference_runs.fitted_intercept IS 'Estimated intercept in log10 space (logMeasure = intercept + slope*logScale).';
COMMENT ON COLUMN inference_runs.slope_delta IS 'Difference between fitted slope and fixed-point slope.';
COMMENT ON COLUMN inference_runs.r2 IS 'Coefficient of determination for the log-log fit.';
COMMENT ON COLUMN inference_runs.residual_rms IS 'Root-mean-square residual in log10 space (vertical residuals).';
COMMENT ON COLUMN inference_runs.residual_max_abs IS 'Maximum absolute residual in log10 space.';
COMMENT ON COLUMN inference_runs.orthogonal_rms IS 'RMS orthogonal distance to the fitted log-log line in (logScale, logMeasure) coordinates.';
COMMENT ON COLUMN inference_runs.deviation_score IS 'Composite deviation score combining residual RMS and slope delta (units: log10 + slope).';

-- ----------------------------------------------------------------------------
-- scale_regimes: Multi-regime analysis defining different scale ranges within systems where different slope behaviors may occur.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS scale_regimes (
  regime_id                           TEXT                 PRIMARY KEY          -- Primary key for this regime.
);
ALTER TABLE scale_regimes ADD COLUMN IF NOT EXISTS "system" TEXT;                                   -- FK to systems table.
ALTER TABLE scale_regimes ADD COLUMN IF NOT EXISTS min_log_scale NUMERIC;                           -- Minimum log10(scale) boundary for this regime.
ALTER TABLE scale_regimes ADD COLUMN IF NOT EXISTS max_log_scale NUMERIC;                           -- Maximum log10(scale) boundary for this regime.
ALTER TABLE scale_regimes ADD COLUMN IF NOT EXISTS expected_slope NUMERIC;                          -- Expected log-log slope within this regime.
ALTER TABLE scale_regimes ADD COLUMN IF NOT EXISTS regime_type TEXT;                                -- Type of regime: 'early_scaling', 'mature_scaling', 'crossover', 'cutoff', etc.
COMMENT ON TABLE scale_regimes IS 'Multi-regime analysis defining different scale ranges within systems where different slope behaviors may occur.';
COMMENT ON COLUMN scale_regimes.regime_id IS 'Primary key for this regime.';
COMMENT ON COLUMN scale_regimes."system" IS 'FK to systems table.';
COMMENT ON COLUMN scale_regimes.min_log_scale IS 'Minimum log10(scale) boundary for this regime.';
COMMENT ON COLUMN scale_regimes.max_log_scale IS 'Maximum log10(scale) boundary for this regime.';
COMMENT ON COLUMN scale_regimes.expected_slope IS 'Expected log-log slope within this regime.';
COMMENT ON COLUMN scale_regimes.regime_type IS 'Type of regime: ''early_scaling'', ''mature_scaling'', ''crossover'', ''cutoff'', etc.';

-- ============================================================================
-- FK INDEXES - Performance only, always applied
-- ============================================================================

-- scales
CREATE INDEX IF NOT EXISTS idx_scales_system ON scales ("system");
CREATE INDEX IF NOT EXISTS idx_scales_measurement_model ON scales (measurement_model);

-- system_stats
CREATE INDEX IF NOT EXISTS idx_system_stats_system ON system_stats ("system");

-- measurement_models
CREATE INDEX IF NOT EXISTS idx_measurement_models_system ON measurement_models ("system");

-- observed_scales
CREATE INDEX IF NOT EXISTS idx_observed_scales_system ON observed_scales ("system");
CREATE INDEX IF NOT EXISTS idx_observed_scales_measurement_model ON observed_scales (measurement_model);

-- inference_runs
CREATE INDEX IF NOT EXISTS idx_inference_runs_system ON inference_runs ("system");
CREATE INDEX IF NOT EXISTS idx_inference_runs_measurement_model ON inference_runs (measurement_model);

-- scale_regimes
CREATE INDEX IF NOT EXISTS idx_scale_regimes_system ON scale_regimes ("system");

-- 9 FK index(es) declared.
