-- ============================================================================
-- CREATE POLICIES - Row Level Security policies
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- ============================================================================

-- Enable RLS on all tables

ALTER TABLE project_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE ontology_axioms ENABLE ROW LEVEL SECURITY;
ALTER TABLE framing_invariants ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_features ENABLE ROW LEVEL SECURITY;
ALTER TABLE rulebook_source_spokes ENABLE ROW LEVEL SECURITY;
ALTER TABLE rulebook_domains ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_launch_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_local_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE rulebook_flavors ENABLE ROW LEVEL SECURITY;
ALTER TABLE field_type_taxonomy ENABLE ROW LEVEL SECURITY;
ALTER TABLE formula_dialects ENABLE ROW LEVEL SECURITY;
ALTER TABLE demo_narratives ENABLE ROW LEVEL SECURITY;
ALTER TABLE glossary ENABLE ROW LEVEL SECURITY;
ALTER TABLE rulebook_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE flavor_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE claude_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE build_phases ENABLE ROW LEVEL SECURITY;
ALTER TABLE effort_classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_disciplines ENABLE ROW LEVEL SECURITY;
ALTER TABLE erb_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE erb_feature_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE erb_features ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_stories ENABLE ROW LEVEL SECURITY;
ALTER TABLE acceptance_criteria ENABLE ROW LEVEL SECURITY;
ALTER TABLE consistency_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE consistency_findings ENABLE ROW LEVEL SECURITY;
ALTER TABLE mobile_nav_tabs ENABLE ROW LEVEL SECURITY;
ALTER TABLE mobile_routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE skill_routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_layout_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_slot_witnesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE cmcc_summary ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_goal ENABLE ROW LEVEL SECURITY;
ALTER TABLE architectural_highlight ENABLE ROW LEVEL SECURITY;

-- TODO: Add specific RLS policies based on your security requirements
-- Example:
-- CREATE POLICY "Users can view their own data" ON app_user
--   FOR SELECT USING (auth.uid() = user_id);

