-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- Total Views: 5
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Drop pass: every rulebook-owned view, reverse iteration order, CASCADE.
-- The rulebook is HEAD — the surviving view set must mirror it exactly.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_types_of_project CASCADE;
DROP VIEW IF EXISTS vw_roles CASCADE;
DROP VIEW IF EXISTS vw_employees CASCADE;
DROP VIEW IF EXISTS vw_projects CASCADE;
DROP VIEW IF EXISTS vw_client CASCADE;

-- ----------------------------------------------------------------------------
-- vw_client: Table: Client
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_client CASCADE;
CREATE VIEW vw_client WITH (security_invoker = ON) AS
SELECT
  t.client_id,
  t.customer,                                                                   -- Identifier for the customers.
  t.email_address,                                                              -- Thec ustomers email address
  t.first_name,                                                                 -- First Name of the customer - used to make the full name
  t.last_name,                                                                  -- Last Name of the customer - used to make the full name
  calc_client_full_name(t.client_id) AS full_name                               -- The client's full name, written first name then last name (FirstName & " " & LastName).
FROM client t;

-- ----------------------------------------------------------------------------
-- vw_projects: Table: Projects
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_projects CASCADE;
CREATE VIEW vw_projects WITH (security_invoker = ON) AS
SELECT
  t.project_id,
  t.name,
  t.description,
  t.project_type,
  calc_projects_project_type_name(t.project_id) AS project_type_name,
  calc_projects_project_type_description(t.project_id) AS project_type_description,
  calc_projects_project_type_requires_manager_approval(t.project_id) AS project_type_requires_manager_approval,
  t.due_date,
  calc_projects_is_approved(t.project_id) AS is_approved,                       -- Whether the project is validly approved. True when the project's type doesn't require manager approval, OR the person in ApprovedBy holds a manager role.
  t.approved_by,
  calc_projects_approved_by_role_is_manager(t.project_id) AS approved_by_role_is_manager,
  calc_projects_approved_by_name(t.project_id) AS approved_by_name,
  calc_projects_approved_by_email_address(t.project_id) AS approved_by_email_address,
  calc_projects_approved_by_phone_number(t.project_id) AS approved_by_phone_number
FROM projects t;

-- ----------------------------------------------------------------------------
-- vw_employees: Table: Employees
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_employees CASCADE;
CREATE VIEW vw_employees WITH (security_invoker = ON) AS
SELECT
  t.employee_id,
  t.name,
  t.email_address,
  t.phone_number,
  t.role,
  calc_employees_role_name(t.employee_id) AS role_name,
  calc_employees_role_description(t.employee_id) AS role_description,
  t.projects,
  calc_employees_role_is_manager(t.employee_id) AS role_is_manager
FROM employees t;

-- ----------------------------------------------------------------------------
-- vw_roles: Table: Roles
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_roles CASCADE;
CREATE VIEW vw_roles WITH (security_invoker = ON) AS
SELECT
  t.role_id,
  t.name,
  t.description,
  t.is_manager,
  t.employees,
  calc_roles_count_of_employees(t.role_id) AS count_of_employees
FROM roles t;

-- ----------------------------------------------------------------------------
-- vw_types_of_project: Table: TypesOfProject
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_types_of_project CASCADE;
CREATE VIEW vw_types_of_project WITH (security_invoker = ON) AS
SELECT
  t.types_of_project_id,
  t.name,
  t.description,
  t.requires_manager_approval,
  t.projects,
  calc_types_of_project_count_of_projects(t.types_of_project_id) AS count_of_projects
FROM types_of_project t;

