#!/usr/bin/env python3
"""
Shared functions for ERB execution substrate generators.
All inject-into-*.py scripts use these common utilities.
"""

import json
import os
from pathlib import Path
from datetime import datetime


def get_rulebook_path():
    """Get the path to the effortless-rulebook.json file.

    Scripts run from /execution-substrates/{candidate}/ so the rulebook
    is at ../../effortless-rulebook/effortless-rulebook.json
    """
    return Path("../../effortless-rulebook/effortless-rulebook.json")


def load_rulebook():
    """Load and parse the effortless-rulebook.json file."""
    rulebook_path = get_rulebook_path()

    if not rulebook_path.exists():
        raise FileNotFoundError(f"Rulebook not found at {rulebook_path}")

    with open(rulebook_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def ensure_output_folder():
    """Ensure the current working directory exists (it should, since we run from there)."""
    cwd = Path.cwd()
    cwd.mkdir(parents=True, exist_ok=True)
    return cwd


def write_readme(candidate_name, description=None, technology=None):
    """Write a placeholder README.md for the execution substrate.

    Args:
        candidate_name: Name of the target format/substrate (e.g., 'python', 'owl')
        description: Optional description, defaults to a placeholder message
        technology: Optional technology section explaining the format/substrate
    """
    output_folder = ensure_output_folder()
    readme_path = output_folder / "README.md"

    if description is None:
        description = f"Placeholder for {candidate_name} generation from the Effortless Rulebook."

    # Build technology section if provided
    technology_section = ""
    if technology:
        technology_section = f"\n## Technology\n\n{technology}\n"

    content = f"""# {candidate_name.title()} Execution Substrate

{description}
{technology_section}
## Status

This is a placeholder generated by the ERB orchestration system.

## Source

Generated from: `effortless-rulebook/effortless-rulebook.json`

"""

    with open(readme_path, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Created {readme_path}")
    return readme_path


def get_candidate_name_from_cwd():
    """Extract the candidate name from the current working directory.

    Assumes we're running from /execution-substrates/{candidate}/
    """
    return Path.cwd().name


def clean_generated_files(generated_files: list, substrate_name: str = None):
    """Remove generated files from a substrate directory.

    Args:
        generated_files: List of filenames (relative to cwd) to remove
        substrate_name: Optional name for logging (defaults to cwd name)

    Returns:
        List of files that were successfully removed
    """
    if substrate_name is None:
        substrate_name = get_candidate_name_from_cwd()

    cwd = Path.cwd()
    removed = []

    print(f"Cleaning generated files for {substrate_name}...")

    for filename in generated_files:
        file_path = cwd / filename
        if file_path.exists():
            try:
                file_path.unlink()
                print(f"  Removed: {filename}")
                removed.append(filename)
            except Exception as e:
                print(f"  Failed to remove {filename}: {e}")
        else:
            print(f"  Skipped (not found): {filename}")

    if removed:
        print(f"Cleaned {len(removed)} file(s)")
    else:
        print("No files to clean")

    return removed


def handle_clean_arg(generated_files: list, description: str = None):
    """Check for --clean argument and perform cleanup if requested.

    Args:
        generated_files: List of filenames to remove when cleaning
        description: Optional description to display

    Returns:
        True if --clean was handled (script should exit), False otherwise
    """
    import sys

    if '--clean' in sys.argv:
        substrate_name = get_candidate_name_from_cwd()
        if description:
            print(f"\n{description}\n")
        print(f"=" * 60)
        print(f"CLEAN MODE: {substrate_name.upper()}")
        print(f"=" * 60)
        clean_generated_files(generated_files, substrate_name)
        return True

    return False


# =============================================================================
# ENTITY DISCOVERY FUNCTIONS
# =============================================================================
# These functions discover entities, schemas, and computed columns from the
# rulebook. They enable multi-entity processing across all substrates.
# =============================================================================

import re


def to_snake_case(name: str) -> str:
    """Convert PascalCase to snake_case: UserAccounts -> user_accounts

    Also handles fields with existing underscores: Bio_HockettScore -> bio_hockett_score
    """
    # Use [^_] to avoid doubling underscores when input already has them
    s1 = re.sub('([^_])([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


def to_pascal_case(name: str) -> str:
    """Convert snake_case to PascalCase: user_accounts -> UserAccounts"""
    return ''.join(word.capitalize() for word in name.split('_'))


def discover_entities(rulebook: dict) -> list:
    """
    Discover all entities from the rulebook.
    Entities are top-level keys that have a 'schema' array.
    Returns list of entity names in PascalCase (as they appear in rulebook).
    """
    entities = []
    skip_keys = {'$schema', 'model_name', 'Description', '_meta'}

    for key, value in rulebook.items():
        if key in skip_keys:
            continue
        if isinstance(value, dict) and 'schema' in value:
            entities.append(key)

    return entities


def get_entity_schema(rulebook: dict, entity_name: str) -> list:
    """
    Get the schema array for an entity.
    Handles both PascalCase and snake_case entity names.
    """
    # Try direct lookup first
    if entity_name in rulebook:
        return rulebook[entity_name].get('schema', [])

    # Try converting from snake_case to PascalCase
    pascal_name = to_pascal_case(entity_name)
    if pascal_name in rulebook:
        return rulebook[pascal_name].get('schema', [])

    # Try converting from PascalCase to snake_case and look up
    snake_name = to_snake_case(entity_name)
    for key in rulebook:
        if to_snake_case(key) == snake_name:
            return rulebook[key].get('schema', [])

    return []


def get_entity_data(rulebook: dict, entity_name: str) -> list:
    """
    Get the data array for an entity.
    Handles both PascalCase and snake_case entity names.
    """
    # Try direct lookup first
    if entity_name in rulebook:
        return rulebook[entity_name].get('data', [])

    # Try converting from snake_case to PascalCase
    pascal_name = to_pascal_case(entity_name)
    if pascal_name in rulebook:
        return rulebook[pascal_name].get('data', [])

    # Try converting from PascalCase to snake_case and look up
    snake_name = to_snake_case(entity_name)
    for key in rulebook:
        if to_snake_case(key) == snake_name:
            return rulebook[key].get('data', [])

    return []


def discover_primary_key(rulebook: dict, entity_name: str) -> str:
    """
    Discover the primary key for an entity.
    Returns the first non-nullable field, or first field ending in 'Id'.
    """
    schema = get_entity_schema(rulebook, entity_name)

    # First try: find first non-nullable field
    for field in schema:
        if field.get('nullable') == False:
            return to_snake_case(field['name'])

    # Second try: find first field ending in 'Id'
    for field in schema:
        if field['name'].endswith('Id'):
            return to_snake_case(field['name'])

    # Fallback: first field
    if schema:
        return to_snake_case(schema[0]['name'])

    return None


def discover_computed_columns(rulebook: dict, entity_name: str) -> list:
    """
    Discover computed columns for an entity.
    Returns list of snake_case column names where type == "calculated".
    """
    schema = get_entity_schema(rulebook, entity_name)

    computed = []
    for field in schema:
        if field.get('type') == 'calculated':
            computed.append(to_snake_case(field['name']))

    return computed


def get_calculated_fields(schema: list) -> list:
    """
    Extract all calculated fields from a schema.
    Returns list of field dicts where type == "calculated" and formula exists.
    """
    return [
        field for field in schema
        if field.get('type') == 'calculated' and field.get('formula')
    ]


def get_raw_fields(schema: list) -> list:
    """Extract all raw fields from a schema."""
    return [field for field in schema if field.get('type') == 'raw']


def get_aggregation_fields(schema: list) -> list:
    """Extract all aggregation fields from a schema."""
    return [field for field in schema if field.get('type') == 'aggregation']


# =============================================================================
# AGGREGATION COMPUTATION
# =============================================================================
# These functions compute aggregation fields (COUNTIFS, SUMIFS, etc.) by
# loading related data from the testing/blank-tests directory.
# =============================================================================

def parse_countifs_formula(formula: str) -> tuple:
    """
    Parse a COUNTIFS formula to extract the related table, lookup field, and match field.

    Formula format: =COUNTIFS(RelatedTable!{{LookupField}}, CurrentTable!{{MatchField}})
    Example: =COUNTIFS(WorkflowSteps!{{Workflow}}, Workflows!{{WorkflowId}})

    Returns: (related_table, lookup_field, match_field) or (None, None, None) if not parseable
    """
    import re
    # Match pattern: COUNTIFS(Table!{{Field}}, Table!{{Field}})
    pattern = r'=COUNTIFS\((\w+)!\{\{(\w+)\}\},\s*\w+!\{\{(\w+)\}\}\)'
    match = re.match(pattern, formula)
    if match:
        related_table = match.group(1)  # e.g., "WorkflowSteps"
        lookup_field = match.group(2)   # e.g., "Workflow"
        match_field = match.group(3)    # e.g., "WorkflowId"
        return (related_table, lookup_field, match_field)
    return (None, None, None)


def load_related_data(project_root: Path, related_table: str) -> list:
    """
    Load data from testing/blank-tests for a related table.

    Args:
        project_root: Path to the project root
        related_table: PascalCase name of the related table

    Returns:
        List of records from the related table's blank-tests file
    """
    snake_name = to_snake_case(related_table)
    blank_tests_path = project_root / "testing" / "blank-tests" / f"{snake_name}.json"

    if not blank_tests_path.exists():
        return []

    with open(blank_tests_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def compute_aggregations(records: list, entity_name: str, rulebook: dict, project_root: Path) -> list:
    """
    Compute aggregation fields for a list of records.

    This function identifies aggregation fields in the schema, loads related data,
    and computes the aggregated values (e.g., COUNTIFS).

    Args:
        records: List of records to update with aggregation values
        entity_name: Name of the entity (PascalCase or snake_case)
        rulebook: The loaded rulebook dictionary
        project_root: Path to the project root for loading related data

    Returns:
        Updated list of records with aggregation fields populated
    """
    schema = get_entity_schema(rulebook, entity_name)
    agg_fields = get_aggregation_fields(schema)

    if not agg_fields:
        return records

    # Cache for loaded related data
    related_data_cache = {}

    for field in agg_fields:
        field_name = field.get('name')
        formula = field.get('formula', '')
        snake_field_name = to_snake_case(field_name)

        # Parse the formula
        related_table, lookup_field, match_field = parse_countifs_formula(formula)

        if not related_table:
            continue

        # Load related data (with caching)
        if related_table not in related_data_cache:
            related_data_cache[related_table] = load_related_data(project_root, related_table)

        related_records = related_data_cache[related_table]
        snake_lookup_field = to_snake_case(lookup_field)
        snake_match_field = to_snake_case(match_field)

        # Build a count map: match_value -> count
        count_map = {}
        for related_record in related_records:
            lookup_value = related_record.get(snake_lookup_field)
            if lookup_value is not None:
                count_map[lookup_value] = count_map.get(lookup_value, 0) + 1

        # Update each record with the aggregation value
        for record in records:
            match_value = record.get(snake_match_field)
            if match_value is not None:
                record[snake_field_name] = count_map.get(match_value, 0)
            else:
                record[snake_field_name] = 0

    return records
