-- ============================================================================
-- DROP AND CREATE TABLES (drop-all mode) - Clean slate + Normalized schema
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- Total Tables: 11
-- Total Raw Fields: 84
-- ============================================================================

SET timezone = 'UTC';

-- ============================================================================
-- DROP ALL OBJECTS - Clean slate for database
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- ============================================================================

DO $$ 
DECLARE r RECORD; v_count INTEGER := 0;
BEGIN
    RAISE NOTICE 'Dropping views...';
    FOR r IN (SELECT table_name FROM information_schema.views WHERE table_schema = 'public') LOOP
        EXECUTE 'DROP VIEW IF EXISTS ' || quote_ident(r.table_name) || ' CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % views', v_count; v_count := 0;
    
    RAISE NOTICE 'Dropping functions...';
    FOR r IN (SELECT DISTINCT p.proname as function_name, pg_get_function_identity_arguments(p.oid) as function_args
              FROM pg_proc p JOIN pg_namespace n ON p.pronamespace = n.oid
              WHERE n.nspname = 'public' AND p.prokind = 'f') LOOP
        EXECUTE 'DROP FUNCTION IF EXISTS ' || quote_ident(r.function_name) || '(' || r.function_args || ') CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % functions', v_count; v_count := 0;
    
    RAISE NOTICE 'Dropping tables...';
    FOR r IN (SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE') LOOP
        EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.table_name) || ' CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % tables', v_count;
END $$;

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Users: Bank employees: relationship managers, underwriters, branch bankers, and admins. Used for portfolio assignment, audit trails, and segregation-of-duties enforcement.
-- ----------------------------------------------------------------------------
CREATE TABLE users (
  users_id                            TEXT                 PRIMARY KEY,         -- Primary key (synthesized from the calculated Name — the table's logical key — so it wins over incidental Id-ending attribute fields).
  full_name                           TEXT                ,                     -- Display label of the bank employee.
  role                                TEXT                ,                     -- Role discriminator: RM, Underwriter, BranchBanker, or Admin.
  email                               TEXT                                      -- Bank email used for SSO and notifications.
);
COMMENT ON TABLE users IS 'Bank employees: relationship managers, underwriters, branch bankers, and admins. Used for portfolio assignment, audit trails, and segregation-of-duties enforcement.';
COMMENT ON COLUMN users.users_id IS 'Primary key (synthesized from the calculated Name — the table''s logical key — so it wins over incidental Id-ending attribute fields).';
COMMENT ON COLUMN users.full_name IS 'Display label of the bank employee.';
COMMENT ON COLUMN users.role IS 'Role discriminator: RM, Underwriter, BranchBanker, or Admin.';
COMMENT ON COLUMN users.email IS 'Bank email used for SSO and notifications.';

-- ----------------------------------------------------------------------------
-- Businesses: Small-business customers (and prospects) of the bank. Central entity: BeneficialOwners, Contacts, Accounts, Loans, Documents, and Interactions all hang off a Business. BusinessProfile information (legal name, structure, NAICS code) lives directly on this table.
-- ----------------------------------------------------------------------------
CREATE TABLE businesses (
  businesses_id                       TEXT                 PRIMARY KEY,         -- Primary key (synthesized from the calculated Name — the table's logical key — so it wins over incidental Id-ending attribute fields).
  legal_name                          TEXT                ,                     -- Registered legal name of the business.
  business_structure                  TEXT                ,                     -- Entity structure: LLC, C-Corp, S-Corp, Partnership, Sole Proprietor, etc.
  naics_code                          TEXT                ,                     -- North American Industry Classification System code for the business.
  naics_description                   TEXT                ,                     -- Human-readable label for the NAICS code.
  annual_revenue_usd                  NUMERIC             ,                     -- Most-recent annual revenue, USD.
  status                              TEXT                ,                     -- Lifecycle status: Prospect, Customer, or Closed.
  onboarded_at                        TIMESTAMPTZ         ,                     -- Date onboarding completed (KYB cleared, first account opened).
  relationship_manager                TEXT                ,                     -- FK to Users: the RM who owns this business relationship (the SinglePointOfContact).
  referral_source                     TEXT                                      -- Optional FK to another Business that referred this prospect/customer in.
);
COMMENT ON TABLE businesses IS 'Small-business customers (and prospects) of the bank. Central entity: BeneficialOwners, Contacts, Accounts, Loans, Documents, and Interactions all hang off a Business. BusinessProfile information (legal name, structure, NAICS code) lives directly on this table.';
COMMENT ON COLUMN businesses.businesses_id IS 'Primary key (synthesized from the calculated Name — the table''s logical key — so it wins over incidental Id-ending attribute fields).';
COMMENT ON COLUMN businesses.legal_name IS 'Registered legal name of the business.';
COMMENT ON COLUMN businesses.business_structure IS 'Entity structure: LLC, C-Corp, S-Corp, Partnership, Sole Proprietor, etc.';
COMMENT ON COLUMN businesses.naics_code IS 'North American Industry Classification System code for the business.';
COMMENT ON COLUMN businesses.naics_description IS 'Human-readable label for the NAICS code.';
COMMENT ON COLUMN businesses.annual_revenue_usd IS 'Most-recent annual revenue, USD.';
COMMENT ON COLUMN businesses.status IS 'Lifecycle status: Prospect, Customer, or Closed.';
COMMENT ON COLUMN businesses.onboarded_at IS 'Date onboarding completed (KYB cleared, first account opened).';
COMMENT ON COLUMN businesses.relationship_manager IS 'FK to Users: the RM who owns this business relationship (the SinglePointOfContact).';
COMMENT ON COLUMN businesses.referral_source IS 'Optional FK to another Business that referred this prospect/customer in.';

-- ----------------------------------------------------------------------------
-- BeneficialOwners: Individuals owning 25%+ of a Business plus designated control persons, per FinCEN's CDD rule. PII (SSN, DOB, address) is stored encrypted at rest via field-level encryption.
-- ----------------------------------------------------------------------------
CREATE TABLE beneficial_owners (
  beneficial_owners_id                TEXT                 PRIMARY KEY,         -- Primary key (synthesized from the calculated Name — the table's logical key — so it wins over incidental Id-ending attribute fields).
  business                            TEXT                ,                     -- FK to the parent Business.
  full_name                           TEXT                ,                     -- Owner's full legal name.
  date_of_birth_encrypted             TEXT                ,                     -- Encrypted date of birth (PII, FieldLevelEncryption).
  ssn_encrypted                       TEXT                ,                     -- Encrypted Social Security Number (PII, FieldLevelEncryption).
  address_encrypted                   TEXT                ,                     -- Encrypted home address (PII, FieldLevelEncryption).
  ownership_percentage                NUMERIC             ,                     -- Percent of the Business owned by this individual (0-100).
  is_control_person                   BOOLEAN                                   -- True when this individual is the designated control person per CDD (one is required when no owner crosses 25%).
);
COMMENT ON TABLE beneficial_owners IS 'Individuals owning 25%+ of a Business plus designated control persons, per FinCEN''s CDD rule. PII (SSN, DOB, address) is stored encrypted at rest via field-level encryption.';
COMMENT ON COLUMN beneficial_owners.beneficial_owners_id IS 'Primary key (synthesized from the calculated Name — the table''s logical key — so it wins over incidental Id-ending attribute fields).';
COMMENT ON COLUMN beneficial_owners.business IS 'FK to the parent Business.';
COMMENT ON COLUMN beneficial_owners.full_name IS 'Owner''s full legal name.';
COMMENT ON COLUMN beneficial_owners.date_of_birth_encrypted IS 'Encrypted date of birth (PII, FieldLevelEncryption).';
COMMENT ON COLUMN beneficial_owners.ssn_encrypted IS 'Encrypted Social Security Number (PII, FieldLevelEncryption).';
COMMENT ON COLUMN beneficial_owners.address_encrypted IS 'Encrypted home address (PII, FieldLevelEncryption).';
COMMENT ON COLUMN beneficial_owners.ownership_percentage IS 'Percent of the Business owned by this individual (0-100).';
COMMENT ON COLUMN beneficial_owners.is_control_person IS 'True when this individual is the designated control person per CDD (one is required when no owner crosses 25%).';

-- ----------------------------------------------------------------------------
-- Contacts: Non-owner individuals associated with a Business: officers, AP clerks, authorized signers, additional points of contact. Distinct from BeneficialOwners (which carries PII/CDD weight).
-- ----------------------------------------------------------------------------
CREATE TABLE contacts (
  contacts_id                         TEXT                 PRIMARY KEY,         -- Primary key (synthesized from the calculated Name — the table's logical key — so it wins over incidental Id-ending attribute fields).
  business                            TEXT                ,                     -- FK to the parent Business.
  full_name                           TEXT                ,                     -- Contact's full name.
  title                               TEXT                ,                     -- Job title at the business (CEO, CFO, AP Clerk, etc.).
  email                               TEXT                ,                     -- Contact email.
  phone                               TEXT                ,                     -- Contact phone.
  contact_type                        TEXT                ,                     -- Discriminator: Officer, APClerk, AuthorizedSigner, Other.
  is_authorized_signer                BOOLEAN                                   -- True when this contact can sign on the business's accounts.
);
COMMENT ON TABLE contacts IS 'Non-owner individuals associated with a Business: officers, AP clerks, authorized signers, additional points of contact. Distinct from BeneficialOwners (which carries PII/CDD weight).';
COMMENT ON COLUMN contacts.contacts_id IS 'Primary key (synthesized from the calculated Name — the table''s logical key — so it wins over incidental Id-ending attribute fields).';
COMMENT ON COLUMN contacts.business IS 'FK to the parent Business.';
COMMENT ON COLUMN contacts.full_name IS 'Contact''s full name.';
COMMENT ON COLUMN contacts.title IS 'Job title at the business (CEO, CFO, AP Clerk, etc.).';
COMMENT ON COLUMN contacts.email IS 'Contact email.';
COMMENT ON COLUMN contacts.phone IS 'Contact phone.';
COMMENT ON COLUMN contacts.contact_type IS 'Discriminator: Officer, APClerk, AuthorizedSigner, Other.';
COMMENT ON COLUMN contacts.is_authorized_signer IS 'True when this contact can sign on the business''s accounts.';

-- ----------------------------------------------------------------------------
-- Accounts: Deposit accounts the Business holds at the bank (checking, savings, money market). Balances feed GlobalCashFlow during credit analysis. TreasuryServices enrollment flags (ACH, Wire, Card) are stored per-account.
-- ----------------------------------------------------------------------------
CREATE TABLE accounts (
  accounts_id                         TEXT                 PRIMARY KEY,         -- Primary key (synthesized from the calculated Name — the table's logical key — so it wins over incidental Id-ending attribute fields).
  business                            TEXT                ,                     -- FK to the parent Business.
  account_type                        TEXT                ,                     -- Checking, Savings, MoneyMarket, etc.
  account_number_last4                TEXT                ,                     -- Last 4 digits of the account number for display.
  current_balance_usd                 NUMERIC             ,                     -- Current balance in USD; sourced from CoreBanking.
  has_ach                             BOOLEAN             ,                     -- ACH treasury service enrolled on this account.
  has_wire                            BOOLEAN             ,                     -- Wire transfer treasury service enrolled on this account.
  has_card                            BOOLEAN             ,                     -- Business card product issued against this account.
  opened_at                           TIMESTAMPTZ                               -- Date the account was opened.
);
COMMENT ON TABLE accounts IS 'Deposit accounts the Business holds at the bank (checking, savings, money market). Balances feed GlobalCashFlow during credit analysis. TreasuryServices enrollment flags (ACH, Wire, Card) are stored per-account.';
COMMENT ON COLUMN accounts.accounts_id IS 'Primary key (synthesized from the calculated Name — the table''s logical key — so it wins over incidental Id-ending attribute fields).';
COMMENT ON COLUMN accounts.business IS 'FK to the parent Business.';
COMMENT ON COLUMN accounts.account_type IS 'Checking, Savings, MoneyMarket, etc.';
COMMENT ON COLUMN accounts.account_number_last4 IS 'Last 4 digits of the account number for display.';
COMMENT ON COLUMN accounts.current_balance_usd IS 'Current balance in USD; sourced from CoreBanking.';
COMMENT ON COLUMN accounts.has_ach IS 'ACH treasury service enrolled on this account.';
COMMENT ON COLUMN accounts.has_wire IS 'Wire transfer treasury service enrolled on this account.';
COMMENT ON COLUMN accounts.has_card IS 'Business card product issued against this account.';
COMMENT ON COLUMN accounts.opened_at IS 'Date the account was opened.';

-- ----------------------------------------------------------------------------
-- Loans: Credit facilities extended to a Business, tracked from inquiry through funding, servicing, and payoff. RiskRating is denormalized here for fast reads; every change is captured in RiskRatingHistory.
-- ----------------------------------------------------------------------------
CREATE TABLE loans (
  loans_id                            TEXT                 PRIMARY KEY,         -- Primary key (synthesized from the calculated Name — the table's logical key — so it wins over incidental Id-ending attribute fields).
  loan_number                         TEXT                ,                     -- Bank-assigned loan number (e.g. 'L-0051').
  business                            TEXT                ,                     -- FK to the borrower Business.
  originating_rm                      TEXT                ,                     -- FK to Users: the RM who originated this loan.
  underwriter                         TEXT                ,                     -- FK to Users: the underwriter who underwrote this loan.
  loan_purpose                        TEXT                ,                     -- Equipment, CRE, LOC, WorkingCapital, etc.
  principal_usd                       NUMERIC             ,                     -- Loan principal at origination, USD.
  rate_pct                            NUMERIC             ,                     -- Interest rate, percent (e.g. 7.25).
  term_months                         INTEGER             ,                     -- Loan term in months.
  underwriting_stage                  TEXT                ,                     -- Current pipeline stage: Inquiry, PreQualification, Application, KYBAndBureauPull, Packaging, CreditAnalysis, CommitteeApproval, ClosingPrep, Signing, Funded.
  risk_rating                         INTEGER             ,                     -- Current risk grade (1=Pass strongest ... 7=Substandard ... 9=Loss). Denormalized; every change is captured in RiskRatingHistory.
  risk_rating_label                   TEXT                ,                     -- Human-readable label for the current risk grade.
  dscr                                NUMERIC             ,                     -- Most recent debt service coverage ratio.
  ltv                                 NUMERIC             ,                     -- Most recent loan-to-value ratio (0-1); null for unsecured loans.
  global_cash_flow_usd                NUMERIC             ,                     -- Most recent global cash flow figure across business, owners, and affiliates.
  originated_at                       TIMESTAMPTZ         ,                     -- Date the application was created.
  funded_at                           TIMESTAMPTZ                               -- Date the loan funded; null until funding completes.
);
COMMENT ON TABLE loans IS 'Credit facilities extended to a Business, tracked from inquiry through funding, servicing, and payoff. RiskRating is denormalized here for fast reads; every change is captured in RiskRatingHistory.';
COMMENT ON COLUMN loans.loans_id IS 'Primary key (synthesized from the calculated Name — the table''s logical key — so it wins over incidental Id-ending attribute fields).';
COMMENT ON COLUMN loans.loan_number IS 'Bank-assigned loan number (e.g. ''L-0051'').';
COMMENT ON COLUMN loans.business IS 'FK to the borrower Business.';
COMMENT ON COLUMN loans.originating_rm IS 'FK to Users: the RM who originated this loan.';
COMMENT ON COLUMN loans.underwriter IS 'FK to Users: the underwriter who underwrote this loan.';
COMMENT ON COLUMN loans.loan_purpose IS 'Equipment, CRE, LOC, WorkingCapital, etc.';
COMMENT ON COLUMN loans.principal_usd IS 'Loan principal at origination, USD.';
COMMENT ON COLUMN loans.rate_pct IS 'Interest rate, percent (e.g. 7.25).';
COMMENT ON COLUMN loans.term_months IS 'Loan term in months.';
COMMENT ON COLUMN loans.underwriting_stage IS 'Current pipeline stage: Inquiry, PreQualification, Application, KYBAndBureauPull, Packaging, CreditAnalysis, CommitteeApproval, ClosingPrep, Signing, Funded.';
COMMENT ON COLUMN loans.risk_rating IS 'Current risk grade (1=Pass strongest ... 7=Substandard ... 9=Loss). Denormalized; every change is captured in RiskRatingHistory.';
COMMENT ON COLUMN loans.risk_rating_label IS 'Human-readable label for the current risk grade.';
COMMENT ON COLUMN loans.dscr IS 'Most recent debt service coverage ratio.';
COMMENT ON COLUMN loans.ltv IS 'Most recent loan-to-value ratio (0-1); null for unsecured loans.';
COMMENT ON COLUMN loans.global_cash_flow_usd IS 'Most recent global cash flow figure across business, owners, and affiliates.';
COMMENT ON COLUMN loans.originated_at IS 'Date the application was created.';
COMMENT ON COLUMN loans.funded_at IS 'Date the loan funded; null until funding completes.';

-- ----------------------------------------------------------------------------
-- Covenants: Conditions attached to a Loan that must be tested on a recurring schedule (e.g. minimum DSCR each quarter). CovenantMonitoring runs the tickler calendar ahead of NextTestDate; breaches surface as SystemEvent Interactions.
-- ----------------------------------------------------------------------------
CREATE TABLE covenants (
  covenants_id                        TEXT                 PRIMARY KEY,         -- Primary key (synthesized from the calculated Name — the table's logical key — so it wins over incidental Id-ending attribute fields).
  loan                                TEXT                ,                     -- FK to the parent Loan.
  covenant_type                       TEXT                ,                     -- MinDSCR, MaxLeverage, ReportingFinancials, etc.
  threshold_value                     NUMERIC             ,                     -- Numeric threshold for the test (e.g. 1.20 for MinDSCR); null for non-numeric covenants.
  test_frequency                      TEXT                ,                     -- Quarterly, Annual, Monthly, etc.
  next_test_date                      TIMESTAMPTZ         ,                     -- Date of the next scheduled covenant test.
  status                              TEXT                ,                     -- Active, Breached, Waived, Cured, Closed.
  current_waiver_through              TIMESTAMPTZ                               -- Date through which an active CovenantWaiver is in effect; null when no active waiver.
);
COMMENT ON TABLE covenants IS 'Conditions attached to a Loan that must be tested on a recurring schedule (e.g. minimum DSCR each quarter). CovenantMonitoring runs the tickler calendar ahead of NextTestDate; breaches surface as SystemEvent Interactions.';
COMMENT ON COLUMN covenants.covenants_id IS 'Primary key (synthesized from the calculated Name — the table''s logical key — so it wins over incidental Id-ending attribute fields).';
COMMENT ON COLUMN covenants.loan IS 'FK to the parent Loan.';
COMMENT ON COLUMN covenants.covenant_type IS 'MinDSCR, MaxLeverage, ReportingFinancials, etc.';
COMMENT ON COLUMN covenants.threshold_value IS 'Numeric threshold for the test (e.g. 1.20 for MinDSCR); null for non-numeric covenants.';
COMMENT ON COLUMN covenants.test_frequency IS 'Quarterly, Annual, Monthly, etc.';
COMMENT ON COLUMN covenants.next_test_date IS 'Date of the next scheduled covenant test.';
COMMENT ON COLUMN covenants.status IS 'Active, Breached, Waived, Cured, Closed.';
COMMENT ON COLUMN covenants.current_waiver_through IS 'Date through which an active CovenantWaiver is in effect; null when no active waiver.';

-- ----------------------------------------------------------------------------
-- RiskRatingHistory: Time-series of risk-grade changes on a Loan. Regulators audit rating drift, so every migration is captured here. AnnualReview also writes a row even when the grade is reaffirmed unchanged.
-- ----------------------------------------------------------------------------
CREATE TABLE risk_rating_history (
  risk_rating_history_id              TEXT                 PRIMARY KEY,         -- Primary key (synthesized from the calculated Name — the table's logical key — so it wins over incidental Id-ending attribute fields).
  loan                                TEXT                ,                     -- FK to the Loan whose grade changed.
  changed_by_user                     TEXT                ,                     -- FK to Users: who recorded the migration.
  effective_date                      TIMESTAMPTZ         ,                     -- Date the new grade takes effect.
  prior_grade                         INTEGER             ,                     -- Grade before this change; null on initial rating.
  new_grade                           INTEGER             ,                     -- Grade after this change.
  reason                              TEXT                                      -- Free-text justification for the migration.
);
COMMENT ON TABLE risk_rating_history IS 'Time-series of risk-grade changes on a Loan. Regulators audit rating drift, so every migration is captured here. AnnualReview also writes a row even when the grade is reaffirmed unchanged.';
COMMENT ON COLUMN risk_rating_history.risk_rating_history_id IS 'Primary key (synthesized from the calculated Name — the table''s logical key — so it wins over incidental Id-ending attribute fields).';
COMMENT ON COLUMN risk_rating_history.loan IS 'FK to the Loan whose grade changed.';
COMMENT ON COLUMN risk_rating_history.changed_by_user IS 'FK to Users: who recorded the migration.';
COMMENT ON COLUMN risk_rating_history.effective_date IS 'Date the new grade takes effect.';
COMMENT ON COLUMN risk_rating_history.prior_grade IS 'Grade before this change; null on initial rating.';
COMMENT ON COLUMN risk_rating_history.new_grade IS 'Grade after this change.';
COMMENT ON COLUMN risk_rating_history.reason IS 'Free-text justification for the migration.';

-- ----------------------------------------------------------------------------
-- Documents: Files in the DocumentVault. A document attaches to either a Business (tax returns, formation docs) or a Loan (note, security agreement, appraisal). Both FKs are nullable so a document can hang off the appropriate parent.
-- ----------------------------------------------------------------------------
CREATE TABLE documents (
  documents_id                        TEXT                 PRIMARY KEY,         -- Primary key (synthesized from the calculated Name — the table's logical key — so it wins over incidental Id-ending attribute fields).
  business                            TEXT                ,                     -- Optional FK to a Business (nullable for loan-only docs).
  loan                                TEXT                ,                     -- Optional FK to a Loan (nullable for business-only docs).
  uploaded_by_user                    TEXT                ,                     -- Optional FK to the User who uploaded (null when uploaded via the BusinessClientPortal).
  filename                            TEXT                ,                     -- Original filename in the vault.
  document_type                       TEXT                ,                     -- TaxReturn, FormationDoc, FinancialStatement, Note, SecurityAgreement, Appraisal, etc.
  ocr_indexed                         BOOLEAN             ,                     -- True once OCR has indexed the document into SearchAndIndexing.
  uploaded_via                        TEXT                ,                     -- Source surface: RMDashboard, BranchBankerPortal, BusinessClientPortal, AdminConsole, API.
  uploaded_at                         TIMESTAMPTZ                               -- Upload timestamp.
);
COMMENT ON TABLE documents IS 'Files in the DocumentVault. A document attaches to either a Business (tax returns, formation docs) or a Loan (note, security agreement, appraisal). Both FKs are nullable so a document can hang off the appropriate parent.';
COMMENT ON COLUMN documents.documents_id IS 'Primary key (synthesized from the calculated Name — the table''s logical key — so it wins over incidental Id-ending attribute fields).';
COMMENT ON COLUMN documents.business IS 'Optional FK to a Business (nullable for loan-only docs).';
COMMENT ON COLUMN documents.loan IS 'Optional FK to a Loan (nullable for business-only docs).';
COMMENT ON COLUMN documents.uploaded_by_user IS 'Optional FK to the User who uploaded (null when uploaded via the BusinessClientPortal).';
COMMENT ON COLUMN documents.filename IS 'Original filename in the vault.';
COMMENT ON COLUMN documents.document_type IS 'TaxReturn, FormationDoc, FinancialStatement, Note, SecurityAgreement, Appraisal, etc.';
COMMENT ON COLUMN documents.ocr_indexed IS 'True once OCR has indexed the document into SearchAndIndexing.';
COMMENT ON COLUMN documents.uploaded_via IS 'Source surface: RMDashboard, BranchBankerPortal, BusinessClientPortal, AdminConsole, API.';
COMMENT ON COLUMN documents.uploaded_at IS 'Upload timestamp.';

-- ----------------------------------------------------------------------------
-- Interactions: Unified activity-log feed for a Business. An Interaction is intentionally generic: InteractionType discriminates Note, Call, Visit, Task, Meeting, or SystemEvent. Covenant breaches, document requests, and other machine actions are written as SystemEvent interactions so they appear in the same stream as human-logged activity.
-- ----------------------------------------------------------------------------
CREATE TABLE interactions (
  interactions_id                     TEXT                 PRIMARY KEY,         -- Primary key (synthesized from the calculated Name — the table's logical key — so it wins over incidental Id-ending attribute fields).
  business                            TEXT                ,                     -- FK to the parent Business.
  "user"                              TEXT                ,                     -- FK to Users: who logged the interaction (null for system-generated or customer-portal-originated rows).
  interaction_type                    TEXT                ,                     -- Note, Call, Visit, Task, Meeting, or SystemEvent.
  subject                             TEXT                ,                     -- Short subject line (used in compound PK).
  body                                TEXT                ,                     -- Long-form body of the interaction.
  interaction_date                    TIMESTAMPTZ         ,                     -- Date the interaction occurred or was logged.
  due_date                            TIMESTAMPTZ         ,                     -- For Task-type interactions: due date.
  source                              TEXT                                      -- Origin surface: RMDashboard, BusinessClientPortal, BranchBankerPortal, SystemEvent.
);
COMMENT ON TABLE interactions IS 'Unified activity-log feed for a Business. An Interaction is intentionally generic: InteractionType discriminates Note, Call, Visit, Task, Meeting, or SystemEvent. Covenant breaches, document requests, and other machine actions are written as SystemEvent interactions so they appear in the same stream as human-logged activity.';
COMMENT ON COLUMN interactions.interactions_id IS 'Primary key (synthesized from the calculated Name — the table''s logical key — so it wins over incidental Id-ending attribute fields).';
COMMENT ON COLUMN interactions.business IS 'FK to the parent Business.';
COMMENT ON COLUMN interactions."user" IS 'FK to Users: who logged the interaction (null for system-generated or customer-portal-originated rows).';
COMMENT ON COLUMN interactions.interaction_type IS 'Note, Call, Visit, Task, Meeting, or SystemEvent.';
COMMENT ON COLUMN interactions.subject IS 'Short subject line (used in compound PK).';
COMMENT ON COLUMN interactions.body IS 'Long-form body of the interaction.';
COMMENT ON COLUMN interactions.interaction_date IS 'Date the interaction occurred or was logged.';
COMMENT ON COLUMN interactions.due_date IS 'For Task-type interactions: due date.';
COMMENT ON COLUMN interactions.source IS 'Origin surface: RMDashboard, BusinessClientPortal, BranchBankerPortal, SystemEvent.';

-- ----------------------------------------------------------------------------
-- Constraints: Operative constraints (RuleSpeak): must / must not / should obligations, each keyed on a boolean calculated field the rulebook already computes. The deontic operator lives in the Deontic column (data), never in a field name.
-- ----------------------------------------------------------------------------
CREATE TABLE constraints (
  constraints_id                      TEXT                 PRIMARY KEY,         -- Primary key (synthesized from the calculated Name — the table's logical key — so it wins over incidental Id-ending attribute fields).
  constraint_key                      TEXT                ,                     -- Stable constraint identifier, e.g. loan-sod.
  entity                              TEXT                ,                     -- Anchor entity (singular table name, e.g. Loan). Must resolve to a table.
  predicate                           TEXT                ,                     -- Name of a boolean calculated field on Entity that the DAG computes (e.g. SegregationOfDutiesOk). The deontic operator is asserted over this truth.
  deontic                             TEXT                ,                     -- The obligation: MustBeTrue | MustNotBeTrue | ShouldBeTrue.
  severity                            TEXT                ,                     -- hard (always enforced) | soft (advisory) | override (waivable by an authorized approver).
  message                             TEXT                ,                     -- Guidance text shown when the constraint is violated.
  rule_group                          TEXT                ,                     -- Section grouping for the rule, e.g. 'Credit Policy', 'BSA/AML (CDD)'.
  source_citation                     TEXT                ,                     -- Regulatory or policy citation backing the constraint.
  rule_speak_override                 TEXT                ,                     -- Hand-authored canonical RuleSpeak sentence, used verbatim when auto-render isn't smooth enough. Still part of the SSoT.
  is_active                           BOOLEAN                                   -- When false, the constraint is retired and not rendered.
);
COMMENT ON TABLE constraints IS 'Operative constraints (RuleSpeak): must / must not / should obligations, each keyed on a boolean calculated field the rulebook already computes. The deontic operator lives in the Deontic column (data), never in a field name.';
COMMENT ON COLUMN constraints.constraints_id IS 'Primary key (synthesized from the calculated Name — the table''s logical key — so it wins over incidental Id-ending attribute fields).';
COMMENT ON COLUMN constraints.constraint_key IS 'Stable constraint identifier, e.g. loan-sod.';
COMMENT ON COLUMN constraints.entity IS 'Anchor entity (singular table name, e.g. Loan). Must resolve to a table.';
COMMENT ON COLUMN constraints.predicate IS 'Name of a boolean calculated field on Entity that the DAG computes (e.g. SegregationOfDutiesOk). The deontic operator is asserted over this truth.';
COMMENT ON COLUMN constraints.deontic IS 'The obligation: MustBeTrue | MustNotBeTrue | ShouldBeTrue.';
COMMENT ON COLUMN constraints.severity IS 'hard (always enforced) | soft (advisory) | override (waivable by an authorized approver).';
COMMENT ON COLUMN constraints.message IS 'Guidance text shown when the constraint is violated.';
COMMENT ON COLUMN constraints.rule_group IS 'Section grouping for the rule, e.g. ''Credit Policy'', ''BSA/AML (CDD)''.';
COMMENT ON COLUMN constraints.source_citation IS 'Regulatory or policy citation backing the constraint.';
COMMENT ON COLUMN constraints.rule_speak_override IS 'Hand-authored canonical RuleSpeak sentence, used verbatim when auto-render isn''t smooth enough. Still part of the SSoT.';
COMMENT ON COLUMN constraints.is_active IS 'When false, the constraint is retired and not rendered.';

-- ============================================================================
-- FK INDEXES - Performance only, always applied
-- ============================================================================

-- Businesses
CREATE INDEX IF NOT EXISTS idx_businesses_relationship_manager ON businesses (relationship_manager);
CREATE INDEX IF NOT EXISTS idx_businesses_referral_source ON businesses (referral_source);

-- BeneficialOwners
CREATE INDEX IF NOT EXISTS idx_beneficial_owners_business ON beneficial_owners (business);

-- Contacts
CREATE INDEX IF NOT EXISTS idx_contacts_business ON contacts (business);

-- Accounts
CREATE INDEX IF NOT EXISTS idx_accounts_business ON accounts (business);

-- Loans
CREATE INDEX IF NOT EXISTS idx_loans_business ON loans (business);
CREATE INDEX IF NOT EXISTS idx_loans_originating_rm ON loans (originating_rm);
CREATE INDEX IF NOT EXISTS idx_loans_underwriter ON loans (underwriter);

-- Covenants
CREATE INDEX IF NOT EXISTS idx_covenants_loan ON covenants (loan);

-- RiskRatingHistory
CREATE INDEX IF NOT EXISTS idx_risk_rating_history_loan ON risk_rating_history (loan);
CREATE INDEX IF NOT EXISTS idx_risk_rating_history_changed_by_user ON risk_rating_history (changed_by_user);

-- Documents
CREATE INDEX IF NOT EXISTS idx_documents_business ON documents (business);
CREATE INDEX IF NOT EXISTS idx_documents_loan ON documents (loan);
CREATE INDEX IF NOT EXISTS idx_documents_uploaded_by_user ON documents (uploaded_by_user);

-- Interactions
CREATE INDEX IF NOT EXISTS idx_interactions_business ON interactions (business);
CREATE INDEX IF NOT EXISTS idx_interactions_user ON interactions ("user");

-- 16 FK index(es) declared.
